src/snowcli/cli/connection.py, src/snowcli/snowsql_config.py
=> write config file if not exists

src/snowcli/cli/warehouse.py
=> fix warehouse --help

README.md
Bringing README in line with https://github.com/Snowflake-Labs/snowcli/blob/bc70a3c40847296ac6bb393c616a348a532436e0/pyproject.toml#L8
=> python version update in README

src/snowcli/cli/stage.py
small bug preventing working with Python 3.10 post updates
=> fix incompatible python type

src/snowcli/cli/streamlit.py, src/snowcli/snow_connector.py
If host is not set, fall back to old behavior of return the embedded url of the app
=> Fix streamlit deploy without host

.pre-commit-config.yaml, pyproject.toml, src/snowcli/cli/__init__.py, src/snowcli/cli/connection.py, src/snowcli/cli/function.py, src/snowcli/cli/procedure.py, src/snowcli/cli/snowpark_shared.py, src/snowcli/cli/stage.py, src/snowcli/cli/streamlit.py, src/snowcli/cli/warehouse.py, src/snowcli/config.py, src/snowcli/snow_connector.py, src/snowcli/snowsql_config.py, src/snowcli/utils.py, src/templates/default_function/app.py, src/templates/default_procedure/app.py, src/templates/default_procedure/local_connection.py, tests/test_main.py
Let me know if you'd rather me turn off the black setting around standardizing on double-quotes (which is the bulk of the changes)
=> Formatting and linting with black + ruff

pyproject.toml
It does seem to fix #19 once the secure-local-storage version has been installed
=> Cache SSH connections locally

src/snowcli/cli/stage.py, src/snowcli/cli/streamlit.py, src/snowcli/snow_connector.py, src/snowcli/sql/create_stage.sql, src/snowcli/sql/drop_stage.sql, src/snowcli/sql/drop_streamlit.sql
Adds:
* `snow streamlit drop`
* `snow stage drop`
* `snow stage create`
=> Add drop/create stage, drop streamlit commands

src/snowcli/__about__.py, src/snowcli/snowsql_config.py, src/snowcli/utils.py
Resolves https://github.com/Snowflake-Labs/snowcli/issues/77
Resolves https://github.com/Snowflake-Labs/snowcli/issues/78
=> fixing zipfile

src/snowcli/cli/__init__.py, src/snowcli/cli/render.py, tests/test_render.py
Given template like:
```
CREATE ROLE APP_ROLE;
CREATE SCHEMA APP;
GRANT USAGE ON SCHEMA APP TO ROLE APP_ROLE;
-- procedures
CREATE OR REPLACE PROCEDURE PUBLIC.FOO()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
{{ "proc.js" | procedure_from_js_file }}
$$;
```
you can do:
```
➜ snow render template setup.sql
CREATE ROLE APP_ROLE;
CREATE SCHEMA APP;
GRANT USAGE ON SCHEMA APP TO ROLE APP_ROLE;
-- procedures
CREATE OR REPLACE PROCEDURE PUBLIC.FOO()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
var module = {};
var exports = {};
module.exports = exports;
(function() {
function foo() {
}
module.exports = foo
})()
return module.exports.apply(this, arguments);
$$;
```
=> Add render template command

src/snowcli/cli/__init__.py
In this PR I added dynamic importing to all sub-modules inside `snowcli.cli`. So now every file will be added that defines a global `app`.
This will make it so that we don't need to manually import new modules and call `add_typer` on their apps
=> implement dynamic cli app importing

src/snowcli/cli/sql.py
Makes the output more verbose with query results:
```+----------------------------------------------------------------------------------------------------------------------+
| Query                                                                                                                |
|----------------------------------------------------------------------------------------------------------------------|
| SET APP_NAME = 'turbaszek_SDK_APP';                                                                                  |
|----------------------------------------------------------------------------------------------------------------------|
| {'status': 'Statement executed successfully.'}                                                                       | …
```
=> Add result printing to sql command

src/snowcli/__about__.py, src/snowcli/utils.py
Fixed a bug where if no `SNOWCLI_INCLUDE_PATHS` was defined it would grab all files from file root
=> Bug fix package

src/snowcli/__about__.py, src/snowcli/sql/drop_streamlit.sql, tests/__snapshots__/test_snow_connector.ambr
We are missing the role specifications for this command.
=> Add role to drop streamlit

src/snowcli/cli/streamlit.py, src/snowcli/snow_connector.py, src/snowcli/sql/create_streamlit.sql, src/snowcli/sql/drop_streamlit.sql, src/snowcli/sql/get_stage.sql, src/snowcli/sql/list_stage.sql, src/snowcli/sql/put_stage.sql, src/snowcli/sql/remove_from_stage.sql, tests/__snapshots__/test_snow_connector.ambr, tests/test_snow_connector.py
Per @sfc-gh-asaini, [the DDL for CREATE STREAMLIT has changed. ](https://snowflake.slack.com/archives/C03E8TLQ7LP/p1684167544391709)
We need to update the command to match this new format. This change is a breaking change from the previous version so ROOT_LOCATION will no longer work. 
However, since we have moved to embedded stages, it may be easier to keep creating them so we can upload other files there. For that reason, I am not removing the CREATE STAGE portion.
=> Change ROOT_LOCATION to FROM

src/snowcli/cli/package.py, src/snowcli/cli/procedure_coverage/clear.py, src/snowcli/cli/procedure_coverage/report.py, src/snowcli/cli/snowpark_shared.py, src/snowcli/cli/streamlit.py, src/snowcli/utils.py
Changed names of some functions in utils.py to make them consistent with python naming conventions.
I predict no behaviour change, as none of the functions is called directly by the user.
=> Changed function names in utils.py

.pre-commit-config.yaml
Added argument --select N for ruff check during pre-commit.
It shows all the function, variable and class names that do not conform to PEP-8 conventions.
=> 824873 add checks in ruff to enfore naming conventions

src/snowcli/cli/__init__.py, src/snowcli/cli/sql.py, tests/test_sql.py, tests/testing_utils/result_assertions.py
* Removed local variables printing on exceptions (changed one flag in Typer's constructor invocation). It should make CLI safer to use in scripts (we won't print passwords or other sensitive data).
* Improved `sql` command errors (using click's UsageError instead generic ValueError) - it results in nice handling of error by click library.
* Added new unit test case for sql command error for lack of user authentication -> `test_sql_fails_if_user_not_authenticated`.
=> Removed local variables printing on exceptions. Improved sql command errors.

src/snowcli/cli/__init__.py, src/snowcli/cli/snowpark/procedure_coverage/clear.py, src/snowcli/cli/snowpark_shared.py, src/snowcli/cli/stage.py, src/snowcli/cli/streamlit.py, src/snowcli/cli/warehouse.py, src/snowcli/output/formats.py, src/snowcli/output/printing.py, src/snowcli/utils.py, tests/output/test_printing.py
=> Refactor and extend output formatting

.github/workflows/test.yaml
This step is unnecessary because tox takes dependencies from pyproject.toml
=> Deleted unnecessary step during tests

src/snowcli/cli/__init__.py, src/snowcli/config.py, tests/test.toml, tests/test_main.py
=> Allow specifying snowcli config using flag

src/snowcli/cli/__init__.py, src/snowcli/cli/connection.py, src/snowcli/cli/snowpark/__init__.py, src/snowcli/cli/snowpark/function.py, src/snowcli/cli/snowpark/procedure.py, src/snowcli/cli/stage.py, src/snowcli/cli/streamlit.py, src/snowcli/cli/warehouse.py
=> Add missing help information

README.md, pyproject.toml, tests/integration/snowflake_connector.py, tests/integration/test_warehouse.py, tox.ini
* Added integration test that execute query on snowflake and compare result with snowpark query result
* Test is not completely ready, it works locally with properly prepared configuration
* Added `integration` mark in tests, now `pytest` will execute everything except tests with `integration` mark. Execute `pytest -m integration` to run only integration tests
=> Added first integration test (not fully working yet)

.github/pull_request_template.md
Added up-to-date check to the PR checklist to not forget about merges/rebases before sending PR to review.
=> Added up-to-date check to the PR checklist

src/snowcli/cli/__init__.py, src/snowcli/cli/common/flags.py, src/snowcli/cli/connection.py, src/snowcli/cli/render.py, src/snowcli/cli/snowpark/__init__.py, src/snowcli/cli/snowpark/function.py, src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark/procedure.py, src/snowcli/cli/snowpark/procedure_coverage/__init__.py, src/snowcli/cli/stage.py, src/snowcli/cli/streamlit.py, src/snowcli/cli/warehouse.py
=> Introduce common context_settings

README.md
Changed images in readme to github links
=> Changed images in readme to github links

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
Added bug and feature issue templates
=> Added issue templates

src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark_shared.py, src/snowcli/cli/streamlit.py, src/snowcli/snow_connector.py, src/snowcli/sql/put_stage.sql, tests/__snapshots__/test_snow_connector.ambr, tests/test_snow_connector.py
streamlit deploy was failing because it would first try to create the embedded stage, which causes a failure
I fixed this by making the create stage optional with an argument
I also refactored the upload_file_to_stage to use use_sql to make it more standard and easier to test, and added tests around it
I tested this locally with
```sh
snow streamlit create <name>
snow streamlit deploy <name>
```
=> Fix streamlit deploy

README.md, src/snowcli/cli/__init__.py, src/snowcli/cli/connection.py, src/snowcli/cli/loggers.py, src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark/procedure_coverage/clear.py, src/snowcli/cli/snowpark/procedure_coverage/report.py, src/snowcli/cli/snowpark_shared.py, src/snowcli/cli/streamlit.py, src/snowcli/config.py, src/snowcli/snow_connector.py, src/snowcli/utils.py
- Added logging to console
- How it will work with parameters:
- `-v/--verbose` - print info and higher level logs
- `--debug` - print debug and higher level logs, logs have different format
- none of above - print only error logs
=> Added logging

src/snowcli/cli/__init__.py, src/snowcli/cli/common/snow_cli_global_context.py, src/snowcli/cli/main/snow_cli_main_typer.py
* Another approach to handle exceptions, in place of following closed PRs: 
* https://github.com/Snowflake-Labs/snowcli/pull/183
* https://github.com/Snowflake-Labs/snowcli/pull/191
* Added `SnowCliGobalContext` and `SnowCliGobalContextManager` responsible for holding the context/state visible in whole CLI code (also outside Typer/Click command execution).
* Added `SnowCliMainTyper` extending `Typer`. It is responsible for adding global exception handling to app() call.
* This global exception handling is not tested because CliRunner used in tests runs commands on its own (it doesn't call app()).
=> Global exception handling

.github/workflows/jira_issue.yml
=> Fix jira integration

src/snowcli/cli/common/flags.py, src/snowcli/cli/connection.py, src/snowcli/cli/snowpark/function.py, src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark/procedure.py, src/snowcli/cli/snowpark/procedure_coverage/clear.py, src/snowcli/cli/snowpark/procedure_coverage/report.py, src/snowcli/cli/sql.py, src/snowcli/cli/stage.py, src/snowcli/cli/streamlit.py, src/snowcli/cli/warehouse.py, src/snowcli/utils.py, tests/snowsql.toml, tests/test_connection.py, tests/test_snow_connector.py, tests/test_utils.py
* [ x] I've confirmed that my changes are up-to-date with the target branch.
Introduce common flags to avoid code duplication.
=> Standardise cli flags

src/snowcli/__about__.py, src/snowcli/cli/connection.py, src/snowcli/sql/put_stage.sql, tests/__snapshots__/test_snow_connector.ambr
=> Fix stage put command template

src/snowcli/cli/common/flags.py, src/snowcli/cli/connection.py, tests/__snapshots__/test_connection.ambr
=> Connection add command fix

src/snowcli/sql/call_procedure.sql, src/snowcli/sql/create_function.sql, src/snowcli/sql/create_procedure.sql, src/snowcli/sql/create_stage.sql, src/snowcli/sql/create_streamlit.sql, src/snowcli/sql/describe_function.sql, src/snowcli/sql/describe_procedure.sql, src/snowcli/sql/describe_streamlit.sql, src/snowcli/sql/drop_function.sql, src/snowcli/sql/drop_procedure.sql, src/snowcli/sql/drop_stage.sql, src/snowcli/sql/drop_streamlit.sql, src/snowcli/sql/execute_function.sql, src/snowcli/sql/get_stage.sql, src/snowcli/sql/get_streamlit_url.sql, src/snowcli/sql/list_functions.sql, src/snowcli/sql/list_procedures.sql, src/snowcli/sql/list_stage.sql, src/snowcli/sql/list_stages.sql, src/snowcli/sql/list_streamlits.sql, src/snowcli/sql/put_stage.sql, src/snowcli/sql/remove_from_stage.sql, src/snowcli/sql/set_env.sql, src/snowcli/sql/set_procedure_comment.sql, src/snowcli/sql/share_streamlit.sql, src/snowcli/sql/show_warehouses.sql, tests/__snapshots__/test_snow_connector.ambr
=> Extracted env setting in sql templates

src/snowcli/cli/stage.py
=> Stage remove fix

README.md
I updated the Readme to reflect the changes for creating connections. I also added a note that links to the PrPr registration form, per Anurag's request.
...
=> Initial update draft

src/snowcli/cli/snowpark/cp.py, src/snowcli/cli/snowpark/jobs.py, src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark/procedure_coverage/clear.py, src/snowcli/cli/snowpark/procedure_coverage/report.py, src/snowcli/cli/snowpark/registry.py, src/snowcli/cli/snowpark/services.py, src/snowcli/cli/snowpark_shared.py, src/snowcli/cli/sql.py, src/snowcli/cli/stage.py, src/snowcli/cli/streamlit.py, src/snowcli/cli/warehouse.py, src/snowcli/config.py, src/snowcli/exception.py, src/snowcli/snow_connector.py, tests/test_connection.py, tests/test_main.py, tests/test_snow_connector.py, tests/test_sql.py
Remove is_auth method. Move connect_to_snowflake to snow_connector module. Add nicer handling of Snowflake exceptions when estabilishing connection.
=> Refactor connection creation

.pre-commit-config.yaml, CONTRIBUTING.md, src/snowcli/cli/__init__.py, src/snowcli/pycharm_remote_debug.py
Added options to connect CLI to PyCharm remote debug server. Details in `CONTRIBUTING.md`.
=> Added options to connect CLI to PyCharm remote debug server

src/snowcli/cli/sql.py, tests/test_sql.py, tests_integration/config/connection_configs.toml, tests_integration/config/test.toml, tests_integration/conftest.py, tests_integration/test_files/sql_multi_queries.sql, tests_integration/test_sql.py, tests_integration/test_utils.py
Changed result print for snow sql command
Added integration tests for snow sql
Added utils to extract data from print_db_cursor mock
=> Added integration tests for snow sql

src/snowcli/cli/snowpark/package.py
=> Fix for cursor not subscriptable

CONTRIBUTING.md, src/snowcli/config.py, src/snowcli/exception.py, tests/config/env_variables_config, tests/conftest.py, tests/test.toml, tests/test_config.py, tests/test_main.py, tests/test_snow_connector.py, tests_integration/config/connection_configs.toml, tests_integration/conftest.py, tests_integration/snowflake_connector.py
Changed getting env variables
Adapted integration test configuration
Adapted snowpark connection
Using default ("dev") connection in integration tests
=> Environment variables in integration tests adapted to new configuration

pyproject.toml
This reverts commit 7d08cd1977eadb8e25d7fd54f9a6fd498de5d45f.
...
=> Revert "Bump tox from 4.6.3 to 4.6.4 (#231)"

src/snowcli/cli/stage.py, tests_integration/test_sql.py, tests_integration/test_stage.py, tests_integration/test_utils.py
Added integration tests for snow stage
=> Integration tests for snow stage

src/snowcli/cli/connection.py, src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark_shared.py, src/templates/default_procedure/app.py
Removed printing objects that could contain credentials
Log small fixes
=> Removed printing objects that could contain credentials and small fixes

.github/workflows/build.yaml, CONTRIBUTING.md
=> Validate dev dependencies installation on CI

tests_integration/snowflake_connector.py, tests_integration/test_stage.py
Creating new database before integration tests
Cleanup database after tests
=> Create new database for each run of integration tests

src/snowcli/__init__.py, src/snowcli/cli/loggers.py
This removes the problem with `Failed to import ArrowResult. No Apache Arrow result set format can be used.`
=> Suppress logging from Snowflake python connector

tests_integration/conftest.py, tests_integration/test_cp.py, tests_integration/test_stage.py
Integration tests for snowpark compute pool
=> Integration tests for snowpark compute pool

src/snowcli/cli/common/flags.py, src/snowcli/cli/connection.py, src/snowcli/config.py, src/snowcli/snow_connector.py, tests/test.toml, tests/test_config.py, tests/test_connection.py, tests/test_main.py
Mask password in connection list. Introduce constant for default connection. Config callback should not be egar because then --help does not work.
=> Mask password in connection list

.github/workflows/test.yaml, pyproject.toml, tox.ini
=> Add coverage report

src/snowcli/cli/connection.py, tests/test_connection.py
=> Add connection test command

src/snowcli/__about__.py
=> Bump version to 1.0.1

pyproject.toml, tox.ini
=> Remove pytest-cov due to IDE debugger not working

tests/test_utils.py, tests/testing_utils/files_and_dirs.py
Change from manually creating directories and files for unit tests for utils.py to files generated by tempfile
+ minor refactor
=> Switch test_utils to tempfile

CONTRIBUTING.md, src/snowcli/cli/app.py, src/snowcli/cli/snowpark/procedure.py, src/snowcli/output/printing.py, src/templates/default_function/app.py, src/templates/default_function/config.toml, src/templates/default_function/requirements.txt, src/templates/default_procedure/app.py, src/templates/default_procedure/config.toml, tests/test_main.py, tests_integration/__snapshots__/test_snowpark_function.ambr, tests_integration/config/connection_configs.toml, tests_integration/snowflake_connector.py, tests_integration/test_snowpark_function.py
=> Add --info option

tests_integration/snowflake_connector.py, tests_integration/test_cp.py, tests_integration/test_package.py, tests_integration/test_snowpark_function.py, tests_integration/test_sql.py, tests_integration/test_stage.py, tests_integration/test_streamlit.py, tests_integration/test_warehouse.py
* For each integration test new database is created
* Removed second connection to Snowflake
=> Create new database for each integration test

src/snowcli/cli/snowpark/procedure_coverage/clear.py, src/snowcli/cli/snowpark/procedure_coverage/report.py, src/snowcli/cli/stage.py, src/snowcli/cli/warehouse.py, src/snowcli/output/decorators.py, src/snowcli/snow_connector.py, src/snowcli/sql/drop_stage.sql, src/snowcli/sql/list_stage.sql, src/snowcli/sql/list_stages.sql, src/snowcli/sql/show_warehouses.sql, tests/__snapshots__/test_snow_connector.ambr, tests/__snapshots__/test_warehouse.ambr, tests/conftest.py, tests/test_main.py, tests/test_snow_connector.py, tests/test_stage.py, tests/test_warehouse.py, tests_integration/test_stage.py, tests_integration/test_warehouse.py
=> Refactor stage warehouse

tests_integration/test_streamlit.py
Enabled streamlit integration tests
Small fix with role
=> Enabled streamlit integration tests

pyproject.toml
=> Pin urllib3 because of snowflake python connector requirement

.gitignore, src/snowcli/cli/app.py, src/snowcli/cli/snowpark/function.py, src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark/procedure.py, src/snowcli/docs/generator.py, src/snowcli/docs/templates/overview.rst.jinja2, src/snowcli/docs/templates/usage.rst.jinja2, tests/test_main.py
=> Generate usage documentation automatically

.github/workflows/integration_test.yaml, tests_integration/test_sql.py
=> Enabled integration tests

src/snowcli/cli/common/decorators.py, src/snowcli/cli/common/flags.py, src/snowcli/cli/common/snow_cli_global_context.py, src/snowcli/cli/snowpark/package.py, src/snowcli/cli/snowpark/procedure.py, src/snowcli/cli/sql.py, tests/test_sql.py, tox.ini
=> Add global connection flags

src/snowcli/cli/common/decorators.py, src/snowcli/cli/common/flags.py, src/snowcli/cli/common/snow_cli_global_context.py, src/snowcli/utils.py, tests/test_sql.py, tests_integration/snowflake_connector.py, tests_integration/test_package.py, tests_integration/test_sql.py
=> Fix behaviour of global connection option 

src/snowcli/cli/sql.py, src/snowcli/cli/streamlit.py, src/snowcli/output/printing.py, tests/output/test_printing.py, tests/test_snow_connector.py, tests_integration/test_sql.py, tests_integration/test_streamlit.py
Added print_db_cursors function to handle many responses in single command
=> Handling results of multiple queries

src/snowcli/cli/connection.py, tests/__snapshots__/test_connection.ambr, tests/test_connection.py
=> Add validation for connection's port value

.github/workflows/test.yaml
=> Changed codecov version to commit sha

src/snowcli/cli/snowpark/package.py, tests/test_package.py
=> Package create message fix

src/snowcli/cli/snowpark/function/commands.py, src/snowcli/cli/snowpark/procedure/commands.py, src/snowcli/utils.py, tests/__snapshots__/test_snow_connector.ambr, tests/test_procedure.py
=> Standarised project initialisation

tests/test_performance.py
=> Added performance test

README.md
Streamlit in Snowflake is still in private preview, so I edited the readme to reflect that. We'll hopefully be in Public preview soon and I look forward to switching this back.
=> SiS is in PrPr, not PuPr! Edited here

src/snowcli/cli/snowpark/package/commands.py, src/snowcli/cli/snowpark/package/manager.py, tests/test_package.py
Unified commands output in snowpark package
=> Unify commands output in snowpark package

src/snowcli/cli/app.py, src/snowcli/cli/common/decorators.py, src/snowcli/cli/common/flags.py, src/snowcli/cli/common/snow_cli_global_context.py, src/snowcli/cli/connection.py, src/snowcli/cli/snowpark/compute_pool/commands.py, src/snowcli/cli/snowpark/function/commands.py, src/snowcli/cli/snowpark/jobs/commands.py, src/snowcli/cli/snowpark/package/commands.py, src/snowcli/cli/snowpark/procedure/commands.py, src/snowcli/cli/snowpark/services/commands.py, src/snowcli/cli/sql.py, src/snowcli/cli/stage/commands.py, src/snowcli/cli/streamlit/commands.py, src/snowcli/cli/warehouse.py, src/snowcli/output/printing.py, tests/test_command_options.py, tests/test_common_decorators.py, tests/test_connection.py, tests/test_main.py, tests_integration/conftest.py, tests_integration/test_sql.py, tests_integration/testing_utils/snowpark_utils.py
Moved format, verbose and debug options to global options
=> Added format, verbose and debug to global options

src/snowcli/cli/main/snow_cli_main_typer.py
* Fixed handling of chained exceptions (https://github.com/Snowflake-Labs/snowcli/issues/324)
* No automatic tests added because the change is not testable in our current test mechanism. Global exception handling wraps main Typer instance's `__call__` (see `SnowCliMainTyper`), and this is not invoked in tests. Tests use `CliRunner` from `click.testing` which executes our CLI logic own way.
<details>
<summary>Click to expand</summary>
```
(venv) ➜  snowcli git:(main) snow connection list
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/pjob/Git/Snowflake-Labs/snowcli/src/snowcli/cli/app.py:100 in default                     │
│                                                                                                  │
│ …
```
=> Fixed chained exceptions

src/snowcli/cli/snowpark/function/commands.py, src/snowcli/cli/snowpark/procedure/commands.py, src/snowcli/output/printing.py, tests/output/test_printing.py, tests_integration/conftest.py, tests_integration/test_package.py, tests_integration/testing_utils/assertions/test_result_assertions.py, tests_integration/testing_utils/snowpark_utils.py
Changed asserts to check commands responses in JSON format, where it was possible
=> Changed asserts on commands output to json

src/templates/default_procedure/app.py, tests_integration/__snapshots__/test_procedure.ambr
* Changes from #286 but with fixed integration tests
* Fixes https://github.com/Snowflake-Labs/snowcli/issues/285
=> Applied fix to default procedure template from PR #286

tests/snowpark/test_snowpark_shared.py
=> Fix tests after bad merge

src/snowcli/cli/snowpark/package/manager.py, src/snowcli/cli/snowpark/procedure_coverage/manager.py, src/snowcli/snow_connector.py, src/snowcli/sql/create_stage.sql, src/snowcli/sql/get_stage.sql, src/snowcli/sql/put_stage.sql, src/snowcli/sql/remove_from_stage.sql, src/snowcli/sql/set_env.sql, tests/test_package.py, tests/test_snow_connector.py
=> Snow connector cleanup

src/snowcli/__about__.py
=> Bump version to 1.1.0

src/snowcli/cli/common/snow_cli_global_context.py, src/snowcli/cli/common/sql_execution.py, src/snowcli/cli/project/definition.py, src/snowcli/cli/snowpark/procedure_coverage/manager.py, src/snowcli/cli/snowpark/registry/manager.py, src/snowcli/cli/streamlit/manager.py, src/snowcli/snow_connector.py, tests/project/test_config.py, tests/test_main.py, tests/test_snow_connector.py, tests/test_sql.py
Removed SnowflakeConnector class
=> Removed SnowflakeConnector class

src/snowcli/cli/snowpark/procedure_coverage/manager.py
=> Coverage report selection refactor

src/snowcli/cli/stage/commands.py, src/snowcli/docs/generator.py
Flatted generated docs structure
=> Changed docs generation

src/snowcli/__about__.py
* Changed version from `1.1.0` to `1.1.1-dev`.
=> Marking version as dev

src/snowcli/app/cli_app.py, src/snowcli/cli/connection/commands.py, src/snowcli/cli/snowpark/compute_pool/commands.py, src/snowcli/cli/snowpark/function/commands.py, src/snowcli/cli/snowpark/jobs/commands.py, src/snowcli/cli/snowpark/package/commands.py, src/snowcli/cli/snowpark/procedure/commands.py, src/snowcli/cli/snowpark/procedure_coverage/commands.py, src/snowcli/cli/snowpark/registry/commands.py, src/snowcli/cli/snowpark/registry/manager.py, src/snowcli/cli/snowpark/services/commands.py, src/snowcli/cli/sql/commands.py, src/snowcli/cli/stage/commands.py, src/snowcli/cli/streamlit/commands.py, src/snowcli/cli/warehouse/commands.py, src/snowcli/output/decorators.py, src/snowcli/output/printing.py, src/snowcli/output/types.py, tests/__snapshots__/test_package.ambr, tests/__snapshots__/test_warehouse.ambr, tests/output/test_printing.py, tests/snowpark/__snapshots__/test_procedure_coverage.ambr, tests/test_main.py, tests/test_snow_connector.py, tests/test_warehouse.py, tests/testing_utils/fixtures.py, tests_integration/conftest.py, tests_integration/test_package.py, tests_integration/testing_utils/assertions/test_result_assertions.py, tests_integration/testing_utils/snowpark_utils.py
=> Output types

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/workflows/jira_issue.yml
=> Update JIRA create issue action

src/snowcli/app/dev/docs/templates/overview.rst.jinja2, src/snowcli/app/dev/docs/templates/usage.rst.jinja2
=> Updated docs templates

src/snowcli/cli/snowpark_shared.py, src/snowcli/cli/stage/commands.py, src/snowcli/cli/streamlit/commands.py
=> Updated options help

src/snowcli/app/cli_app.py, src/snowcli/app/dev/commands_structure.py
=> Add --structure callback for dev purposes

src/snowcli/app/dev/docs/generator.py, src/snowcli/app/dev/docs/templates/usage.rst.jinja2
=> Changed options selection

CONTRIBUTING.md
This is a small PR to add on some instructions recommended by the SNOWCLI team when using forks. Hoping to benefit other folks with them.
=> Additional Helpful Instructions for CONTRIBUTING.md

.github/workflows/performance_test.yaml, pyproject.toml
=> Performance typo fix

src/snowcli/app/dev/docs/templates/overview.rst.jinja2, src/snowcli/app/dev/docs/templates/usage.rst.jinja2, src/snowcli/cli/stage/commands.py
=> Added missing arguments in syntax and small fixes

src/snowcli/config.py, tests/__snapshots__/test_connection.ambr, tests/test_config.py, tests/test_connection.py
* when you add first connection, that connection become default
* selecting default connection flow:
** get default_connection from config.toml
** if in config.toml is only one connection take it
** if default_connection in config.toml is not set and there is more than 1 connection in config.toml use `dev` connection
=> Connections improvements

CONTRIBUTING.md
=> Updated note how to run integration tests in contribution.md

RELEASE-NOTES.md, src/snowcli/output/printing.py
* Fixes #407
* Too long texts in table cells are now wrapped instead of cropped
I haven't added any automatic tests because it's difficult to create them because of various width of terminals
I did manual testing with the following command:
```bash
snow sql -q "select 'value_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_' as column_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_, 'value_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_' as column_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_, 'value_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_' as column_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_3_, …
```
=> [SNOW-923093] Wrap text in tables

RELEASE-NOTES.md, src/snowcli/cli/snowpark/common.py, src/snowcli/utils.py, tests/snowpark/test_function.py, tests/snowpark/test_procedure.py, tests_integration/test_procedure_coverage.py, tests_integration/testing_utils/snowpark_utils.py
Added parameters for procedure in procedure coverage integration test
Procedure and function have unit tests
=> Added parameters to procedure coverage integration test

src/snowcli/cli/common/sql_execution.py, src/snowcli/cli/nativeapp/commands.py, src/snowcli/cli/nativeapp/init.py, src/snowcli/cli/nativeapp/manager.py, src/snowcli/cli/project/definition.py, src/snowcli/cli/stage/diff.py, src/snowcli/cli/stage/manager.py, src/snowcli/exception.py, tests/nativeapp/test_init.py, tests/nativeapp/test_manager.py, tests/stage/test_diff.py, tests/stage/test_stage.py, tests/testing_utils/fixtures.py
This PR is to introduce a `snow app run` command which is used to create an application package and upload files from a user's local filesystem to a snowflake stage. This is only a part of the implementation of the `snow app run` command, as it is spread over three tickets tracked internally due to the complexity of its behavior. 
Tests have been added keeping in mind this partial implementation for now.  
How to review this PR:
This PR has two sets of changes, one of which has already been approved from another PR https://github.com/Snowflake-Labs/snowcli/pull/400 and I will mark those changes as such so you do not need to re-review them.
=> [NADE] Snow App Run Part 1

.github/workflows/build.yaml, pyproject.toml
* Added missing pluggy dependency
=> Fix missing pluggy dependency

.github/workflows/performance_history_analysis.yaml, performance_history_analysis.py
* Added performance history analysis workflow with manual trigger
=> [SNOW-925356] Performance history analysis

.github/workflows/performance_history_analysis.yaml
* Fixed performance analysis workflow
=> Fix performance analysis workflow

.github/workflows/performance_history_analysis.yaml
=> Fix fetch depth in performance analysis workflow

src/snowcli/cli/registry/commands.py, src/snowcli/cli/registry/manager.py, tests/test_registry.py
Fix for `-c` option not working for `snow registry token` command
=> [SNOW-927561] Fix for registry token connection issues

pyproject.toml, src/snowcli/cli/common/sql_execution.py, src/snowcli/cli/snowpark/compute_pool/commands.py, src/snowcli/cli/snowpark/services/commands.py, src/snowcli/cli/snowpark/services/manager.py, src/snowcli/output/printing.py, src/snowcli/output/types.py, tests/snowpark/test_compute_pool.py, tests/snowpark/test_services.py
Fix bugs with SPCS commands.
The PR makes sure that SPCS compute pool and services work. 
Fixes the following bugs:
* Broken unit tests
* Incorrect parameters
* Make sure that if database or schema does not exist, the human-readable message is created
* Proper printing of status command
* Support for instance family enum
* Using inline-schema when creating service instead of stages
* Add support for printing tables without rows
=> Fix Snowservices issues

src/snowcli/__about__.py
=> Bump version to 1.1.1

.github/workflows/build.yaml, .github/workflows/integration_test.yaml, .github/workflows/test.yaml
=> Run tests also on other branches than main

.github/workflows/performance_history_analysis.yaml, performance_history_analysis.py
* Added `pip install .` after every checkout to be able to analyse commits with the previous locations of the main script
* Added summary with commits sorted by the highest diff in performance test result
* Added auto checkout to the original active branch after analysis finish
Example result of analysis: https://github.com/Snowflake-Labs/snowcli/actions/runs/6350575878/job/17250489798
And the beginning of the summary:
```
Commits causing performance descending:
Diff [0.06980509300012727180728688836] after commit fd84b56cf2cfbd59454188f8dc183d6fb226b074 (2023-09-12 07:12:57-04:00) -> [NADE] Add Support for Project Definition Files + Native App Initialize Project (#369)
Diff [0.05888858999992407916579395533] after commit cfd368dbc1a63c003d563f5d208c8935835a5e91 (2023-09-19 15:50:44+02:00) …
```
=> Performance history analysis improvements

tests/test.toml, tests/test_config.py
As feature requested in #406 is already possible i just added unit tests to ensure it`s working properly
=> Tests for storing default connection in env variable

tests/test_config.py, tests_integration/testing_utils/snowpark_utils.py
=> Fixed few warning in tests

src/snowcli/cli/snowpark/services/manager.py, tests/snowpark/test_services.py, tests/testing_utils/fixtures.py
=> Fix create service command

RELEASE-NOTES.md
=> [v1.1.1] Update release notes

src/snowcli/utils.py, tests/test_utils.py
While parsing requirements file, we forgot, that specifications allow inline comments in requirements files. This led to #431 
This PR introduces slight change to way, we parse mentioned files, allowing usage of inline comments.
=> Fix for packages issue

pyproject.toml, src/snowcli/cli/snowpark/services/manager.py, tests/snowpark/test_services.py
=> Fix create service

tests/test_main.py
Adding automated tests for duplicated options - this time without adding callback
=> Avoiding options duplicates [No-callback approach]

pyproject.toml, src/snowcli/cli/snowpark/services/manager.py, src/snowcli/utils.py, tests/snowpark/test_services.py, tests/test_utils.py
=> Cherry-pick another changes to 1.1.1 RC

src/snowcli/app/dev/docs/templates/usage.rst.jinja2
* Added info about option value type in generated docs
<details>
<summary>Click here to see how it looked before the changes</summary>
</details>
<details>
<summary>Click here to see how it looks after the changes (look at green parts of option headings)</summary>
</details>
=> Info about option value type in generated docs

src/snowcli/cli/registry/commands.py
* Updated repository_name option help
=> Update repository_name option help

RELEASE-NOTES.md
=> Add 1.1.1 release notes to main version

src/snowcli/cli/common/decorators.py, src/snowcli/cli/common/experimental_behaviour.py, src/snowcli/cli/common/flags.py, src/snowcli/cli/common/snow_cli_global_context.py, tests/test_common_decorators.py, tests/test_experimental_behaviour.py
* Introduced `@with_experimental_behaviour()` decorator which adds `--experimental` flag to a command.
=> [SNOW-937242] --experimental flag

src/snowcli/cli/common/flags.py, tests/test_experimental_behaviour.py
The `--experimental` flag should be hidden
=> Make --experimental a hidden flag

src/snowcli/cli/nativeapp/commands.py, src/snowcli/cli/nativeapp/manager.py, tests/nativeapp/test_manager.py
When we detect a change in stage files but the app already exists on the user's account, issue an `alter application ... upgrade using @stage` instead of dropping and re-creating the application.
=> Upgrade apps instead of recreating them

RELEASE-NOTES.md, src/snowcli/cli/common/project_initialisation.py, src/snowcli/cli/snowpark/function/commands.py, src/snowcli/cli/snowpark/procedure/commands.py, src/snowcli/cli/streamlit/commands.py, src/snowcli/utils.py, tests/snowpark/test_function.py, tests/snowpark/test_procedure.py, tests/streamlit/test_commands.py, tests/test_project_initialisation.py, tests_integration/conftest.py, tests_integration/test_function.py, tests_integration/testing_utils/__init__.py, tests_integration/testing_utils/snowpark_utils.py
=> Generalize init commands

src/templates/default_streamlit/.gitignore
=> Added gitignore to Streamlit template

pyproject.toml, src/snowcli/__about__.py
=> Bump version to 1.2.1 and updated PyYAML to 6.0.1

RELEASE-NOTES.md
=> Updated release notes for 1.2.1

RELEASE-NOTES.md
=> Added release notes for 1.2.x versions

.github/workflows/e2e_test.yaml, .pre-commit-config.yaml, pyproject.toml, tests_e2e/__snapshots__/test_installation.ambr, tests_e2e/config/config.toml, tests_e2e/conftest.py, tests_e2e/test_installation.py, tests_integration/streamlit_test/app.py, tests_integration/streamlit_test/environment.yml, tests_integration/streamlit_test/pages/my_page.py
* Added new type of tests - E2E
* Added new directory for E2E tests
* Added new workflow for E2E tests
* Added E2E test of the process of SnowCLI installation
=> Integration tests of the process of SnowCLI installation

RELEASE-NOTES.md, src/snowcli/cli/nativeapp/manager.py, src/snowcli/cli/stage/manager.py, tests/stage/test_manager.py, tests/stage/test_stage.py
Support the use of quoted identifiers in stage names
=> Support quoted identifiers in stages

src/snowcli/cli/nativeapp/commands.py, src/snowcli/cli/nativeapp/init.py, tests/nativeapp/test_init.py
Move the default template repository URL to its final home,  pending open-source release.
=> Move default template repository URL

src/snowcli/cli/nativeapp/commands.py, src/snowcli/cli/nativeapp/init.py, src/snowcli/cli/nativeapp/manager.py, src/snowcli/cli/project/definition.py, src/snowcli/cli/project/util.py, tests/nativeapp/__snapshots__/test_commands.ambr, tests/nativeapp/__snapshots__/test_init.ambr, tests/nativeapp/test_commands.py, tests/nativeapp/test_init.py, tests/nativeapp/test_manager.py, tests/project/test_util.py
Support quoted IDs in native app commands and configuration
=> Support quoted IDs in Native Apps

.github/workflows/jira_issue.yml
* Updated "Community issues" jira number
=> Update community issues jira number

src/snowcli/cli/nativeapp/init.py, src/snowcli/cli/project/definition_manager.py, tests/project/test_definition_manager.py
Centralize the logic to look for a project root, and remove diverging the implementation.
=> Centralize logic to search for project roots

src/snowcli/cli/nativeapp/commands.py
=> Minor grammar edits

pyproject.toml
=> Remove E2E tests from default pytest

tests/conftest.py
* Added reseting of logging levels before each test case.
=> Fix logging levels reset in tests

tests_integration/test_object.py
* Fixed `snow object show schema` integration test by applying database context
=> Fixed 'snow object show schema' integration test by applying database context

pyproject.toml, tests_integration/config/connection_configs.toml, tests_integration/conftest.py, tests_integration/snowpark/docker/Dockerfile, tests_integration/snowpark/spec/spec.yml, tests_integration/snowpark/test_jobs.py, tests_integration/snowpark/test_services.py, tests_integration/testing_utils/snowpark_jobs_utils.py, tests_integration/testing_utils/snowpark_services_utils.py
Added integration tests for services and jobs
=> Added integrations test for Snowpark Containers Services

tests/test_registry.py
Executing the command function directly caused the log level to change in the remaining tests and this sometimes caused tests to fail
=> Changed registry tests to invoke runner

src/snowcli/cli/containers/jobs/commands.py
=> Hide snowpark jobs desc

tests/nativeapp/test_manager.py
The way some tests are written for native app manager are a bit hard to follow because you need to manually maintain 1:1ness of mock cursor calls and its expected outcome. Refactored the tests a bit so that they are now side by side, making it easier for the test author to keep track.
=> [NADE] Refactoring NativeAppManager Tests

.github/pull_request_template.md
=> Mention integration tests and manual tests in PR checklist

RELEASE-NOTES.md, src/snowcli/cli/containers/compute_pool/commands.py, src/snowcli/cli/containers/compute_pool/manager.py, src/snowcli/cli/containers/jobs/commands.py, src/snowcli/cli/containers/jobs/manager.py, src/snowcli/cli/containers/services/commands.py, src/snowcli/cli/containers/services/manager.py, src/snowcli/cli/object/manager.py, src/snowcli/cli/snowpark/commands.py, src/snowcli/cli/snowpark/common.py, tests/containers/test_compute_pool.py, tests/containers/test_jobs.py, tests/containers/test_services.py, tests/snowpark/test_function.py, tests/snowpark/test_procedure.py, tests_integration/test_procedure.py, tests_integration/test_procedure_coverage.py, tests_integration/testing_utils/snowpark_utils.py
Removed desc, show and drop commands from snowpark
=> Removed desc, show and drop commands from snowpark

src/snowcli/cli/snowpark/commands.py, src/snowcli/cli/snowpark/package/manager.py, src/snowcli/cli/snowpark/package/utils.py, src/snowcli/cli/snowpark_shared.py, src/snowcli/utils.py, src/snowcli/zipper.py, tests/snowpark/test_snowpark_shared.py, tests/test_utils.py, tests/test_zipper.py, tests/testing_utils/fixtures.py
- Improved building snowpark zip
- Refactored building zip, moved to separate module, greatly simplified
- Added list with ignored files
=> Improve building snowpark zip and refactoring

src/snowcli/cli/common/cli_global_context.py, src/snowcli/exception.py, tests/test_common_global_context.py
=> Added schema validation

RELEASE-NOTES.md, src/snowcli/cli/object/stage/commands.py, src/snowcli/cli/object/stage/manager.py, tests/object/stage/__snapshots__/test_stage.ambr, tests/object/stage/test_stage.py, tests_integration/test_stage.py
Replaces `stage put` and `stage get` with `stage copy` command
=> Replace stage put and get with copy command

src/snowcli/__about__.py, tests_e2e/conftest.py
=> Changed version to 2.0.0-alpha

src/snowcli/cli/object/commands.py
Before
```
➜ snow object --help    
Usage: snow object [OPTIONS] COMMAND [ARGS]...                                                                                                                                                                                         
Manages Snowflake objects like warehouses and stages                                                                                                                                                                                   
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --help  -h        Show this message and exit. …
```
=> Fix objects list not showing in object --help

src/snowcli/__about__.py, tests_e2e/conftest.py
=> Changed version to 2.0.0a2 and fixed e2e tests

src/snowcli/__about__.py
=> 1.2.2 version in about.py

src/snowcli/cli/object/commands.py, src/snowcli/cli/object/manager.py, tests/object/test_object.py
Added arguments check for object subcommands
=> Object argument checks

src/snowcli/app/api_impl/plugin/plugin_config_provider_impl.py, src/snowcli/config.py
=> Auth with private key fix

tests_integration/test_external_plugins.py, tests_integration/testing_utils/assertions/test_result_assertions.py
=> Check logs in external plugins integration tests

src/snowcli/cli/object/stage/manager.py, src/snowcli/cli/project/util.py, tests/object/stage/test_stage.py, tests/project/test_util.py, tests_integration/test_nativeapp.py
Correctly quote local file:// URLs in stage commands, if required. Currently, snow app run fails if spaces are present in the local path because of missing quotes.
=> Quote local paths in stage commands

RELEASE-NOTES.md, src/snowcli/cli/project/schemas/snowpark.py, src/snowcli/cli/snowpark/commands.py, src/snowcli/cli/snowpark/common.py, src/snowcli/cli/snowpark/manager.py, tests/snowpark/test_function.py, tests/snowpark/test_procedure.py, tests/test_data/projects/snowpark_functions/snowflake.yml, tests/test_data/projects/snowpark_procedures/snowflake.yml
Adds support for RUNTIME parameter in functions and procedures.
=> Add support for runtime in snowpark objects

src/snowcli/app/dev/docs/generator.py, src/snowcli/cli/sql/commands.py, tests/test_main.py
=> Fix docs callback

src/snowcli/cli/containers/compute_pool/commands.py, src/snowcli/cli/containers/services/commands.py
Remove instance family type validation from snowcli, push it to snowflake.
=> Remove hardcoded instance family types

src/snowcli/cli/render/commands.py, tests/test_main.py
Verify that every option has at leas one long name
=> Verify that every option has at least 1 long version

src/snowcli/cli/common/sql_execution.py, src/snowcli/cli/sql/commands.py, src/snowcli/cli/sql/manager.py, src/snowcli/output/printing.py, src/snowcli/output/types.py, tests/object/test_object.py, tests/test_main.py, tests/test_sql.py, tests/testing_utils/fixtures.py, tests_integration/conftest.py, tests_integration/test_sql.py
Improve streaming results in case of multiple queries execution.
=> Improve result streaming

CONTRIBUTING.md
* Changes in CONTRIBUTING.md: Manual installation of external plugins not required anymore to run integration tests, because now we install plugins automatically when preparing setup for test cases
=> Changes in CONTRIBUTING.md: Manual installation of external plugins not required anymore to run integration tests

src/snowcli/cli/snowpark/compute_pool/commands.py
* Cherry-pick of #604 to 1.X releases branch.
=> Cherry-pick to 1.X: #604: Remove hardcoded instance family types

RELEASE-NOTES.md
* Include release notes for v1.2.2 and v1.2.3 from release-1.X branch.
=> Include v1.2.2 and v1.2.3 in release notes

RELEASE-NOTES.md, src/snowcli/app/api_impl/plugin/plugin_config_provider_impl.py, src/snowcli/app/cli_app.py, src/snowcli/cli/connection/commands.py, src/snowcli/config.py, src/snowcli/snow_connector.py, tests/test.toml, tests/test_config.py, tests/test_connection.py, tests/test_main.py, tests/test_snow_connector.py, tests_integration/config/config_with_enabled_all_external_plugins.toml, tests_integration/config/config_with_enabled_only_one_external_plugin.toml, tests_integration/config/connection_configs.toml
* Removed CliConfigManager class
* Switched to python connector default connection
=> Switched to python connector config parser

RELEASE-NOTES.md
=> Added release notes for 1.2.4

src/snowcli/__about__.py
=> Bump alpha version to 3

src/snowcli/cli/nativeapp/manager.py, src/snowcli/cli/nativeapp/run_processor.py, src/snowcli/cli/nativeapp/teardown_processor.py, src/snowcli/cli/nativeapp/version/version_processor.py, tests/nativeapp/test_manager.py, tests/nativeapp/test_run_processor.py, tests/nativeapp/test_version_create_processor.py, tests/nativeapp/test_version_drop_processor.py, tests/nativeapp/utils.py
This PR introduces two changes:
1. Perform app package distribution mismatch check in `snow app version drop`.
2. For `snow app version create`, if a user passes in both version and patch and the version does not exist, throw an error.
=> [NADE] Distribution Warnings and Bad Parameter Exception

src/snowcli/plugins/registry/commands.py
=> Removed register token example from docstring

.github/CODEOWNERS, src/snowcli/plugins/nativeapp/commands.py, src/snowcli/plugins/nativeapp/common_flags.py, src/snowcli/plugins/nativeapp/version/commands.py
@sfc-gh-mheavin suggested some edits to be made to the command descriptions that make them more readable. This PR makes those edits. 
Also updated the CODEOWNERS file to include recent refactor.
=> [NADE] Update description across NA commands for better documentation

src/snowflake/cli/api/config.py, tests/test_config.py
Default config file will be created if not exists
=> Create default config if not exists

src/snowflake/cli/plugins/object/stage/commands.py, tests/object/stage/__snapshots__/test_stage.ambr, tests/object/stage/test_stage.py
=> Print summary for all files copied from and to stage

src/snowflake/cli/api/commands/flags.py
Change default value of "connection" flag to "default" (it's not "dev" anymore)
=> Update connections help message

src/snowflake/cli/api/config.py, src/snowflake/cli/app/snow_connector.py, tests/test_config.py
=> Overriding default connection by env variables

src/snowflake/cli/api/output/types.py, src/snowflake/cli/app/main_typer.py, src/snowflake/cli/app/printing.py, tests_integration/__snapshots__/test_sql.ambr, tests_integration/conftest.py, tests_integration/test_sql.py
=> Add json output streaming in case of MultipleResults output

pyproject.toml, src/snowcli/cli/nativeapp/init.py, src/snowcli/utils.py, tests/nativeapp/test_init.py, tests/test_loaded_modules.py, tox.ini
=> Import git repo only if it is needed in native apps

tests_integration/test_data/projects/snowpark_with_package/app/functions.py, tests_integration/test_data/projects/snowpark_with_package/requirements.txt, tests_integration/test_data/projects/snowpark_with_package/snowflake.yml, tests_integration/test_package.py, tests_integration/test_snowpark.py, tests_integration/testing_utils/snowpark_utils.py
Switch from independent packages, to ones managed by us in integration tests for `snowpark` and `package` command groups
=> Switch snowpark & package tests to our test-packages

src/snowflake/cli/__about__.py
=> Bump to rc version

pyproject.toml, src/snowflake/cli/plugins/nativeapp/version/version_processor.py, tests/test_loaded_modules.py, tox.ini
Moved git imports to functions
=> Import git when is needed

RELEASE-NOTES.md
=> Updated release notes with 1.2.5

RELEASE-NOTES.md
=> [NADE] Add NA commands to the release notes for v2.0.0

.github/workflows/old_publish.yaml
=> Fix old publish workflow

RELEASE-NOTES.md
Mentioning removed 'jobs' command in release notes
=> Mentioning removed 'jobs' command in release notes

src/snowflake/cli/plugins/nativeapp/version/version_processor.py
Remove `(... , )` from prompt.
=> Change the prompt input to string not tuple

README.md
=> Remove docs link from README.md

src/snowflake/cli/__about__.py
=> bump version to v2.0.0rc2

src/snowflake/cli/api/cli_global_context.py
=> mraba/fix-super-invocation: update super usage

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Bump version to v2.0.0rc3

tests/conftest.py, tests/test_config.py, tests/test_logs.py, tests/test_snow_connector.py, tests/test_utils.py, tests/testing_utils/fixtures.py, tests_e2e/conftest.py, tests_integration/conftest.py
---
* Add (ugly) fixture overriding default `connections.toml` location, so existence of connections.toml will not cause unittests and integration tests to fail
* Add unit tests checking that connectins.toml override connections config from config.toml
=> Snow 1017573 connections toml tests

src/snowflake/cli/__about__.py
=> Bump version to 2.0.0

test_external_plugins/override_build_in_command/pyproject.toml, test_external_plugins/override_build_in_command/src/snowflakecli/test_plugins/override_build_in_command/commands.py, test_external_plugins/override_build_in_command/src/snowflakecli/test_plugins/override_build_in_command/plugin_spec.py, tests/test_data/configs/override_plugin_config.toml, tests/test_external_plugins.py
Check if error log appears when plugin tries to override command
=> Add test for error log where plugin override command

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Bump version to 2.0.1

src/snowflake/cli/plugins/spcs/image_repository/manager.py, tests/spcs/test_image_repository.py
=> using show_specific_object in image_repository.manager.get_repository_url

RELEASE-NOTES.md, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/plugins/object/common.py, src/snowflake/cli/plugins/spcs/common.py, src/snowflake/cli/plugins/spcs/compute_pool/commands.py, src/snowflake/cli/plugins/spcs/compute_pool/manager.py, src/snowflake/cli/plugins/spcs/services/commands.py, tests/spcs/test_compute_pool.py, tests/testing_utils/fixtures.py, tests_integration/spcs/test_cp.py, tests_integration/testing_utils/compute_pool_utils.py
Added commands for `spcs compute-pool set --<property1> <value1> ...` and `spcs compute-pool unset <name> --<property1>  ...`. These commands allow you to set values or reset to default values for properties of an existing compute pool, equivalent to `ALTER COMPUTE POOL <name> SET/UNSET ...`. Added unit and integration tests for these commands. 
**Usage:**
**Help Message:**
**Error If No Properties Provided:**
=> SNOW-1011773: `spcs compute-pool set/unset <properties...>` commands

tests/__snapshots__/test_help_messages.ambr, tests/test_help_messages.py
Add unit test looking up and invoking all commands with `--help`, checking output against snapshots
=> Add tests checking all help messages

.github/workflows/jira_issue.yml
=> Updated epic for community issues

RELEASE-NOTES.md, src/snowflake/cli/api/cli_global_context.py, src/snowflake/cli/api/commands/decorators.py, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/app/snow_connector.py, tests/__snapshots__/test_help_messages.ambr, tests/api/commands/__snapshots__/test_snow_typer.ambr, tests/test_common_decorators.py, tests/test_common_global_context.py, tests/test_connection.py, tests/test_sql.py
=> Added support for MFA

src/snowflake/cli/api/commands/project_initialisation.py, src/snowflake/cli/api/commands/snow_typer.py, src/snowflake/cli/plugins/connection/commands.py, src/snowflake/cli/plugins/nativeapp/commands.py, src/snowflake/cli/plugins/nativeapp/version/commands.py, src/snowflake/cli/plugins/object/__init__.py, src/snowflake/cli/plugins/object/commands.py, src/snowflake/cli/plugins/object/stage/commands.py, src/snowflake/cli/plugins/snowpark/commands.py, src/snowflake/cli/plugins/snowpark/package/commands.py, src/snowflake/cli/plugins/spcs/__init__.py, src/snowflake/cli/plugins/spcs/compute_pool/commands.py, src/snowflake/cli/plugins/spcs/compute_pool/manager.py, src/snowflake/cli/plugins/spcs/image_registry/commands.py, src/snowflake/cli/plugins/spcs/image_repository/commands.py, src/snowflake/cli/plugins/spcs/jobs/commands.py, src/snowflake/cli/plugins/spcs/services/commands.py, src/snowflake/cli/plugins/streamlit/commands.py, tests/test_connection.py, tests/test_project_initialisation.py
Use `SnowTyper` for all other commands.
=> Use SnowTyper for all commands

RELEASE-NOTES.md, src/snowflake/cli/plugins/spcs/services/commands.py, src/snowflake/cli/plugins/spcs/services/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/spcs/test_services.py, tests_integration/spcs/spec/spec_upgrade.yml, tests_integration/spcs/test_services.py, tests_integration/testing_utils/snowpark_services_utils.py
Added 'spcs service upgrade' command which allows you to update the spec of a running service.
**Usage**:
=> SNOW-1011778: Adding 'spcs service upgrade' command

RELEASE-NOTES.md, src/snowflake/cli/plugins/spcs/services/commands.py, src/snowflake/cli/plugins/spcs/services/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/spcs/test_services.py, tests_integration/spcs/spec/spec.yml, tests_integration/spcs/spec/spec_upgrade.yml, tests_integration/spcs/test_services.py, tests_integration/testing_utils/snowpark_services_utils.py
Added new command for `service list-endpoints` to show public endpoints of a running SPCS service. Added unit and integration tests.
**Usage**:
=> SNOW-1011781: Adding `service list-endpoints` command.

src/snowflake/cli/templates/default_snowpark/snowflake.yml
Removes external access from snowpark example so it will work out of the box.
=> Remove external access from example

.github/workflows/publish.yaml
Adding "release" environment to "publish" workflow to make publishing more secure.
=> Use "release" github environment to publish SnowCLI

src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/plugins/connection/commands.py, tests/api/commands/test_flags.py
Using `--password`  flag should warn user about exposing the value.
=> Add warning if password is passed via --password flag

src/snowflake/cli/app/dev/docs/generator.py
=> Changed docs file extension to txt

RELEASE-NOTES.md, src/snowflake/cli/api/config.py, src/snowflake/cli/app/loggers.py, tests/api/test_secure_path.py, tests/conftest.py, tests/test_logs.py, tests/testing_utils/fixtures.py, tests_integration/conftest.py
=> Logging into file by default

src/snowflake/cli/templates/default_snowpark/app/functions.py, src/snowflake/cli/templates/default_snowpark/app/procedures.py, tests_e2e/conftest.py, tests_e2e/test_snowpark_examples.py
Add main block to template functions and procedures so users can execute those locally
=> Extend snowpark template to support local debugging

src/snowflake/cli/api/commands/flags.py, tests/test_connection.py
Show prompt when mfa flag is provided without value
=> Added prompt for mfa if provided flag without value

tests_integration/test_snowpark.py
Fix for integration tests after Snowflake release 8.7
=> Fix for integration tests

src/snowflake/cli/__about__.py
=> Bump version to 2.1.0

RELEASE-NOTES.md, src/snowflake/cli/plugins/connection/commands.py, tests/app/test_telemetry.py, tests/test_connection.py
Users reported that `snow connection tests` is unintuitive because it does not test if database or schema defined in connection exists.
=> Add session context validation in connection test

README.md
=> Repository name update in readme

RELEASE-NOTES.md, src/snowflake/cli/api/config.py, src/snowflake/cli/plugins/connection/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/test_connection.py
Adds `snow connection set-default` command
=> Add connection set-default command

src/snowflake/cli/plugins/streamlit/commands.py, tests/__snapshots__/test_help_messages.ambr
=> Adjust streamlit deploy help

src/snowflake/cli/plugins/connection/commands.py, src/snowflake/cli/plugins/nativeapp/commands.py, src/snowflake/cli/plugins/nativeapp/version/commands.py, src/snowflake/cli/plugins/snowpark/commands.py, src/snowflake/cli/plugins/snowpark/package/commands.py, src/snowflake/cli/plugins/snowpark/snowpark_shared.py, src/snowflake/cli/plugins/spcs/compute_pool/commands.py, src/snowflake/cli/plugins/spcs/jobs/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/test_cli.py, tests_e2e/__snapshots__/test_installation.ambr
Unifying tense in help messages
=> Updated help messages

src/snowflake/cli/app/dev/docs/templates/usage.rst.jinja2
=> Docs generation change

src/snowflake/cli/plugins/git/commands.py, src/snowflake/cli/plugins/git/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/git/test_git_commands.py, tests_e2e/__snapshots__/test_installation.ambr
Add `git list-branches` and `git list-tags` commands
=> Snow 1105625 git list branches tags

src/snowflake/cli/templates/default_snowpark/app/procedures.py, src/snowflake/cli/templates/default_snowpark/snowflake.yml
Remove any external access from snowpark template
=> Remove external access from snowpark template

tests_integration/test_data/projects/snowpark_external_access/app/app.py, tests_integration/test_data/projects/snowpark_external_access/requirements.txt
=> Removed requests dependency from tests

src/snowflake/cli/plugins/snowpark/package/utils.py, tests/snowpark/__snapshots__/test_package.ambr, tests_integration/__snapshots__/test_package.ambr, tests_integration/test_package.py
=> Fixed messages for package lookup

src/snowflake/cli/plugins/nativeapp/manager.py, src/snowflake/cli/plugins/snowpark/commands.py, src/snowflake/cli/plugins/snowpark/common.py, src/snowflake/cli/plugins/snowpark/package/commands.py, src/snowflake/cli/plugins/snowpark/package/utils.py, src/snowflake/cli/plugins/snowpark/package_utils.py, src/snowflake/cli/plugins/streamlit/streamlit_utils.py, tests/__snapshots__/test_help_messages.ambr, tests/snowpark/__snapshots__/test_package.ambr
=> Capitalization fix

src/snowflake/cli/plugins/object/stage/commands.py, tests/__snapshots__/test_help_messages.ambr
* Cherrypicks from main branch
=> Target directory fix for stage copy docs (#859)

pyproject.toml
This reverts commit 80467b3d2b50c7996cfd068ed510476e64a714e0.
...
=> Revert "Bump tomlkit from 0.12.3 to 0.12.4 (#848)"

tests/__snapshots__/test_help_messages.ambr, tests/test_help_messages.py
Add `snow --help` to commands checked by test_help_messages.py
=> Add snow --help to test_help_messages

.pre-commit-config.yaml, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/api/commands/snow_typer.py, src/snowflake/cli/api/secure_path.py, src/snowflake/cli/app/cli_app.py, src/snowflake/cli/app/loggers.py, src/snowflake/cli/app/main_typer.py, src/snowflake/cli/plugins/connection/commands.py, src/snowflake/cli/plugins/snowpark/commands.py, src/snowflake/cli/plugins/spcs/image_repository/commands.py, tests/__snapshots__/test_snow_connector.ambr, tests/api/commands/test_snow_typer.py, tests/snowpark/test_function.py, tests/snowpark/test_procedure.py
1. Remove print/echo usage in favor of more controlled ways
2. Remove snowcli usages from user facing placese
3. Make sure --silent is eager so order of flags make no difference
4. Add pygrep checks to avoid regression
=> Avoid plain print, make sure silent is eager flag

src/snowflake/cli/api/config.py
* Config permissions check disabled on Windows before 2.1.0 release.
=> Disable config permissions check on Windows

src/snowflake/cli/api/secure_path.py
=> SecurePath: make file type assertions public

.pre-commit-config.yaml, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/api/commands/snow_typer.py, src/snowflake/cli/api/config.py, src/snowflake/cli/api/secure_path.py, src/snowflake/cli/app/cli_app.py, src/snowflake/cli/app/loggers.py, src/snowflake/cli/app/main_typer.py, src/snowflake/cli/plugins/connection/commands.py, src/snowflake/cli/plugins/snowpark/commands.py, src/snowflake/cli/plugins/spcs/image_repository/commands.py, tests/__snapshots__/test_snow_connector.ambr, tests/api/commands/test_snow_typer.py, tests/snowpark/test_function.py, tests/snowpark/test_procedure.py
=> Cherrypicks 2024-03-06 - 1

RELEASE-NOTES.md
Add release notes for `snow git` commands
=> Update release notes.

src/snowflake/cli/api/cli_global_context.py, src/snowflake/cli/api/commands/snow_typer.py, src/snowflake/cli/api/config.py, src/snowflake/cli/api/feature_flags.py, src/snowflake/cli/plugins/streamlit/manager.py, tests/api/commands/__snapshots__/test_snow_typer.ambr, tests/api/commands/test_snow_typer.py, tests/api/test_feature_flags.py, tests/plugin/__snapshots__/test_override_by_external_plugins.ambr
=> Add config based feature flags

src/snowflake/cli/plugins/snowpark/package/commands.py, src/snowflake/cli/plugins/snowpark/package/manager.py
In this way we do cleanup even if there are any errors.
=> Refactor cleanup_after_install as a decorator

src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/plugins/git/commands.py, src/snowflake/cli/plugins/git/manager.py, src/snowflake/cli/plugins/object/commands.py, src/snowflake/cli/plugins/object/stage/commands.py, src/snowflake/cli/plugins/object/stage/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/git/test_git_commands.py, tests/object/stage/test_stage.py, tests_integration/test_git.py
Add `--like` flag to `list-branches` and `list-tags` in `snow git` commands and `--pattern` flag to `list-files`
=> Snow 1223142 add like to list commands

tests_integration/conftest.py
Replace `__all__ = [...]` to `noqa: F401` to disable ruff from removing imported fixtures, which were not used explicitly in the code.
=> small refactor of conftests.py file

.snyk/req-auto-generated.txt, pyproject.toml, src/snowflake/cli/plugins/spcs/services/manager.py, tests/spcs/test_services.py, tests_integration/conftest.py
=> Remove StrictYaml from project

.github/workflows/lint.yaml, .snyk/dependency-sync.py
=> Generate requirements.txt pre-commit fix

snyk/dependency-sync.py, snyk/requirements.txt
=> Removed comment from requirements

pyproject.toml, snyk/requirements.txt
Because we use `pip` in package commands.
=> Add pip as requirement for snowflake cli

RELEASE-NOTES.md, pyproject.toml, src/snowflake/cli/plugins/snowpark/venv.py
=> Cherry-pick changes to 2.1.2

RELEASE-NOTES.md
=> Add v2.1.1 and v2.1.2 release notes

README.md
=> Repository migration readme update

RELEASE-NOTES.md, src/snowflake/cli/plugins/snowpark/package/commands.py, src/snowflake/cli/plugins/snowpark/package_utils.py, src/snowflake/cli/plugins/snowpark/venv.py, tests/snowpark/test_package.py, tests_integration/test_package.py
The only problem we had with supporting all `pip` sources in `snowpark package create`, was package name resolution - the resulting `.zip` archive could have invalid name.
This PR uses `pip wheel` command to help with package name resolution.
=> Snow 1051580 support package create from all sources

.pre-commit-config.yaml, RELEASE-NOTES.md, pyproject.toml, src/snowflake/cli/plugins/snowpark/models.py
Add codespell check to pre-commit. Followup after #931
=> Add codespell check to pre-commit

tests_integration/test_snowpark.py
Test test_build_with_anaconda_dependencies failing because of updated package in Anaconda
=> Skip integration test test_build_with_anaconda_dependencies

tests_integration/test_data/projects/snowpark_version_check/.gitignore, tests_integration/test_data/projects/snowpark_version_check/app/app.py, tests_integration/test_data/projects/snowpark_version_check/requirements.txt, tests_integration/test_data/projects/snowpark_version_check/snowflake.yml, tests_integration/test_snowpark.py
* Fix test using existing library
* Add test checking version of package used by snowpark functions
=> improve snowpark integration tests

RELEASE-NOTES.md, src/snowflake/cli/api/feature_flags.py, tests/__snapshots__/test_help_messages.ambr, tests_e2e/__snapshots__/test_installation.ambr
Set snowgit feature flag to `True` by default
=> Enable snowgit commands

RELEASE-NOTES.md
=> Improve deprecation wording for snowpark package in RELEASE-NOTES

CONTRIBUTING.md, pyproject.toml, tests/snowpark/test_models.py
Renamed `snowcli` to `snowflake-cli` and updated github links
=> Updated snowcli name and links to github

LEGAL.md
=> Remove LEGAL.md because project is in PuPr

src/snowflake/cli/__about__.py
=> Update version to 2.2.0rc0

RELEASE-NOTES.md
Fixed `snow object stage execute` release notes
=> Fixed snow object stage execute in release notes

src/snowflake/cli/__about__.py
* Using `dev0` version in about.py on the main branch
=> Using dev0 version in about.py on the main branch

RELEASE-NOTES.md
=> Move snow connection test fix release note to 2.2.0

RELEASE-NOTES.md, src/snowflake/cli/api/sql_execution.py, tests_integration/test_connection.py
* Cherrypicks to v2.2.0 from the main branch
=> Cherrypicks to v2.2.0 from the main branch

src/snowflake/cli/plugins/git/commands.py, src/snowflake/cli/plugins/object/common.py, src/snowflake/cli/plugins/snowpark/package/anaconda_packages.py, tests/__snapshots__/test_help_messages.ambr
`snowflake` -> `Snowflake` in docs and help messags
=> Capitilized 'Snowflake'

src/snowflake/cli/plugins/git/commands.py, src/snowflake/cli/plugins/object/common.py, src/snowflake/cli/plugins/snowpark/package/anaconda_packages.py, tests/__snapshots__/test_help_messages.ambr
* Cherry-pick from the main branch to v2.2.0
=> Capitilized 'Snowflake' (#1008)

.pre-commit-config.yaml, conftest.py, pyproject.toml, src/snowflake/cli/app/constants.py, src/snowflake/cli/app/snow_connector.py, src/snowflake/cli/app/telemetry.py, tests/app/test_telemetry.py, tests/test_connection.py, tests/test_main.py, tests/test_snow_connector.py
Added 3 extra params when creating connection:
- application_name
- _internal_application_name
- _internal_application_version
This will allow us to detect snowflake-cli connections outside telemetry.
=> Snow 1346407 connection version info

src/snowflake/cli/plugins/nativeapp/feature_flags.py, tests/nativeapp/test_feature_flags.py
* [N/A] I've added or updated integration tests to verify correctness of my new code.
Adding a feature flag to control the upcoming setup script generation logic.
=> Add feature flag to control setup script generation in the CLI

src/snowflake/cli/plugins/nativeapp/codegen/sandbox.py, tests/nativeapp/codegen/test_sandbox.py
* [N/A] I've added or updated integration tests to verify correctness of my new code.
Added a utility method to execute a python script in a virtual environment. This a building block for an upcoming native applications feature.
I tested the logic on both Windows and Mac using a manually written driver and a combination of different python versions installed globally, conda environment and venv environments. Also added unit tests to cover 100% of the logic.
=> Add the ability to execute a python script in virtual environments

.github/workflows/build.yaml
The `needs` does not work across different workflows. This is probably a leftover from early CI split.
=> Remove needs clause from build.yml

RELEASE-NOTES.md, src/snowflake/cli/plugins/snowpark/models.py, src/snowflake/cli/plugins/snowpark/package_utils.py, tests_integration/test_package.py, tests_integration/test_snowpark.py
Optimize dependency search to lower number of anaconda dependencies for snowpark projects and size of .zip artifacts of snowpark packages.
=> Snow 1316060 optimize package dependency search

RELEASE-NOTES.md, src/snowflake/cli/plugins/git/manager.py, src/snowflake/cli/plugins/snowpark/package/manager.py, src/snowflake/cli/plugins/stage/manager.py, tests/git/__snapshots__/test_git_commands.ambr, tests/git/test_git_commands.py, tests/stage/__snapshots__/test_stage.ambr, tests/stage/test_stage.py, tests_integration/__snapshots__/test_git.ambr, tests_integration/__snapshots__/test_stage.ambr, tests_integration/test_git.py, tests_integration/test_stage.py
Added missing support for fully qualified names in stage and git execute commands
=> Added support for FQN in stage and git execute

src/snowflake/cli/api/project/schemas/snowpark/callable.py, tests/project/__snapshots__/test_config.ambr
Fixes default value for secrets fields. This was mostly causing warning in tests. There should be no impact on users code.
=> Fix invalid default value for secrets filed

.github/CODEOWNERS
`CODEOWNERS` file has a bug, it should be all of team NADE for the `tests/nativeapp` instead of my name + nade.
=> Update CODEOWNERS for Native Apps

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Bump version to 2.3.0rc0

src/snowflake/cli/__about__.py
=> Bump version to 2.4.0dev0

RELEASE-NOTES.md, src/snowflake/cli/plugins/sql/commands.py, tests/__snapshots__/test_help_messages.ambr
To align with `snowsql` naming
=> Rename --data to --variables in snow sql

.github/CODEOWNERS
* [N/A] I've confirmed that instructions included in README.md are still correct after my changes in the codebase.
* [N/A] I've added or updated automated unit tests to verify correctness of my new code.
* [N/A] I've added or updated integration tests to verify correctness of my new code.
* [N/A] I've confirmed that my changes are working by executing CLI's commands manually.
Adjust ownership of test artifacts to reflect the new structure for native apps. Also, ensure that snapshots have shared ownership to facilitate the PR process for NADE.
=> Adjust ownership of test artifacts

RELEASE-NOTES.md, src/snowflake/cli/api/constants.py, tests/__snapshots__/test_help_messages.ambr, tests_integration/test_object.py
Add external access integrations to snow object commands
=> Add external access integrations to snow object commands

tests_integration/nativeapp/test_teardown.py
* I've confirmed that my changes are working by executing CLI's commands manually.
Following up on #1029 and enabling the skipped integration tests after the CI user was granted with the required permissions.
=> Enable teardown cascade integration tests

CONTRIBUTING.md
* I've confirmed that my changes are working by executing CLI's commands manually.
Documenting the integration tests user requirements for the tests added in #1064
=> update contrib doc with intg test user grant db requirement

src/snowflake/cli/api/feature_flags.py, src/snowflake/cli/plugins/cortex/commands.py, src/snowflake/cli/plugins/cortex/plugin_spec.py
Added cortex group to allow simultanous work on some commands
=> Add cortex group

src/snowflake/cli/__about__.py
=> Bump version to 2.3.0

.github/workflows/jira_close.yml, .github/workflows/jira_comment.yml
By enclosing the variable in quotation marks, you tell the shell to treat the entire string as a single argument, even if it contains spaces or other special characters. This can prevent errors and unexpected behavior in your shell commands and scripts.
=> Update environment variables usage in JIRA actions

.github/CODEOWNERS
* N/A I've confirmed that my changes are working by executing CLI's commands manually.
Tweaking code owners again to avoid requiring SnowflakeCLI reviews for each release notes update. Also cleaning up / generalizing other rules.
=> Tweaking code owners to avoid blocking PRs on release note updates

pyproject.toml
Use pytest-xdist for integration tests.
=> mraba/pytest-xdist: parallelize integration tests

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/plugins/nativeapp/constants.py, src/snowflake/cli/plugins/nativeapp/run_processor.py, tests/nativeapp/test_run_processor.py, tests_integration/nativeapp/test_version.py, tests_integration/test_utils.py
=> Cherry picks for 2.3.1

RELEASE-NOTES.md
Adjusting release-notes after 2.3.0 and 2.3.1 releases
=> Fix release-notes after 2.3.X releases

.github/CODEOWNERS
Thanks to this change different teams won't be required for review. This should improve work peace.
=> Remove owners for RELEASE-NOTES.md

src/snowflake/cli/plugins/notebook/commands.py, src/snowflake/cli/plugins/notebook/exceptions.py, src/snowflake/cli/plugins/notebook/manager.py, src/snowflake/cli/plugins/notebook/types.py, tests/__snapshots__/test_help_messages.ambr, tests/notebook/test_notebook_commands.py, tests/notebook/test_notebook_manager.py, tests_integration/notebook/test_notebooks.py, tests_integration/snowflake_connector.py, tests_integration/test_data/notebook/my_notebook.ipynb
Added support for notebook creation from stage `snow notebook create`
=> Snow 1304163 notebook create command

src/snowflake/cli/plugins/connection/util.py
* [x[ I've described my changes in the release notes.
...
=> Use log.warning instead of exception to hide traceback

RELEASE-NOTES.md, src/snowflake/cli/api/cli_global_context.py, src/snowflake/cli/plugins/connection/commands.py, tests/__snapshots__/test_help_messages.ambr
=> Support temporary connection in test command

RELEASE-NOTES.md, src/snowflake/cli/app/printing.py, tests/output/test_printing.py
=> Add newline at the end of JSON output

RELEASE-NOTES.md, src/snowflake/cli/api/commands/flags.py, tests/__snapshots__/test_help_messages.ambr
=> Add variables support in stage/git execute

.pre-commit-config.yaml, RELEASE-NOTES.md, src/snowflake/cli/api/commands/snow_typer.py, src/snowflake/cli/app/cli_app.py, src/snowflake/cli/app/main_typer.py, src/snowflake/cli/plugins/sql/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/__snapshots__/test_sql.ambr, tests/test_help_messages.py, tests/test_sql.py
MainCliSnowTyper callback was enriched witch ctx handling and discovery whether not invoked with subcommand.
SnowTyper has no_args_is_help set to True.
=> Snow 998984 show help when no args

RELEASE-NOTES.md, src/snowflake/cli/api/commands/snow_typer.py, src/snowflake/cli/app/main_typer.py, tests/__snapshots__/test_help_messages.ambr, tests_e2e/__snapshots__/test_installation.ambr
Enable built-in feature of completion
=> Enable autocompletion

.github/CODEOWNERS
* N/A I've confirmed that my changes are working by executing CLI's commands manually.
`tests/test_data` should have shared ownership to make sure teams aren't unnecessarily blocked on each other.
=> Share ownership of tests/test_data

tests/snowpark/test_package.py
Add sql query mock to packages unit tests
=> Fix unit tests failing without internet connection

.github/workflows/test.yaml, tests/nativeapp/codegen/test_sandbox.py, tests/test_sql.py, tests_integration/test_snowpark_external_access.py
Enabling unit tests on Python 3.12 + fixes to allign to new methods
=> Enabling tests on 3.12

tests_integration/test_package.py, tests_integration/test_snowpark.py
* Add check for logs around pip wheel call 
* Add test checking invalid requirement parsing
=> Security validation: add tests

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Bump version to 2.5.0dev0

src/snowflake/cli/__about__.py, src/snowflake/cli/plugins/nativeapp/teardown_processor.py
=> Cherry-picks for 2.4.0rc1

src/snowflake/cli/plugins/stage/manager.py
=> Removed additional @ from log

tests_integration/test_git.py
Remove `snow git fetch` output check, as the repository changes often enough for the test to become flaky
=> fix test_git::test_fetch integration test

tests/nativeapp/codegen/snowpark/__snapshots__/test_python_processor.ambr
* N/A I've confirmed that my changes are working by executing CLI's commands manually.
I just noticed that some of the existing snapshots are incorrect and cause some errors when running locally (somehow the run isn't considered a failure, but I'm not sure why...). In any case fixing them is necessary.
=> Fix incorrect snapshots

RELEASE-NOTES.md, src/snowflake/cli/api/feature_flags.py, src/snowflake/cli/plugins/notebook/commands.py, tests/__snapshots__/test_help_messages.ambr, tests_e2e/__snapshots__/test_installation.ambr
[Notebooks](https://docs.snowflake.com/en/user-guide/ui-snowsight/notebooks) are now in public preview, we can remove the feature flag.
=> Make notebook publicly available

src/snowflake/cli/plugins/stage/manager.py, tests/stage/__snapshots__/test_stage.ambr, tests/stage/test_stage.py, tests/streamlit/test_commands.py
Stop overriding snow:// with @
=> Stop overriding snow:// with @

RELEASE-NOTES.md, src/snowflake/cli/plugins/nativeapp/commands.py, src/snowflake/cli/plugins/nativeapp/run_processor.py, src/snowflake/cli/plugins/nativeapp/version/commands.py, src/snowflake/cli/plugins/nativeapp/version/version_processor.py, tests/__snapshots__/test_help_messages.ambr, tests_integration/nativeapp/test_version.py
Changes `snow app version create --patch` to require an integer for the patch number since that's what the backend expects (passing in a string results in a SQL compilation error).
=> [SNOW1456079] Change patch to Optional[int]

src/snowflake/cli/templates/default_snowpark/snowflake.yml, src/snowflake/cli/templates/default_streamlit/snowflake.yml
=> Bump definition_version in templates

src/snowflake/cli/api/secure_path.py, tests/api/test_secure_path.py, tests/test_data/test_data.py, tests/test_utils.py
- SecurePath tests: add fixture simulating overridden system `umask`
- SecurePath: fix parents' too wide permissions when creating directory recursively (overridden `umask` scenario)
- unit tests: use fake names of pip packages
=> Snow 1176584 Security validation fixes

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/app/constants.py, src/snowflake/cli/app/snow_connector.py, tests/nativeapp/__snapshots__/test_commands.ambr, tests/nativeapp/codegen/snowpark/__snapshots__/test_python_processor.ambr, tests/test_connection.py, tests/test_main.py, tests/test_snow_connector.py
=> Release v2.4.1

RELEASE-NOTES.md, src/snowflake/cli/plugins/spcs/image_registry/manager.py, tests/spcs/test_registry.py
Improved error message in `snow spcs image-registry login` when docker is not installed.
=> Added better error when docker is not installed

.github/CODEOWNERS, tests_e2e/test_data/nativeapp.txt, tests_e2e/test_nativeapp.py
NADE is about to introduce an E2E test for our commands, and we would like to add its owners accordingly.
=> Extend E2E Tests Ownership to NADE

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
Bumping version as part of release process
=> Bump version to 2.6.0

tests/test_config.py
Added test for config parent directory permission after create
=> Added test for config parent directory permission after create

src/snowflake/cli/plugins/nativeapp/manager.py
* N/A I've confirmed that my changes are working by executing CLI's commands manually.
Fixing a missed variable renaming
=> Fix missed outdated var name

src/snowflake/cli/__about__.py, src/snowflake/cli/plugins/nativeapp/codegen/snowpark/callback_source.py.jinja
=> Cherrypicks v2.5.0 1

tests/api/test_secure_path.py, tests/test_data/test_data.py, tests/test_utils.py
- Change "fake" test packages name
- Improve `os.umask` usage in tests
=> SNOW-1176550 security validation - change dummy test packages name 

src/snowflake/cli/plugins/nativeapp/artifacts.py, tests/nativeapp/__snapshots__/test_artifacts.ambr, tests/nativeapp/test_artifacts.py
OS Directory traversal is in random order, and hence any side effects of the traversal will also be random. This randomness can cause flakiness in tests that check code paths that cause exceptions. This means we cannot deterministically test for file paths when the code errors early, because each run of the test may have traversed the directory (up until the exception) in a different order than before. 
This PR removes the flakiness of the tests, and introduces a deterministic order for the traversal.
=> [NADE] Introduce order for iterating over files in bundle, fix tests

src/snowflake/cli/__about__.py, src/snowflake/cli/api/utils/definition_rendering.py, src/snowflake/cli/api/utils/models.py, src/snowflake/cli/plugins/nativeapp/artifacts.py, tests/api/utils/test_definition_rendering.py, tests/nativeapp/__snapshots__/test_artifacts.ambr, tests/nativeapp/test_artifacts.py
=> Cherrypicks to v2.5.0rc2

RELEASE-NOTES.md, src/snowflake/cli/app/printing.py, tests/output/test_printing.py
=> Fix markup escaping errors in snow sql command

tests/test_config.py
Check if warning is issued when user uses custom config file without proper permissions.
=> Test warning when using custom config without access

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/app/printing.py, tests/output/test_printing.py
=> Cherrypicks v2.5.0 3

RELEASE-NOTES.md, src/snowflake/cli/plugins/stage/commands.py, src/snowflake/cli/plugins/stage/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/stage/test_stage.py
Adds --auto-compress flag to `snow stage copy` command.
=> Add --auto-compress flag to stage copy command

README.md, pyproject.toml
Added useful links to README and updated project status in package classifiers.
=> Update project status and links

test_external_plugins/multilingual_hello_command_group/src/snowflakecli/test_plugins/multilingual_hello/commands.py, test_external_plugins/multilingual_hello_command_group/src/snowflakecli/test_plugins/multilingual_hello/plugin_spec.py, test_external_plugins/snowpark_hello_single_command/src/snowflakecli/test_plugins/snowpark_hello/commands.py, test_external_plugins/snowpark_hello_single_command/src/snowflakecli/test_plugins/snowpark_hello/plugin_spec.py
Refactor test plugin to use SnowAppFactory
=> Refactor test plugin to use SnowAppFactory

src/snowflake/cli/app/dev/docs/generator.py
Generated usage docs should be rst files.
=> Generated usage docs should be .rst files

src/snowflake/cli/__about__.py
=> Remove rc suffix

tests_integration/__snapshots__/test_temporary_connection.ambr, tests_integration/test_temporary_connection.py
Error response changed so updated test to pass
=> Updated temporary connection test

pyproject.toml
Removing `--snapshot-warn-unused` so unused snapshots will cause error. Main reason is situation like this https://github.com/snowflakedb/snowflake-cli/pull/1244#discussion_r1649116961
=> Unused snapshots should cause errors

src/snowflake/cli/plugins/nativeapp/feature_flags.py, tests/nativeapp/test_feature_flags.py
Introduce a feature flag for the upcoming python setup work from NADE.
=> Add feature flag to control Python setup execution in native app logic

src/snowflake/cli/app/dev/docs/templates/usage.rst.jinja2
Generating docs with --no- boolean flags
=> Generating docs with --no- boolean flags

RELEASE-NOTES.md, src/snowflake/cli/plugins/nativeapp/errno.py, src/snowflake/cli/plugins/nativeapp/manager.py, src/snowflake/cli/plugins/nativeapp/teardown_processor.py, tests/nativeapp/__snapshots__/test_teardown_processor.ambr, tests/nativeapp/test_teardown_processor.py, tests_integration/nativeapp/test_teardown.py
When a package is dropped, subsequent `snow app teardown` calls fail with “Application is no longer available for use. Please contact the application provider for more details.” since the CLI is still trying to execute `show objects owned by application`. If this query fails with this error, we should ask the user if they want to cascade drop the application without being able to see the objects.
=> [SNOW-1486485] Fix tearing down an app whose package has already been dropped

RELEASE-NOTES.md, src/snowflake/cli/app/__init__.py, src/snowflake/cli/app/cli_app.py, src/snowflake/cli/app/commands_registration/command_plugins_loader.py, src/snowflake/cli/app/loggers.py, tests/test_command_registration.py, tests_e2e/test_error_handling.py, tests_integration/plugin/test_broken_plugin.py, tests_integration/test_external_plugins.py
* Added info log message about loaded external plugins
* Added test
=> Added info log about loaded external plugins

.github/workflows/build.yaml
=> build.yaml fix

RELEASE-NOTES.md
=> Release notes update

RELEASE-NOTES.md, src/snowflake/cli/plugins/git/manager.py, src/snowflake/cli/plugins/stage/manager.py, tests/stage/__snapshots__/test_stage.ambr, tests/stage/test_stage.py, tests_integration/__snapshots__/test_stage.ambr, tests_integration/test_stage.py
Added support for user stages in stage execute command
=> Added support for user stages in stage execute command

.github/workflows/jira_issue.yml
=> Update jira_issue workflow

RELEASE-NOTES.md, src/snowflake/cli/plugins/git/commands.py, src/snowflake/cli/plugins/git/manager.py, src/snowflake/cli/plugins/stage/manager.py, tests/git/test_git_commands.py, tests/stage/test_stage.py, tests_integration/test_stage.py
Added support for user stages in stage and git copy command
=> Added support for user stages in stage and git copy command

src/snowflake/cli/plugins/object/commands.py, tests/__snapshots__/test_help_messages.ambr
Change example object types for `snow object` commands to ones currently supported by `snow object create`
=> Adjust examples for object type argument

RELEASE-NOTES.md, src/snowflake/cli/api/commands/flags.py
=> Add autocompletion for connection names to --connection flag

tests/test_performance.py
Snowpark is a new dependency that needs to be loaded top level.
=> Bump execution threshold for perf tests

RELEASE-NOTES.md
Added fix with logs to release notes
=> Added fix with logs to release notes

.github/workflows/ok_to_test.yml, .github/workflows/test_e2e.yaml, .github/workflows/test_integration.yaml
=> Added ok-to-test workflow

src/snowflake/cli/plugins/init/commands.py, tests_integration/test_init.py
* Add `snow init` integration tests
* Add readable error message in case chosen URL does not exist
=> Snow 1515844 init integration tests; incorrect URL error handling

tests_integration/test_git.py
Temporarily skip failing test due to server side issue
=> Temporarily skip failing test due to server side issue

src/snowflake/cli/app/loggers.py, tests/test_logs.py
Fixed logs init with disabled save_logs in config and debug flag passed to command
=> Fixed logs init with disabled save_logs and debug flag

src/snowflake/cli/plugins/nativeapp/commands.py, tests_integration/nativeapp/__snapshots__/test_deploy.ambr, tests_integration/nativeapp/test_deploy.py, tests_integration/nativeapp/test_validate.py, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/app/README.md, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/app/manifest.yml, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/app/setup_script.sql, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/snowflake.yml, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/app/README.md, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/app/manifest.yml, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/app/setup_script.sql, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/snowflake.yml
Added the `@nativeapp_definition_v2_to_v1` decorator to `snow app validate` and `snow app deploy` commands.
Parameterized the fixture of the existing tests to run on both v1 and v2 projects.
=> Support project definition v2 in "app validate" and "app deploy"

src/snowflake/cli/plugins/nativeapp/commands.py, src/snowflake/cli/plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py, tests/nativeapp/test_v2_to_v1.py, tests_integration/nativeapp/__snapshots__/test_deploy.ambr, tests_integration/nativeapp/test_bundle.py, tests_integration/nativeapp/test_deploy.py, tests_integration/nativeapp/test_teardown.py, tests_integration/nativeapp/test_validate.py, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/app/README.md, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/app/manifest.yml, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/app/setup_script.sql, tests_integration/test_data/projects/napp_deploy_prefix_matches_v1/snowflake.yml, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/app/README.md, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/app/manifest.yml, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/app/setup_script.sql, tests_integration/test_data/projects/napp_deploy_prefix_matches_v2/snowflake.yml
* Added the `@nativeapp_definition_v2_to_v1` decorator to `snow app` commands: `bundle`, `validate` and `deploy`
* Updated the `_pdf_v2_to_v1()` logic to support `artifacts`, `bundle_root`, `generated_root`, `deploy_root`
Parameterized the fixture of the existing tests to run on both v1 and v2 projects.
Created the `override_snowflake_yml_artifacts()` utility for the tests to modify `snowflake.yml` for both v1 and v2.
=> Support project definition v2 in "snow app" commands: bundle, validate, deploy

src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/plugins/git/commands.py, src/snowflake/cli/plugins/init/commands.py, src/snowflake/cli/plugins/sql/commands.py, src/snowflake/cli/plugins/stage/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/__snapshots__/test_sql.ambr
Refactor `VariablesOption` flag to be able to provide proper help messages without creating `typer.Option` definition from anew
=> Refactor VariableOption flag

RELEASE-NOTES.md, src/snowflake/cli/plugins/init/commands.py, tests/__snapshots__/test_help_messages.ambr, tests_e2e/__snapshots__/test_installation.ambr
=> Show snow init command

RELEASE-NOTES.md, src/snowflake/cli/plugins/nativeapp/run_processor.py, tests/nativeapp/test_post_deploy.py
Update post_install default database to point to application database.
=> Update post_install default database to point to application database

RELEASE-NOTES.md, src/snowflake/cli/plugins/git/manager.py, src/snowflake/cli/plugins/stage/manager.py, tests/git/test_git_commands.py
Snowflake doesn't support copy to user stages.
=> Removed supporting git copy to for user stages

src/snowflake/cli/plugins/nativeapp/commands.py, src/snowflake/cli/plugins/nativeapp/manager.py, tests/nativeapp/test_manager.py, tests_integration/nativeapp/test_events.py
Reverts snowflakedb/snowflake-cli#1352 due to integration test flakiness
=> Revert "SNOW-1544013 Fetch events for app"

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Bump version to 2.7.0rc0 and updated release notes

src/snowflake/cli/api/commands/project_initialisation.py, tests/__snapshots__/test_help_messages.ambr
Add missing spaces in deprecated init help messages
=> Add spaces in deprecated init help messages

src/snowflake/cli/api/config.py, src/snowflake/cli/plugins/connection/commands.py, tests/__snapshots__/test_help_messages.ambr
=> Added --token-file-path for connection add command

RELEASE-NOTES.md
=> Moved fix for large files uploaded to AWS S3 to 2.7.0 version

.github/workflows/test_integration.yaml, pyproject.toml
Makes integration tests a bit better by avoiding fast-fail (avoids canceling test runs that would pass when the other flakes) and increases parallelism to 6 & changes load-balancing strategy to combat recent increases in runtime.
Before:
After:
=> Integration test CI improvements

.pre-commit-config.yaml
=> Fix for failing code quality checks

RELEASE-NOTES.md, src/snowflake/cli/plugins/connection/commands.py, src/snowflake/cli/plugins/connection/util.py, tests/__snapshots__/test_connection.ambr, tests/test_connection.py
Fix for #1391 - added prompt callback that strips values provided by the user, to prevent saving trailing spaces.
=> Fix for whitespaces problem in connection add

.github/workflows/cleanup.yaml, .github/workflows/test_cli_action.yaml, .github/workflows/test_e2e.yaml, .github/workflows/test_fork.yaml, .github/workflows/test_integration.yaml, .github/workflows/test_trusted.yaml, scripts/cleanup.py, src/snowflake/cli/app/snow_connector.py, tests_integration/snowflake_connector.py, tests_integration/test_temporary_connection.py
=> Changed integration tests user auth to private key

scripts/cleanup.py
=> Cleanup script fix

scripts/cleanup.py
=> Fix cleanup task

tests_integration/nativeapp/test_project_templating.py
This test was missing a call to `snow app teardown` so it was leaving behind an app package.
=> Add missing teardown to integration test

RELEASE-NOTES.md, src/snowflake/cli/_plugins/nativeapp/commands.py, tests/__snapshots__/test_help_messages.ambr
Makes the `snow app events` command public
=> SNOW-1565544 Unhide snow app events command

RELEASE-NOTES.md, src/snowflake/cli/_plugins/cortex/commands.py, src/snowflake/cli/_plugins/nativeapp/commands.py, src/snowflake/cli/_plugins/object/commands.py, src/snowflake/cli/_plugins/sql/commands.py, src/snowflake/cli/_plugins/sql/manager.py, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/api/commands/overridable_parameter.py, src/snowflake/cli/api/commands/overrideable_parameter.py, src/snowflake/cli/api/exceptions.py, tests/__snapshots__/test_help_messages.ambr, tests/__snapshots__/test_sql.ambr, tests/api/commands/__snapshots__/test_flags.ambr, tests/api/commands/test_flags.py, tests/cortex/test_cortex_commands.py, tests/object/test_object.py, tests/spcs/__snapshots__/test_image_repository.ambr, tests/spcs/test_image_repository.py, tests/test_sql.py, tests/testing_utils/result_assertions.py, tests_integration/nativeapp/test_deploy.py, tests_integration/nativeapp/test_events.py, tests_integration/testing_utils/assertions/test_result_assertions.py
- Add OverridableParameter as parent class of OverridableArgument and OverridableOption, it now raise IncompatibleOptionsError instead of ClickException
- Update cortext commands to use OverridableArgument
- Update sql command to raise IncompatibleOptionsError instead of ClickException
[Ticket](https://snowflakecomputing.atlassian.net/browse/SNOW-1482252) 
Error example:
=> Common error for mutually exclusive flags

src/snowflake/cli/_plugins/snowpark/commands.py, src/snowflake/cli/_plugins/snowpark/common.py, src/snowflake/cli/api/project/schemas/entities/snowpark_entity.py, tests/project/test_project_definition_v2.py, tests/snowpark/__snapshots__/test_function.ambr, tests/snowpark/__snapshots__/test_procedure.ambr, tests/snowpark/test_function.py, tests/snowpark/test_procedure.py
Align Snowpark models to use indentifier instead of name.
=> Align snowpark entities to use identifier

RELEASE-NOTES.md, src/snowflake/cli/_plugins/streamlit/commands.py, src/snowflake/cli/_plugins/streamlit/manager.py, src/snowflake/cli/api/project/schemas/entities/common.py, src/snowflake/cli/api/project/schemas/entities/snowpark_entity.py, src/snowflake/cli/api/project/schemas/entities/streamlit_entity_model.py, src/snowflake/cli/api/sql_execution.py, tests/streamlit/test_streamlit_manager.py, tests_integration/test_data/projects/streamlit_v2/environment.yml, tests_integration/test_data/projects/streamlit_v2/pages/my_page.py, tests_integration/test_data/projects/streamlit_v2/streamlit_app.py, tests_integration/test_data/projects/streamlit_v2/utils/utils.py, tests_integration/test_data/projects/streamlit_v2_external_access/snowflake.yml, tests_integration/test_data/projects/streamlit_v2_external_access/streamlit_app.py, tests_integration/test_streamlit.py
Added support for external access in streamlit. Closes #1433
=> Add external access support in streamlit

src/snowflake/cli/_plugins/init/commands.py, src/snowflake/cli/api/rendering/project_templates.py, tests/test_data/projects/project_templating_jinja_blocks/blocks.txt, tests/test_data/projects/project_templating_jinja_blocks/template.yml, tests/test_init.py
* Add support for jinja2 blocks (`if`, `for` etc)
* Add `snowflake_cli_version` variable to template variables
=> Snow 1633381 add jinja blocks to snow init

RELEASE-NOTES.md, src/snowflake/cli/_plugins/snowpark/commands.py, tests_integration/test_snowpark.py
Add missing "return" statement in snowpark aliases
=> Fix snowpark aliases

RELEASE-NOTES.md
Update release notes with v2.8.0
=> v2.8.0 release notes

src/snowflake/cli/_plugins/snowpark/commands.py, tests_integration/test_snowpark.py, tests_integration/testing_utils/snowpark_utils.py
Small followup after #1465 to build dependencies.zip if there are any dependencies
=> Build snowpark deps only if any exist

src/snowflake/cli/_plugins/init/commands.py, tests/test_init.py, tests_integration/test_init.py
Fixes misleading error message when `snow init` is called with no arguments: https://github.com/snowflakedb/snowflake-cli/issues/1486
=> More actionable error message for snow init

src/snowflake/cli/_plugins/snowpark/commands.py, src/snowflake/cli/_plugins/snowpark/snowpark_project_paths.py, src/snowflake/cli/api/project/schemas/entities/common.py, src/snowflake/cli/api/project/schemas/entities/snowpark_entity.py, tests/project/test_project_definition_v2.py, tests_integration/test_snowpark.py
Remove `project_name` in Snowpark by making artifacts a list of path mappings
=> Make Snowpark to support artifacts mappings

src/snowflake/cli/_plugins/workspace/commands.py
=> Workspace migrate doc typo fix

.github/CODEOWNERS
* I've added or updated integration tests to verify correctness of my new code.
* I've confirmed that my changes are working by executing CLI's commands manually on MacOS.
Marking workspaces paths as CLI/NADE shared ownership.
=> Update CODEOWNERS with workspaces paths

src/snowflake/cli/_plugins/workspace/action_context.py, src/snowflake/cli/_plugins/workspace/manager.py, src/snowflake/cli/api/entities/application_package_entity.py, tests/nativeapp/patch_utils.py, tests/test_data/projects/workspaces_simple/snowflake.yml, tests/workspace/test_application_package_entity.py, tests_integration/nativeapp/test_post_deploy.py
* Implementing `post_deploy` section in definition v2 for `ApplicationPackageEntity`.
* Added a default warehouse value to `ActionContext` that is read from the connection (matching the functionality in `snow app`).
=> Workspaces post deploy hooks

src/snowflake/cli/_plugins/stage/commands.py, src/snowflake/cli/api/commands/flags.py, tests/api/test_fqn.py, tests/stage/test_stage.py
In stage commands stages can start with @
=> Fixed stage commands with stages starting with @

tests/git/__snapshots__/test_git_commands.ambr, tests/git/test_git_commands.py, tests/stage/__snapshots__/test_stage.ambr, tests/stage/test_stage.py
Added tests for stage/git execute.
Added tests for new git repo list files (no repo name in path)
=> Stage execute fix

RELEASE-NOTES.md, src/snowflake/cli/_plugins/git/commands.py, tests/git/test_git_commands.py
Fixes naming of secrets and api integration in case of providing repo name as fully qualified name.
=> Fix git setup with FQN repo names

RELEASE-NOTES.md, src/snowflake/cli/_plugins/streamlit/manager.py, tests/streamlit/test_commands.py, tests/streamlit/test_streamlit_manager.py, tests_integration/test_streamlit.py
Adds check for existing streamlit object of the same name before deploying any file or creating streamlit.
=> Check for existing streamlit before deploying anything

src/snowflake/cli/api/project/definition_conversion.py, tests/workspace/test_manager.py
Raises specific errors if manifest can't be found.
If artifacts can't be bundled:
If manifest.yml can't be found:
=> SNOW-1643030 Emit specific errors if manifest location can't be found

tests_integration/spcs/testing_utils/compute_pool_utils.py
The response changed, let's update this test
=> Fix compute pool integration test assertion

.github/workflows/test_integration_spcs.yaml, pyproject.toml
Due to flakiness we are separating SPCS tests from main integration testsing pipeline.
=> Separate SPCS int tests

.github/workflows/test.yaml, .github/workflows/test_e2e.yaml, .github/workflows/test_integration.yaml
This reverts commit b586b8eddd84dd55de48eb6d64a25c3707d1eb7a.
...
=> Revert "Run tests only when code changes (#1560)"

scripts/run_tests_qa.sh
=> Added script for tests on qa

RELEASE-NOTES.md
=> Remove V3 from RELEASE-NOTES.md

src/snowflake/cli/__about__.py
=> Bump version to 3.0.0rc2

pyproject.toml, snyk/requirements.txt
Bump snowflake.core to latest version
=> Bump snowflake.core to 0.12.1

src/snowflake/cli/api/sql_execution.py, tests/nativeapp/test_manager.py, tests/nativeapp/test_package_scripts.py, tests/nativeapp/test_run_processor.py
Followup to #1584 for `use_warehouse`
=> Remove DictCursor from use_warehouse

tests_integration/nativeapp/test_post_deploy.py
Add integration test to check for backslashes on Windows for post_deploy scripts.
=> Add integration test to check for backslashes on Windows

RELEASE-NOTES.md, src/snowflake/cli/_plugins/snowpark/snowpark_entity_model.py, src/snowflake/cli/_plugins/streamlit/manager.py, src/snowflake/cli/_plugins/streamlit/streamlit_entity_model.py, src/snowflake/cli/api/project/schemas/entities/common.py, tests/streamlit/__snapshots__/test_commands.ambr, tests/streamlit/test_streamlit_manager.py, tests_integration/test_streamlit.py
Add `imports` support in Streamlit. Extracts `imports` base model for consistency between snowpark and streamlit entities.
=> Add imports support in Streamlit

tests/nativeapp/test_teardown_processor.py
While working on my previous PR, I noticed that some of the existing tests had no-op statements instead of assertions. This PR fixes the assertions as well as their respective conditions, since unsurprisingly some of them had diverged.
=> Fix incorrect test assertions

src/snowflake/cli/_app/secret.py, src/snowflake/cli/_app/snow_connector.py, tests/test_connection.py, tests/test_snow_connector.py, tests_integration/snowflake_connector.py
Added class that hides variable values when appear in traceback.
=> Added class to hide variables in tracebacks

tests_integration/test_cortex.py
=> Disabled cortex tests on qa

RELEASE-NOTES.md
=> Release notes cleanup

RELEASE-NOTES.md
=> Fix release notes

src/snowflake/cli/_plugins/nativeapp/entities/application.py, src/snowflake/cli/_plugins/nativeapp/manager.py, tests/nativeapp/test_manager.py, tests/nativeapp/utils.py
Moves these functions to the app entity since we're making `NativeAppManager` just a wrapper.
=> Move get_events and stream_events to app entity

scripts/cleanup.py
Changed private_key_file to private_key_raw env variable in cleanup script.
=> Cleanup private key env fix

scripts/cleanup.py
Deleting objects with special signs in name throw syntax error.
=> Quoted name in cleanup script

scripts/packaging/build_darwin_package.sh
Fix executable path for signing
=> SNOW-1694005: fix executable path

src/snowflake/cli/_app/dev/docs/templates/overview.rst.jinja2, src/snowflake/cli/_app/dev/docs/templates/usage.rst.jinja2, tests/__snapshots__/test_docs_generation_output.ambr
=> Removed double grave accent in docs

RELEASE-NOTES.md, src/snowflake/cli/_plugins/helpers/commands.py, src/snowflake/cli/api/project/definition_conversion.py, src/snowflake/cli/api/project/definition_manager.py, tests/helpers/test_v1_to_v2.py, tests/project/test_definition_manager.py, tests/test_data/projects/migration_local_yml/snowflake.local.yml, tests/test_data/projects/migration_local_yml/snowflake.yml
Cherry pick for two PRs to be included in 3.0.0 release:
* #1637 
* #1636
=> Cherrypicks 3.0.0 rc4

src/snowflake/cli/__about__.py
=> Version bump

src/snowflake/cli/_app/cli_app.py, tests/__snapshots__/test_help_messages.ambr, tests_e2e/__snapshots__/test_installation.ambr
Added version info to tool name displayed on help screen
=> mraba/help-version-info: add version to tool description on help screen

.github/workflows/test_e2e.yaml, .github/workflows/test_integration.yaml, .github/workflows/test_integration_spcs.yaml
=> Run int and e2e test after push to main

src/snowflake/cli/_plugins/nativeapp/commands.py
Converts `snow app diff` to operate natively on v2 models
=> SNOW-1706990 Convert `snow app diff` to v2-native

.compat/build_snowflake-cli-labs.sh, scripts/packaging/docker-compose.yaml, scripts/packaging/python/test_cli_labs_whl.sh, scripts/packaging/python/test_cli_whl.sh
Automate manual testing for WHL files
=> SNOW-1639544 automate manual WHL test 3.0.1

tests/test_config.py
Add unit test checking SnowCLI end on error if connections.toml file permissions are too wide on Windows
=> add Windows tests for connections.toml permissions

.compat/build_snowflake-cli-labs.sh, scripts/packaging/docker-compose.yaml, scripts/packaging/python/test_cli_labs_whl.sh, scripts/packaging/python/test_cli_whl.sh
Automate manual testing for WHL files
=> SNOW-1639544 automate manual WHL checks 2.8.2

.github/CODEOWNERS
This file is part of a NADE initiative to reduce test flakiness, we should be codeowners on it.
=> Add NADE ownership to tests_common/deflake.py

src/snowflake/cli/_plugins/nativeapp/commands.py, src/snowflake/cli/_plugins/nativeapp/entities/application.py, src/snowflake/cli/_plugins/nativeapp/manager.py, tests/nativeapp/utils.py
Converts `snow app open` to operate on v2 entities natively.
=> SNOW-1706990 Convert `snow app open` to v2-native

src/snowflake/cli/_plugins/nativeapp/commands.py, src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, src/snowflake/cli/_plugins/nativeapp/manager.py
Converts `snow app validate` to operate on v2 entities natively.
=> SNOW-1706990 Convert `snow app validate` to v2-native

RELEASE-NOTES.md
=> mraba/release-notes-3.1.0: update release notes

RELEASE-NOTES.md, src/snowflake/cli/_plugins/connection/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/test_connection.py
Add `snow connection generate-jwt` command similar to `snowsql --generate-jwt`
=> Add connection generate-jwt command

tests/nativeapp/test_post_deploy_for_package.py, tests/test_data/projects/napp_post_deploy_missing_file_v2/snowflake.yml, tests/test_data/projects/napp_post_deploy_v2/scripts/app_post_deploy1.sql, tests/test_data/projects/napp_post_deploy_v2/scripts/app_post_deploy2.sql, tests/test_data/projects/napp_post_deploy_v2/scripts/package_post_deploy1.sql, tests/test_data/projects/napp_post_deploy_v2/scripts/package_post_deploy2.sql, tests/test_data/projects/napp_post_deploy_v2/snowflake.yml, tests_integration/nativeapp/test_large_upload.py
Convert package post-deploy tests and one skipped integration tests to remove use of `NativeAppManager`.
=> Update more tests to get rid of NativeAppManager

tests_integration/nativeapp/test_post_deploy.py
`test_nativeapp_post_deploy` has extra parametrizations that don't need to run for every type of project, so let's leave the full definition version parametrization to a simple test and have dedicated tests for the other logic.
Reduces integration suite runtime to ~13 minutes.
=> Split special cases of test_nativeapp_post_deploy into separate v2-only

RELEASE-NOTES.md, src/snowflake/cli/_plugins/stage/commands.py, src/snowflake/cli/api/commands/flags.py, tests/__snapshots__/test_help_messages.ambr, tests_integration/test_stage.py
=> Fix stage list-files for directory paths

RELEASE-NOTES.md, scripts/main.py, src/snowflake/cli/__about__.py
=> Update release-notes for 3.1.0

src/snowflake/cli/_plugins/connection/commands.py, tests/__snapshots__/test_help_messages.ambr
=> mraba/generate-jwt-help-updated: update help message

RELEASE-NOTES.md, src/snowflake/cli/_app/cli_app.py, tests/test_main.py
Add information about `SNOWFLAKE_HOME` to `snow --info` callback to improve troubleshooting.
=> Add SNOWFLAKE_HOME information to --info

src/snowflake/cli/_plugins/connection/commands.py, src/snowflake/cli/api/connections.py, tests/__snapshots__/test_help_messages.ambr, tests/test.toml, tests/test_config.py, tests/test_connection.py
=> Make JWT command uses config connection details

RELEASE-NOTES.md, src/snowflake/cli/_plugins/nativeapp/commands.py, tests_integration/nativeapp/test_diff.py
=> Cherry-picks for 3.1.0-rc2

src/snowflake/cli/__about__.py
=> Bump rc version

src/snowflake/cli/_plugins/nativeapp/entities/application.py, tests/nativeapp/test_run_processor.py
`ApplicationEntity.deploy` was added to be able to run an app from `NativeAppManager`. Now that everything is using `action_deploy`, we can inline the body of `deploy` into `action_deploy`. This also allows us to convert `create_or_upgrade_app` to an instance method since it's only called from `deploy` (and one test file).
The end result is that `create_or_upgrade_app` has had its list of parameters much reduced since it now has access to `self._entity_model`.
=> SNOW-1758715 Inline ApplicationEntity.deploy into action_deploy, make create_or_upgrade_app an instance method

src/snowflake/cli/_plugins/nativeapp/entities/application.py, src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, tests/nativeapp/test_teardown.py
Inlines `drop` into `action_drop` for both Native App entities
=> SNOW-1758715 Inline drop for both entities

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, tests/nativeapp/test_version_create.py
Inlines the contents of `ApplicationPackageEntity.version_create` into `action_version_create`
=> SNOW-1758715 Inline ApplicationPackageEntity.version_create

src/snowflake/cli/_plugins/nativeapp/entities/application.py, src/snowflake/cli/api/exceptions.py, tests/nativeapp/test_manager.py
- Bug where value is NONE except of being empty, need to check for that case as well
- Formatting for some error messages spacing fixed, since the original error message can contain line breaks then it breaks dedent
=> add event table check for NONE case and fix error message formatting

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, src/snowflake/cli/_plugins/nativeapp/manager.py, src/snowflake/cli/api/project/definition_conversion.py, tests/nativeapp/test_manager.py, tests/nativeapp/test_version_create.py, tests_integration/nativeapp/test_feature_metrics.py
=> Add package scripts warning back (#1764)

tests_integration/test_git.py
* Removed skipping of a test temporary skipped in #1776
=> Unskip test added in #1776

src/snowflake/cli/__about__.py
=> Remove rc suffix from 3.1.0

src/snowflake/cli/_plugins/nativeapp/entities/application.py, src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, tests/nativeapp/test_manager.py
Converts `ApplicationPackageEntity.use_package_warehouse`, `ApplicationEntity.use_application_warehouse`, and `ApplicationEntity.get_snowsight_url` to instance methods.
=> SNOW-1758715 Convert use_x_warehouse and get_snowsight_url to instance method

src/snowflake/cli/_plugins/nativeapp/entities/application.py, tests/nativeapp/test_manager.py, tests/nativeapp/utils.py
Inline `get_existing_app_info_static` into `get_existing_app_info`
=> SNOW-1758715 Inline get_existing_app_info_static into get_existing_app_info

src/snowflake/cli/_plugins/nativeapp/entities/application.py, tests/nativeapp/test_manager.py
Converts ApplicationEntitiy event-related classmethods into instance methods
=> SNOW-1758715 Convert get_events and stream_events to instance methods

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, tests/nativeapp/test_manager.py, tests/nativeapp/test_version_drop.py
Inlines `version_drop` into `action_version_drop` and converts a few more classmethods that were only used from `version_drop` to instance methods
=> SNOW-1758715 Inline ApplicationPackageEntity.version_drop into action_version_drop

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, tests/nativeapp/test_version_create.py, tests/nativeapp/test_version_drop.py
Converts `bundle()` into a private instance method
=> SNOW-1758715 Convert ApplicationPackageEntity.bundle to instance method

src/snowflake/cli/_plugins/nativeapp/v2_conversions/compat.py
These functions were used in the now-removed v2-to-v1 conversion
=> Remove unused compat code

.github/workflows/jira_issue.yml
=> Update JIRA tracking epick

RELEASE-NOTES.md, src/snowflake/cli/_plugins/object/commands.py, src/snowflake/cli/_plugins/object/manager.py, src/snowflake/cli/api/rest_api.py, tests/__snapshots__/test_help_messages.ambr, tests/object/__snapshots__/test_object.ambr, tests/object/test_object.py, tests_integration/test_object.py
Fixes #1789 
Added `--replace` and `--if-not-exists` to `snow object create`
=> Support for if-not-exists and --replace with snow object

.github/workflows/test_cli_action.yaml
Use `main` branch instead of hardcoded tag for github action testing.
=> Update test_cli_action.yaml to use main branch

src/snowflake/cli/_plugins/connection/util.py, tests/streamlit/test_commands.py, tests/test_utils.py, tests/testing_utils/files_and_dirs.py
Add utils for event sharing PR.
This is to simplify the merging of https://github.com/snowflakedb/snowflake-cli/pull/1823/files, by splitting the files by ownership.
=> Add utils for event sharing PR

src/snowflake/cli/_plugins/connection/commands.py, tests/__snapshots__/test_help_messages.ambr, tests_e2e/__snapshots__/test_installation.ambr
Unifying "connection" flags in `snow connection add` and any other connection flags.
=> Unify connection add flags names with common connection options

RELEASE-NOTES.md, src/snowflake/cli/_plugins/connection/commands.py, tests/test_connection.py
=> Fix generate-jwt to support keys with no passphrase

.github/CODEOWNERS
Also sorts lines in this section
=> Add src/snowflake/cli/api/project/definition_conversion.py to shared ownership

RELEASE-NOTES.md, src/snowflake/cli/_plugins/connection/commands.py, tests/__snapshots__/test_connection.ambr, tests/__snapshots__/test_help_messages.ambr, tests/test_connection.py
=> Add --no-interactive option to connection add

src/snowflake/cli/_plugins/nativeapp/sf_facade_constants.py, src/snowflake/cli/_plugins/nativeapp/sf_facade_exceptions.py, src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py, src/snowflake/cli/api/project/util.py, tests/nativeapp/test_sf_sql_facade.py
- Adds `_use_object_optional` to unify `_use_role_optional`, `_use_database_optional`, and `_use_warehouse_optional`
- Adds `_use_schema_optional`
- Adds `handle_unclassified_error` handling to `get_account_event_table`
- Adds `InsufficientPrivilegesError` to be used in future PRs
=> Extract SQL facade use methods to common method, add use_schema

RELEASE-NOTES.md
=> SNOW-1772200 Add template conversion to release notes

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, tests/project/test_project_definition_v2.py, tests/workspace/test_ws_dump.py
`stage` field in application package was missing validation for `{schema_name}.{stage_name}` format. 
fixes SNOW-1801659
=> Add field validation for stage

RELEASE-NOTES.md
=> SNOW-1803158: Release Notes for SPCS SnowCLI Log Streaming

RELEASE-NOTES.md
=> Fix release notes for upcoming 3.2.0 release

RELEASE-NOTES.md
Updating release notes before RC0
=> 3.2.0 release notes

src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr
Starting 3.3.0.dev0 on the main branch after 3.2.0 RC cut-off.
=> Starting 3.3.0.dev0 on the main branch

RELEASE-NOTES.md, src/snowflake/cli/api/config.py, src/snowflake/cli/api/secure_utils.py
Remove grants instead of denying permissions on Windows
Adding tests for this specific situation is overcomplicated - we would need access to permissions config on Windows image. I assumed that `test_config.py` tests passing on Windows machine are enough
=> SNOW-1791894 Remove grants instead of denying permissions on Windows

src/snowflake/cli/_app/dev/docs/templates/usage.rst.jinja2
=> Remove empty defaults from docs

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/_app/dev/docs/templates/usage.rst.jinja2, src/snowflake/cli/api/config.py, src/snowflake/cli/api/secure_utils.py, tests_e2e/__snapshots__/test_installation.ambr
* Cherry-picks from the main branch to v3.2.0 RC1:
* https://github.com/snowflakedb/snowflake-cli/pull/1871
* https://github.com/snowflakedb/snowflake-cli/pull/1872
* Updated release notes:
* Added #1871 to fixes introduced in v3.2.0.
=> v3.2.0 RC1 cherrypicks

tests/helpers/__snapshots__/test_v1_to_v2.ambr
The feature branch has a broken test, so I need to fix it before I can apply significant refactors to the feature branch.
Verified that this fixes `hatch run test` locally.
=> Fix broken v1 to v2 test on the feature branch

.github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, .github/workflows/test_e2e.yaml, .github/workflows/test_integration.yaml, .github/workflows/test_integration_spcs.yaml
Added build and tests workflows to run for features/ branches
=> Added build and tests workflows to run for features/ branches

RELEASE-NOTES.md, src/snowflake/cli/_plugins/spcs/services/commands.py, tests/__snapshots__/test_help_messages.ambr
* Change wording of help messages of new flags
* Remove one-letter abbreviations of new flags
=> Adjust spcs service logs help messages

tests_integration/test_cortex.py
Changed word to translate in cortex test.
=> Cortex translate test fix

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/_plugins/spcs/services/commands.py, src/snowflake/cli/api/config.py, tests/__snapshots__/test_help_messages.ambr, tests/test_config.py, tests/testing_utils/fixtures.py, tests_e2e/__snapshots__/test_installation.ambr, tests_integration/test_cortex.py
* Cherrypicks from the main branch to 3.2.0 RC2:
* https://github.com/snowflakedb/snowflake-cli/pull/1875
* https://github.com/snowflakedb/snowflake-cli/pull/1878
* https://github.com/snowflakedb/snowflake-cli/pull/1882
* Version changed to `3.2.0rc2`
=> v3.2.0 RC2 cherrypicks

.github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, .github/workflows/test_e2e.yaml, .github/workflows/test_integration.yaml, .github/workflows/test_integration_spcs.yaml
=> Changed workflow trigger for pull requests to **

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/_plugins/connection/commands.py, tests_e2e/__snapshots__/test_installation.ambr
* Version changed to RC3
* Cherrypicks from the main branch:
* https://github.com/snowflakedb/snowflake-cli/pull/1886
=> V3.2.0rc3 cherrypicks

src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr
=> 3.2.0 final version

RELEASE-NOTES.md, pyproject.toml, scripts/packaging/Dockerfile
Downgraded `python` version used for building binary packages from `3.11` to `3.10`.
This version of python installed using `pyenv` works well with older intel cpus.
⚠️ This PR requires `jenkins_utils` cleanup before https://github.com/snowflakedb/jenkins_utils/pull/15017
Proof of work:
https://ci-dev-122.int.snowflakecomputing.com/job/ReleaseSnowflakeCLI/96/console
=> Snow 1790301 linux build fix

pyproject.toml, snyk/requirements.txt
=> Bump snowpark core

tests_integration/nativeapp/test_teardown.py, tests_integration/test_object.py
=> Added missing pytest integration marks

tests/test_connection.py
=> Fixed test has_calls on Python 3.12

RELEASE-NOTES.md, pyproject.toml, snyk/requirements.txt, src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr, tests_e2e/conftest.py
=> V.3.2.2 cherrypicks

src/snowflake/cli/api/rest_api.py, tests_integration/test_object.py
=> Temporarily disable schema existence check for object create (#1949)

src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr
=> Bump version v3.3.0

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr
Sort release notes after 3.3.0 release and bump dev version
=> update release notes for 3.3.0 release

tests/test_docs_generation_output.py
=> fix docs generation tests

RELEASE-NOTES.md
Link auth policy release notes to docs
=> Link auth policy release notes to docs

scripts/packaging/build_darwin_package.sh
I cleaned up dead code for installer validation 
Proof of work https://ci-dev-122.int.snowflakecomputing.com/view/SnowflakeCLI/job/ReleaseSnowflakeCLI/107/
=> mraba/binary-build-cleanup: restore validate_installtion method use

RELEASE-NOTES.md, src/snowflake/cli/_plugins/spcs/image_repository/commands.py, src/snowflake/cli/_plugins/spcs/image_repository/image_repository_entity.py, src/snowflake/cli/_plugins/spcs/image_repository/image_repository_entity_model.py, src/snowflake/cli/_plugins/spcs/image_repository/manager.py, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/api/project/definition_helper.py, src/snowflake/cli/api/project/schemas/entities/entities.py, tests/__snapshots__/test_help_messages.ambr, tests/spcs/__snapshots__/test_image_repository.ambr, tests/spcs/test_image_repository.py, tests/test_data/projects/spcs_image_repository/snowflake.yml, tests/test_data/projects/spcs_multiple_image_repositories/snowflake.yml, tests_integration/spcs/test_image_repository.py, tests_integration/spcs/testing_utils/image_repository_utils.py, tests_integration/test_data/projects/spcs_image_repository/snowflake.yml
Added `snow spcs image-repository deploy` command.
=> Image repository model in snowflake yml

RELEASE-NOTES.md, src/snowflake/cli/_plugins/spcs/services/commands.py, src/snowflake/cli/_plugins/spcs/services/manager.py, src/snowflake/cli/_plugins/spcs/services/service_entity.py, src/snowflake/cli/_plugins/spcs/services/service_entity_model.py, src/snowflake/cli/_plugins/spcs/services/service_project_paths.py, src/snowflake/cli/api/project/schemas/entities/entities.py, tests/__snapshots__/test_help_messages.ambr, tests/spcs/__snapshots__/test_services.ambr, tests/spcs/test_services.py, tests/test_data/projects/spcs_multiple_services/snowflake.yml, tests/test_data/projects/spcs_multiple_services/spec.yml, tests/test_data/projects/spcs_service/snowflake.yml, tests/test_data/projects/spcs_service/spec.yml, tests_integration/spcs/test_services.py, tests_integration/spcs/testing_utils/spcs_services_utils.py, tests_integration/test_data/projects/spcs_service/snowflake.yml, tests_integration/test_data/projects/spcs_service/spec.yml
Added `snow spcs service deploy` command.
=> Added snow spcs service deploy command

tests_integration/nativeapp/conftest.py, tests_integration/nativeapp/native_apps_utils.py, tests_integration/nativeapp/test_init_run.py, tests_integration/nativeapp/test_publish.py, tests_integration/nativeapp/test_release_channels.py, tests_integration/nativeapp/test_release_directives.py
Added integ tests for:
- release channels commands
- release directives commands
- snow app publish command
- snow app run --from-release-directive --channel=x commands
=> Integ tests for release channels, directives, publish command, and run from release channel

src/snowflake/cli/_plugins/cortex/commands.py, src/snowflake/cli/api/cli_global_context.py, src/snowflake/cli/api/entities/common.py, tests/test_docs_generation_output.py
Adding `snow_api_root` object  in CLI context and entity base class, to create a common entry point for using SnowAPIs
=> Added snow_api_root object

RELEASE-NOTES.md, src/snowflake/cli/_plugins/notebook/notebook_entity.py, src/snowflake/cli/_plugins/notebook/notebook_entity_model.py, tests/notebook/__snapshots__/test_notebook_commands.ambr, tests/notebook/test_notebook_commands.py, tests/test_data/projects/notebook_containerized_v2/notebook.ipynb, tests/test_data/projects/notebook_containerized_v2/snowflake.yml, tests_integration/test_data/projects/notebook_containerized_v2/notebook.ipynb, tests_integration/test_data/projects/notebook_containerized_v2/snowflake.yml, tests_integration/test_notebooks.py
Add support for containerized notebooks to notebook entity
=> Add support for containerized notebooks

pyproject.toml, snyk/requirements.txt
=> Bump python connector to 3.13.2

RELEASE-NOTES.md, scripts/packaging/build_binaries.sh, scripts/packaging/build_darwin_package.sh, scripts/packaging/win/build_snowflake_cli.bat
Keyring and shellingham dependencies weren't included in binaries.
=> Added missing keyring and shellingham dependencies in binaries

src/snowflake/cli/_plugins/nativeapp/commands.py, src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, src/snowflake/cli/_plugins/workspace/commands.py, tests/__snapshots__/test_help_messages.ambr
=> Fix typo in help messages

src/snowflake/cli/_plugins/nativeapp/commands.py, src/snowflake/cli/_plugins/nativeapp/release_channel/commands.py, src/snowflake/cli/_plugins/nativeapp/release_directive/commands.py, src/snowflake/cli/_plugins/nativeapp/v2_conversions/compat.py, src/snowflake/cli/api/commands/flags.py, tests/__snapshots__/test_docs_generation_output.ambr, tests/__snapshots__/test_help_messages.ambr, tests/__snapshots__/test_sql.ambr, tests/api/commands/__snapshots__/test_snow_typer.ambr
Adjust messages according to Editorial feedback
=> Adjust messages according to Editorial feedback

src/snowflake/cli/_plugins/snowpark/commands.py, src/snowflake/cli/_plugins/snowpark/common.py, src/snowflake/cli/_plugins/snowpark/snowpark_entity.py, src/snowflake/cli/_plugins/snowpark/snowpark_project_paths.py, tests/snowpark/test_project_paths.py
=> Renamed Artefact

src/snowflake/cli/api/commands/flags.py, tests/__snapshots__/test_help_messages.ambr, tests/__snapshots__/test_sql.ambr
Fix for typo in docstring (as requested by @sfc-gh-mheavin)
=> Typo fix in generated docs

.github/workflows/jira_issue.yml, src/snowflake/cli/api/commands/flags.py
Fix for community issues workflow- if there's now component, new jira filter won't show the issue
=> Community issues workflow update

pyproject.toml, snyk/requirements.txt, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/api/project/schemas/updatable_model.py, tests/__snapshots__/test_help_messages.ambr, tests/__snapshots__/test_sql.ambr, tests_e2e/__snapshots__/test_installation.ambr, tests_integration/test_snowpark.py
=> Cherrypick for v3.4.0

.github/workflows/jira_issue.yml
=> Fix for issue creation workflow

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr
=> Bump main version

.github/workflows/test_perfomance.yaml
=> Separate unit and perfomance testing

pyproject.toml, tests_integration/test_package.py
Freeze version of Zendesk package used in tests and change test condition for new github Windows worker
=> Snow 1953009 fix failing test on main

src/snowflake/cli/api/commands/flags.py, tests/__snapshots__/test_docs_generation_output.ambr, tests/__snapshots__/test_help_messages.ambr, tests/__snapshots__/test_sql.ambr, tests/api/commands/__snapshots__/test_snow_typer.ambr, tests/test_connection.py, tests/test_sql.py, tests_integration/test_connection.py
* Improve diagnostic report help messages
=> Improve diagnostic report help messages

src/snowflake/cli/_plugins/notebook/commands.py, src/snowflake/cli/_plugins/snowpark/commands.py, src/snowflake/cli/_plugins/streamlit/commands.py, tests/__snapshots__/test_help_messages.ambr
Add information about files not being removed from stage if `--replace` flag is used in `deploy` commands.
This PR updates the documentation for 3.5.0 release, it will have a follow-up introducing `--prune` flag
=> Improve deploy replace help message

tests_integration/test_notebooks.py
QA introduced runtime validation for notebook create command, which caused our test to fail.
This PR replaces it with test working on QA, and adds appropriate comment when the change will reach prod environments
=> Fix notebook test failing on QA

RELEASE-NOTES.md
* [] I've confirmed that instructions included in README.md are still correct after my changes in the codebase.
...
=> docs: release notes 3.5.0

tests_integration/test_notebooks.py
Fix error message assert in QA-only notebook test.
=> Fix error message assert in QA test

.github/workflows/test_integration_spcs.yaml, pyproject.toml, tests_integration/spcs/test_registry.py, tests_integration/spcs/test_services.py
This reverts commit 9c795236
...
=> Revert "Moved back SPCS tests to integration tests (#2047)"

src/snowflake/cli/_plugins/notebook/commands.py, src/snowflake/cli/_plugins/spcs/compute_pool/commands.py, src/snowflake/cli/_plugins/spcs/image_repository/commands.py, src/snowflake/cli/_plugins/spcs/services/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/spcs/test_compute_pool.py, tests/spcs/test_image_repository.py, tests/spcs/test_services.py
Make snowflake.yml required file for spcs deploy commands
=> Make snowflake.yml required file for spcs deploy commands

pyproject.toml, snyk/requirements.txt
=> Bump jinja2 and python connector

pyproject.toml, snyk/requirements.txt, src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr
=> Cherrypicks 3.5.0rc2

src/snowflake/cli/_plugins/object/command_aliases.py, src/snowflake/cli/_plugins/project/commands.py, src/snowflake/cli/api/constants.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm_project/test_dcm_project.py, tests/test_help_messages.py, tests/testing_utils/fixtures.py, tests_integration/test_dcm_project.py
Implements `project list` command with support of common options: `like` and `in`
=> feat: [SNOW-1942858] implement project list command

src/snowflake/cli/__about__.py, tests_e2e/__snapshots__/test_installation.ambr
=> Bump version to 3.5.0

src/snowflake/cli/__about__.py
=> Bump dev version to 3.6.0

tests_integration/test_sql.py, tests_integration/test_temporary_connection.py
=> Fixed invalid private key on Windows

.github/workflows/test_integration_spcs.yaml
=> Remove SPCS tests from PRs

RELEASE-NOTES.md, src/snowflake/cli/_app/version_check.py, tests/app/test_version_check.py
Added missing parameter `file_size_limit_mb` in `_read_latest_version` method
Updated `REPOSITORY_URL` to `https://pypi.org/pypi/snowflake-cli/json
=> mraba/version-check-fix: add missing file_size_limit_mb for cache file

output/bundle/streamlit/main.py, src/snowflake/cli/__about__.py
Bump version to 3.6.0rc0 and update release notes for 3.6.0
=> Bump release 3.6.0 rc0

tests_e2e/__snapshots__/test_error_handling.ambr, tests_e2e/__snapshots__/test_installation.ambr, tests_e2e/__snapshots__/test_nativeapp.ambr, tests_e2e/conftest.py, tests_e2e/test_error_handling.py
Remove trailing whitespaces check from e2e tests snapshots
=> Remove trailing whitespaces in e2e snapshots

src/snowflake/cli/_app/snow_connector.py
=> Fix typo in error message

RELEASE-NOTES.md, src/snowflake/cli/_plugins/stage/manager.py, tests/git/test_git_commands.py, tests/stage/test_stage.py
Added file execute log for stage and git.
=> Added file execute log for stage and git

src/snowflake/cli/_plugins/auth/keypair/commands.py, src/snowflake/cli/_plugins/auth/keypair/manager.py, tests/auth/__snapshots__/test_auth.ambr, tests/auth/test_auth.py
The auth rotate command only overwrites the connection.
=> Auth rotate only overwrite connection

RELEASE-NOTES.md, scripts/packaging/build_isolated_binary_with_hatch.py, src/snowflake/cli/__about__.py, src/snowflake/cli/_app/snow_connector.py, src/snowflake/cli/_app/telemetry.py, src/snowflake/cli/_plugins/auth/keypair/commands.py, src/snowflake/cli/_plugins/auth/keypair/manager.py, src/snowflake/cli/_plugins/connection/commands.py, src/snowflake/cli/_plugins/stage/manager.py, src/snowflake/cli/api/exceptions.py, tests/auth/__snapshots__/test_auth.ambr, tests/auth/test_auth.py, tests/git/test_git_commands.py, tests/stage/test_stage.py, tests/test_connection.py, tests_e2e/__snapshots__/test_error_handling.ambr, tests_e2e/__snapshots__/test_installation.ambr, tests_e2e/__snapshots__/test_nativeapp.ambr, tests_e2e/conftest.py, tests_e2e/test_error_handling.py
=> Cherrypicks v3.6.0 rc1

tests_integration/test_notebooks.py
Fix notebooks integration test after Snowflake rollout
=> Fix integration test after Snowflake rollout

scripts/packaging/build_darwin_package.sh
Fix cargo installation script for MacOS x86
Testing:
* x86: https://ci-dev-122.int.snowflakecomputing.com/job/SnowflakeCLI-Mac-x86/92/ 
* arm64: https://ci-dev-122.int.snowflakecomputing.com/view/SnowflakeCLI/job/SnowflakeCLI-MacArm64/262/
=> Snow 2011455 mac binary build fix

scripts/packaging/win/snowflake_cli_exitdlg.wxs
Fixes https://github.com/snowflakedb/snowflake-cli/issues/1960
Fix overlapping text in Windows installer
Build binaries from [before](https://ci-dev-122.int.snowflakecomputing.com/job/SnowflakeCLI-Win-x86-64-Installer/108/) and [after](https://ci-dev-122.int.snowflakecomputing.com/job/SnowflakeCLI-Win-x86-64-Installer/109/) the change and test them manually on Windows virtual machine.
=> Fix text positioning in Windows installer.

src/snowflake/cli/_plugins/auth/keypair/commands.py, src/snowflake/cli/api/commands/flags.py, tests/__snapshots__/test_docs_generation_output.ambr, tests/__snapshots__/test_help_messages.ambr, tests/api/commands/__snapshots__/test_snow_typer.ambr, tests/sql/__snapshots__/test_sql.ambr
=> Updated docs for auth commands

scripts/cleanup.py
Added roles to cleanup script and added if for owner
=> Added roles to cleanup script and added if for owner

src/snowflake/cli/_plugins/project/commands.py, src/snowflake/cli/_plugins/project/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm_project/test_dcm_project.py, tests/dcm_project/test_dcm_project_manager.py, tests_integration/test_dcm_project.py
& minor fixes to project add version command
https://snowflakecomputing.atlassian.net/browse/SNOW-1994372
=> feat: [SNOW-1994372] implement project list versions command

RELEASE-NOTES.md, src/snowflake/cli/_plugins/auth/__init__.py, src/snowflake/cli/api/feature_flags.py, tests/__snapshots__/test_help_messages.ambr, tests_e2e/__snapshots__/test_installation.ambr
=> Hide auth keypair behind feature flag

RELEASE-NOTES.md, scripts/packaging/build_darwin_package.sh, scripts/packaging/win/snowflake_cli_exitdlg.wxs, src/snowflake/cli/__about__.py, src/snowflake/cli/_plugins/auth/__init__.py, src/snowflake/cli/_plugins/auth/keypair/commands.py, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/api/feature_flags.py, tests/__snapshots__/test_docs_generation_output.ambr, tests/__snapshots__/test_help_messages.ambr, tests/api/commands/__snapshots__/test_snow_typer.ambr, tests/sql/__snapshots__/test_sql.ambr, tests_e2e/__snapshots__/test_installation.ambr, tests_integration/test_notebooks.py
* https://github.com/snowflakedb/snowflake-cli/pull/2168
* https://github.com/snowflakedb/snowflake-cli/pull/2158
* https://github.com/snowflakedb/snowflake-cli/pull/2157
* https://github.com/snowflakedb/snowflake-cli/pull/2156
* https://github.com/snowflakedb/snowflake-cli/pull/2155
=> Cherry picks to v3.6.0

scripts/packaging/build_isolated_binary_with_hatch.py
Fix binary building script as jenkins seems to misbehave with `@contextmanager` lib - override was reverted before the project had a chance to be installed. Changes tested on mac build with additional debug command displaying installation source info.
=> Binary building fix

src/snowflake/cli/_app/loggers.py, src/snowflake/cli/_app/snow_connector.py, src/snowflake/cli/_plugins/init/commands.py, src/snowflake/cli/_plugins/sql/manager.py, src/snowflake/cli/api/cli_global_context.py, src/snowflake/cli/api/commands/decorators.py, src/snowflake/cli/api/commands/flags.py, src/snowflake/cli/api/config.py, src/snowflake/cli/api/exceptions.py, src/snowflake/cli/api/plugins/plugin_config.py, src/snowflake/cli/api/project/schemas/template.py, src/snowflake/cli/api/rendering/project_templates.py, src/snowflake/cli/api/rendering/sql_templates.py, src/snowflake/cli/api/utils/definition_rendering.py, src/snowflake/cli/api/utils/templating_functions.py, tests/__snapshots__/test_docs_generation_output.ambr, tests/__snapshots__/test_help_messages.ambr, tests/api/artifacts/test_enhanced_error_codes.py, tests/api/utils/test_definition_rendering.py, tests/api/utils/test_templating_functions.py, tests/nativeapp/codegen/templating/test_templates_processor.py, tests/nativeapp/test_post_deploy_for_app.py, tests/nativeapp/test_post_deploy_for_package.py, tests/output/__snapshots__/test_silent_output.ambr, tests/output/test_silent_output.py, tests/sql/__snapshots__/test_sql.ambr, tests/sql/test_sql_enhanced_exit_codes.py, tests/test_common_decorators.py, tests/test_config.py, tests/test_logs.py
Created sets of Exceptions to be used as base for use in cli.
Updated `snow sql` to use new exceptions.
Added global option to return extended exit codes in scripts
=> SNOW-1911022: enhanced exit code with base CliError

src/snowflake/cli/_plugins/connection/commands.py, tests/test_connection.py
=> Added missing feature flag check for auth

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
Update release notes and bump version to 3.8.0.dev0
=> Bump release notes 3.7.0

src/snowflake/cli/_plugins/logs/commands.py, src/snowflake/cli/_plugins/logs/manager.py, src/snowflake/cli/_plugins/logs/utils.py, tests/__snapshots__/test_help_messages.ambr, tests/logs/__snapshots__/test_logs.ambr, tests/logs/test_logs.py, tests/logs/test_logs_utils.py, tests_integration/test_data/projects/snowpark_v2/c.py
Added `--log-level` flag to `snow-logs`
=> `Snow logs` fixes part 2: logs strike back

.github/workflows/test_integration_spcs.yaml
run SPCS tests on pull requests to release branches
=> run SPCS check on release PRs

RELEASE-NOTES.md, scripts/packaging/macos/postinstall
Extended MacOS postinstall script to update rc files if snow path is not present in PATH.
=> SNOW-2040358 update all scripts if snow is not in the path

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Cherrypicks v3.7.0

src/snowflake/cli/api/rendering/sql_templates.py, tests/sql/test_sql.py, tests_integration/sql/__snapshots__/test_source_reader.ambr
Add information about removing legacy SQL template syntax to displayed warning
=> Add removing legacy templating info to displayed warning

RELEASE-NOTES.md, pyproject.toml, snyk/requirements.txt
Newest release of `certifi` (2025.04.26) does not support connections to S3. This PR pins the version to 2025.01.31
=> Fix connection certificate issues

RELEASE-NOTES.md, src/snowflake/cli/_plugins/spcs/image_registry/manager.py, tests/spcs/test_registry.py
Added a faster query attempt to get image repository url in `snow spcs image-registry login`
=> adding faster query to `snow spcs image-registry login`

RELEASE-NOTES.md, pyproject.toml, snyk/requirements.txt, src/snowflake/cli/__about__.py, src/snowflake/cli/_plugins/spcs/image_registry/manager.py, tests/spcs/test_registry.py
=> Cherry picks to 3.7.1

RELEASE-NOTES.md, src/snowflake/cli/_plugins/spcs/services/manager.py, src/snowflake/cli/api/artifacts/upload.py, src/snowflake/cli/api/artifacts/utils.py, src/snowflake/cli/api/project/project_paths.py, tests/dcm_project/test_commands.py, tests/notebook/test_notebook_commands.py, tests/spcs/test_services.py, tests/streamlit/test_artifacts.py
Cleaning up the output directory after coping files to the stage for Streamlit, Notebook, SPCS Service and project.
=> Cleaning up output directory

src/snowflake/cli/_plugins/project/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm_project/test_commands.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2057618
=> feat: [SNOW-2057618] add project drop alias

RELEASE-NOTES.md
=> Bump release notes for 3.7.1 release

.github/workflows/test_fork.yaml
=> Fork prints

.github/workflows/test_e2e.yaml, .github/workflows/test_fork.yaml, .github/workflows/test_integration.yaml
=> Fork build fix

pyproject.toml, snyk/requirements.txt
Remove dependency on `certifi` as the issue is handled in `snowflake-connector-python 3.15`
=> Remove certifi depencency

.github/workflows/test_fork.yaml
=> Added logs for fork update script

src/snowflake/cli/api/cli_global_context.py
Updated annotations for `snow_api_root` in global context
=> mraba/core-root-typing: use Typing fro snowflake.core.Root annotations

tests_integration/test_snowpark_external_access.py
=> Remove temporary skip from integration test for snowpark external access

.github/workflows/cleanup.yaml, .github/workflows/matrix.yaml, .github/workflows/ok_to_test.yml, .github/workflows/test_e2e.yaml, .github/workflows/test_fork.yaml, .github/workflows/test_integration.yaml, .github/workflows/test_integration_spcs.yaml, .github/workflows/test_trusted.yaml
Reverted fork fix.
Left permissions.
Commented ok-to-test workflow, it doesn't work anyway.
=> Reverted fork fix but left permissions

tests/test_performance.py
Increased performance test threshold 3.1 -> 3.3
=> Increased performance test threshold

src/snowflake/cli/__about__.py, tests/test_performance.py
=> Bump version to v3.8.0-rc0

tests_integration/test_cortex.py
Skip remaining cortex tests from QA6 as they keep timing out. Other tests have already been skipped, which suggests that cortex models are not properly set up on QA environment.
Jenkins job showing cortex tests timing out independently from other tests: https://ci-dev-122.int.snowflakecomputing.com/job/RT-Snowflake-CLI/299/console
=> Skip cortex tests on QA

src/snowflake/cli/_plugins/sql/commands.py, src/snowflake/cli/_plugins/sql/manager.py, tests_integration/test_single_transaction_autocommit.py
fixed issues with `--single-transaction` while input is stdin or file
=> SNOW-2100677: fix single transaction for stdin and files

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py, tests_integration/nativeapp/test_release_channels.py
Fix deprecation message for enable_release_channels feature flag
=> Fix deprecation message for enable_release_channels feature flag

src/snowflake/cli/_plugins/dbt/commands.py, src/snowflake/cli/_plugins/dbt/constants.py, tests/__snapshots__/test_help_messages.ambr
=> feat: [SNOW-2048251] enable dbt run-operation

src/snowflake/cli/_plugins/project/commands.py, tests/dcm_project/test_commands.py, tests_integration/test_dcm_project.py, tests_integration/test_utils.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2101016
=> feat: [SNOW-2101016] check if project exists before adding new version

src/snowflake/cli/_plugins/sql/snowsql_commands.py, tests/sql/test_snowsql_commands.py, tests_integration/conftest.py, tests_integration/sql/__snapshots__/test_snowsql_commands.ambr, tests_integration/sql/test_snowsql_commands.py
Add `start_date` and `end_date` filter to `!queries` command.
Integration tests not added as qa and integration environment time out
=> Snow 2101032 add date filters to query command

src/snowflake/cli/_plugins/dbt/manager.py, tests/dbt/test_dbt_commands.py, tests/dbt/test_manager.py, tests_integration/test_data/projects/dbt_project/profiles.yml
https://snowflakecomputing.atlassian.net/browse/SNOW-2102782
=> feat: [SNOW-2102782] support threads in profiles.yaml

src/snowflake/cli/_plugins/project/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm_project/test_commands.py, tests_integration/test_dcm_project.py
Add `--if-not-exists` flag to `snow project create` command
=> Add --if-not-exists flag to project create

src/snowflake/cli/__about__.py, src/snowflake/cli/_plugins/sql/snowsql_commands.py, tests/sql/test_snowsql_commands.py, tests_integration/sql/__snapshots__/test_snowsql_commands.ambr
=> Cherrypicks v3.8.0

tests_integration/spcs/test_image_repository.py
Skip the spcs list images test on QA due to missing image on the testing account
Tests: https://ci-dev-122.int.snowflakecomputing.com/job/RT-Snowflake-CLI/320/
=> SNOW-2097310 skip spcs list images test on QA

src/snowflake/cli/_plugins/dbt/manager.py, tests/dbt/test_dbt_commands.py, tests_integration/__snapshots__/test_dbt.ambr, tests_integration/test_dbt.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2103792
=> feat: [SNOW-2103792] support altering existing dbt objects in deploy command

RELEASE-NOTES.md, src/snowflake/cli/_app/version_check.py, tests/app/test_version_check.py
Move upgrade message to stderr
=> Snow 2106756 move upgrade warning to stderr

.github/workflows/matrix.yaml, RELEASE-NOTES.md, pyproject.toml, snyk/requirements.txt, tests/nativeapp/codegen/test_sandbox.py, tests_common/conftest.py, tests_e2e/conftest.py, tests_e2e/test_installation.py, tests_e2e/test_nativeapp.py, tests_integration/nativeapp/test_bundle.py, tests_integration/test_git.py
=> fix cli for python 3.13

.github/workflows/matrix.yaml, RELEASE-NOTES.md, pyproject.toml, snyk/requirements.txt, src/snowflake/cli/_app/version_check.py, tests/app/test_version_check.py, tests/nativeapp/codegen/test_sandbox.py, tests_common/conftest.py, tests_e2e/conftest.py, tests_e2e/test_installation.py, tests_e2e/test_nativeapp.py, tests_integration/nativeapp/test_bundle.py, tests_integration/test_git.py
=> Cherrypicks v3.8.1 rc0

RELEASE-NOTES.md
=> chore: update release notes

src/snowflake/cli/__about__.py
=> Bump version to v3.8.1

scripts/cleanup.py
Add "test_role" to known roles in cleanup script
Testing: added role by hand in and run failing snowpark test on QA6: https://ci-dev-122.int.snowflakecomputing.com/job/RT-Snowflake-CLI/343
=>  Add "test_role" to known roles in cleanup script

tests_integration/test_snowpark.py
Temporarily skip tests failing due to QA6 account misconfiguration
tests: https://ci-dev-122.int.snowflakecomputing.com/job/RT-Snowflake-CLI/340/
=> temporarily skip failing tests

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/_plugins/spcs/image_registry/commands.py, src/snowflake/cli/_plugins/spcs/image_registry/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/spcs/test_registry.py
=> Cherrypicks v3.8.3

RELEASE-NOTES.md
Update release notes after 3.8.3 release
=> update release notes

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Bump release notes 3.9.0

src/snowflake/cli/__about__.py
=> Bump version to v3.9.0-rc0

src/snowflake/cli/__about__.py
=> Bump version to v3.9.0

.github/workflows/test_integration.yaml
=> Added create issue permission for integration tests

src/snowflake/cli/_plugins/project/commands.py, tests/dcm_project/test_commands.py, tests_integration/test_dcm_project.py
Fix output of `snow project execute/dry-run` commands
=> Snow 2127689 fix project execute/dry run output

.github/workflows/test_e2e.yaml, .github/workflows/test_fork.yaml, .github/workflows/test_trusted.yaml
Fix integration flaky test report mechanism
=> Fix integration flaky test report mechanism

RELEASE-NOTES.md
Updating the release notes to capture the changes made in https://github.com/snowflakedb/snowflake-cli/pull/2348
=> SNOW-208958: Update release notes

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/_plugins/project/commands.py, src/snowflake/cli/_plugins/spcs/image_registry/commands.py, src/snowflake/cli/_plugins/spcs/image_registry/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm_project/test_commands.py, tests/spcs/__snapshots__/test_registry.ambr, tests/spcs/test_registry.py, tests_integration/test_dcm_project.py
=> Cherry picks to 3.9.1

scripts/release-plugin/src/snowflakecli_internal_release_plugin/commands.py, scripts/release-plugin/src/snowflakecli_internal_release_plugin/repo_manager.py
Add fixes to release plugin after 3.9.1 release:
* Fix detecting branches, which were not created locally
* Add flow for patch releases
=> update release plugin

pyproject.toml, tests_integration/spcs/test_image_repository.py, tests_integration/test_dcm_project.py, tests_integration/testing_utils/streamlit_utils.py
Fix too strict assertions for tests, which were causing errors on QA6 deployment
=> Fix qa6 tests

RELEASE-NOTES.md, src/snowflake/cli/_app/printing.py, tests/output/test_printing.py
Output for `Decimal` was cut, it shouldn't.
Adressess #2386
=> SNOW-2149992 Fix JSON serialization for Decimal

pyproject.toml
=> Decrease concurrent integration tests

src/snowflake/cli/_plugins/cortex/commands.py, src/snowflake/cli/_plugins/cortex/manager.py, src/snowflake/cli/_plugins/stage/manager.py, src/snowflake/cli/api/cli_global_context.py, src/snowflake/cli/api/entities/common.py
Added lazy loading for snowflake.core module, locally time dropped from 1.8s to 0.9s.
=> Added lazy loading for snowflake.core module

.github/workflows/jira_issue.yml
Change filters for `jira create` workflow, to:
* remove labels - this duplicate workflow run
* remove filtering out the bot, as bots are filtered out by github by default
=> Fix filters for jira_issue.yml

.github/workflows/test_trusted.yaml
Change github token used for flaky integration test detection, so it can trigger another workflow
=> SNOW-2148471 Enable flaky test detection workflow to create jira tickets

RELEASE-NOTES.md, src/snowflake/cli/_plugins/snowpark/common.py, src/snowflake/cli/_plugins/snowpark/snowpark_entity.py, src/snowflake/cli/_plugins/snowpark/snowpark_entity_model.py, tests/snowpark/__snapshots__/test_models.ambr, tests/snowpark/__snapshots__/test_snowpark_entity.ambr, tests/snowpark/test_function.py, tests/snowpark/test_function_old_build.py, tests/snowpark/test_procedure.py, tests/snowpark/test_procedure_old_build.py, tests/snowpark/test_snowpark_entity.py
Added packages alias for artifact_repository_packages
=> Added packages alias for artifact_repository_packages

src/snowflake/cli/_plugins/project/commands.py, src/snowflake/cli/_plugins/project/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm_project/test_commands.py, tests/dcm_project/test_manager.py, tests_integration/test_dcm_project.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2154833
=> feat: [SNOW-2154833] implement project drop-version command

tests_common/deflake.py
Parse test message to detect two known issues:
* call limit exceeded
* GS instance is still unavailable
Run workflow on test branch and see that the issue is not created: https://github.com/snowflakedb/snowflake-cli/pull/2440
=> Filter false positives from flaky test detection

RELEASE-NOTES.md, src/snowflake/cli/_plugins/stage/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/stage/__snapshots__/test_stage.ambr, tests/stage/test_stage.py, tests_integration/test_stage.py
https://snowflakecomputing.atlassian.net/browse/SNOW-1213448
=> SNOW-1213448 add support stage-to-stage copy

.github/workflows/test_cli_action.yaml, .github/workflows/test_cli_action_main_branch.yaml, .github/workflows/test_cli_action_release_pr.yaml, src/snowflake/cli/_app/telemetry.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2174441
=> extra telemetry for gha

RELEASE-NOTES.md, src/snowflake/cli/__about__.py
=> Bump release notes 3.10.0

src/snowflake/cli/api/commands/snow_typer.py, src/snowflake/cli/api/feature_flags.py, tests/__snapshots__/test_help_messages.ambr, tests/api/commands/test_snow_typer.py, tests_e2e/__snapshots__/test_installation.ambr
https://snowflakecomputing.atlassian.net/browse/SNOW-2178027
=> SNOW-2178027 revert explicit preview changes

.github/workflows/test_integration_container_services.yaml
fixes 
```
The workflow is not valid. .github/workflows/test_integration_container_services.yaml (Line: 30, Col: 3): Error calling workflow 'snowflakedb/snowflake-cli/.github/workflows/test_trusted.yaml@d7faffbfd9c575d5acd326c2bc4e8cf2dee2f8c1'. The workflow is requesting 'issues: write', but is only allowed 'issues: none'.
```
https://github.com/snowflakedb/snowflake-cli/actions/runs/16284853585
=> ci: [NOSNOW] add issue write permission to action

src/snowflake/cli/__about__.py
=> Bump version to v3.10.0

src/snowflake/cli/_plugins/dcm/commands.py, src/snowflake/cli/_plugins/dcm/manager.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm/test_commands.py, tests/dcm/test_manager.py, tests_integration/test_dcm_project.py
* [] I've confirmed that instructions included in README.md are still correct after my changes in the codebase.
...
=> rename `drop-version` to `drop-deployment`. SQL unchanged

src/snowflake/cli/_plugins/dcm/commands.py, src/snowflake/cli/_plugins/object/command_aliases.py, src/snowflake/cli/_plugins/object/commands.py, src/snowflake/cli/_plugins/object/manager.py, src/snowflake/cli/_plugins/snowpark/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/dcm/test_commands.py, tests/object/test_object.py, tests_integration/test_dcm_project.py, tests_integration/test_object.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2236093
=> feat: [SNOW-2236093] add terse and limit options to list aliases

RELEASE-NOTES.md
Updated command name for odic in release notes
=> mraba/rc-311-update: fix release notes for oidc

src/snowflake/cli/_plugins/dbt/manager.py, tests/dbt/test_dbt_commands.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2256576
=> fix: [SNOW-2256576] dbt deploy - handle quoted names gracefully

src/snowflake/cli/_plugins/auth/oidc/manager.py, tests/auth/test_oidc_manager.py
`snow auth oidc delete` only if user `has_workload_identity = true`
=> SNOW-2259409: delete user only if is federated user

RELEASE-NOTES.md, src/snowflake/cli/_plugins/sql/statement_reader.py, tests/sql/test_statement_reader.py
Improved handling `!source` with trailing comments
=> Snow 2272627 sql handle comments on !source command

pylock.toml, pyproject.toml, snyk/requirements.txt
bumped `snowflake-core` to `1.7.0`
=> mraba/bump-snowflake-core bump snowflake-core to 1.7.0

tests_integration/sql/test_async_queries.py
Longer backoff for testing async queries.
Fixes https://github.com/snowflakedb/snowflake-cli/issues/2434
=> SNOW-2231681 Extend wait times in async query tests

scripts/packaging/build_isolated_binary_with_hatch.py
Use old ways of building Mac binaries
=> SNOW-2089376 Restore original working Mac build approach while keeping Linux optimization

scripts/packaging/build_python.sh
Wheel build need `ensurepip` that was removed as an optimisation step
=> SNOW-2089376 fix wheel build

RELEASE-NOTES.md, pylock.toml, pyproject.toml, snyk/requirements.txt, tests/__snapshots__/test_help_messages.ambr, tests/api/commands/__snapshots__/test_snow_typer.ambr, tests/output/__snapshots__/test_silent_output.ambr, tests_e2e/__snapshots__/test_installation.ambr
=> mraba/bump-typer: bump typer to 0.17.3

RELEASE-NOTES.md, src/snowflake/cli/__about__.py, src/snowflake/cli/_app/__init__.py, src/snowflake/cli/_plugins/snowpark/common.py, src/snowflake/cli/_plugins/snowpark/package/anaconda_packages.py, src/snowflake/cli/_plugins/snowpark/package_utils.py, src/snowflake/cli/_plugins/sql/lexer/types.py, tests/snowpark/test_build.py, tests_integration/sql/test_sql.py, tests_integration/test_data/projects/snowpark_duplicate_test/app.py, tests_integration/test_data/projects/snowpark_duplicate_test/requirements.txt, tests_integration/test_data/projects/snowpark_duplicate_test/snowflake.yml, tests_integration/test_snowpark.py
=> Bump version to v3.12.0-rc0

tests_common/deflake.py
`Insufficient resource during interleaved execution`
The `Insufficient resource during interleaved execution` should be treated as known server bug and not cause flaky test reports.
Fixes #2602
=> SNOW-2335005 Add known server error to deflake 

src/snowflake/cli/_plugins/object/manager.py
Re-raise `err` if it's not the one we expected in the `_handle_create_error_codes`
=> SNOW-2337682 Fix for unknown error in `_handle_create_error_codes`

src/snowflake/cli/_plugins/dbt/commands.py, tests/__snapshots__/test_help_messages.ambr, tests/dbt/test_dbt_commands.py, tests_integration/test_dbt.py
https://snowflakecomputing.atlassian.net/browse/SNOW-2314571
=> feat: [SNOW-2314571] add dbt drop and describe commands
