snowflakedb/snowflake-cli

src/snowcli/__about__.py
src/snowcli/cli/function.py
src/snowcli/cli/procedure.py
src/snowcli/cli/snowpark_shared.py
src/snowcli/utils.py

Currently snowcli can examine a requirements.txt file, identify which packages are available on Anaconda, and download the remainder from PyPi to include in the app.zip artefact.
All of the dependencies of those PyPi packages are included, because pip has no way of knowing that Anaconda could provide some packages to the Snowpark object.
So this change is aimed at providing a second chance at leveraging Anaconda for packages not directly listed in requirements.txt.
This change adds a boolean parameter `--check-anaconda-for-pypi-deps` which performs an optional second Anaconda check over the full list of packages pip downloaded. This naturally only comes into effect if a pip install occurs. The default value is True which is a change in behaviour, I figured this is probably desirable and …

Snowpark packaging improvements

---

src/snowcli/__about__.py
src/snowcli/utils.py

As raised in #51, the pypi download cli parameter does not appear to work correctly.
This is due to a bug in the callback function which validates its value, by failing to return a value it causes the pypi downloads to be skipped.
I've tested all variations of the yes/no/ask parameters and all work as expected after this fix.

Fix bug in option validator causing PyPi download preference to be ignored

---

src/snowcli/cli/streamlit.py
src/snowcli/config.py
src/snowcli/snow_connector.py

This "generates" the appropriate Streamlit URLs based on available information.
In pre-prod envs, you'll need to set `snowflake_host` in your app.toml.
Also - I think I managed the fix all the segfaults by defining a destructor for the `SnowflakeConnector` class that closes the connection and cursor.

Fix up streamlit deploy URLs

---

src/snowcli/cli/streamlit.py

Fixes #54 
This makes `streamlit create --file relative/path.py` work the same as `streamlit deploy --file relative/path.py`, so that they both only look at the filename `path.py`.
Previously, `streamlit deploy` would create the file `path.py` in the new stage, but `streamlit create` would create a streamlit app that was expecting a path to be located at `relative/path.py`

Use filename when creating streamlit app, not full path

---

src/snowcli/cli/stage.py
src/snowcli/snow_connector.py
src/snowcli/sql/put_stage.sql

```
(python-3.10.3) ➜  snowcli git:(add-put-args) ✗ snow stage put test.txt sis_metrics_read_example_stage --no-overwrite
┏━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ source   ┃ target   ┃ source_size ┃ target_size ┃ source_compression ┃ target_compression ┃ status  ┃ message ┃
┡━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━┩
│ test.txt │ test.txt │ 0           │ 0           │ NONE               │ NONE               │ SKIPPED │         │
└──────────┴──────────┴─────────────┴─────────────┴────────────────────┴────────────────────┴─────────┴─────────┘
(python-3.10.3) ➜  snowcli git:(add-put-args) ✗ snow stage put test.txt sis_metrics_read_example_stage …
```

Add overwrite and parallel arguments to put_stage command

---

src/snowcli/snow_connector.py

When create a function with snowcli, it fails with the following stacktrace
```
/opt/homebrew/Cellar/snowcli/0.1.14/libexec/lib/python3.10/site-packages/snowcli/snow_connector. │
│ py:114 in uploadFileToStage                                                                      │
│                                                                                                  │
│   111 │   │   schema,                                                                            │
│   112 │   │   overwrite,                                                                         │
│   113 │   ):                                                                                     │
│ ❱ 114 │   │   self.cs.execute(f"use database {database}")                                        │
│   115 │   │ …
```

Fix "Create Function Failure" by ensuring role is set prior to db/schema setting

---

src/snowcli/sql/create_streamlit.sql
src/snowcli/sql/describe_streamlit.sql

Create Streamlit and Describe Streamlit are currently failing because no role is used in the SQL command even though it is passed in the python functions.

Add role usage to create and describe streamlits

---

.pre-commit-config.yaml
pyproject.toml
src/snowcli/cli/connection.py
src/snowcli/cli/function.py
src/snowcli/cli/procedure.py
src/snowcli/cli/snowpark_shared.py
src/snowcli/cli/warehouse.py
src/snowcli/config.py
src/snowcli/utils.py

#59 added linting with ruff via a pre-commit hook. This PR:
1. Adds the ability for ruff to automatically sort imports in `.py` files and modules via ruff's `isort` plugin, and uses ruff's `pyflakes` tool to detect errors.
2. Runs ruff on the codebase to sort imports.

Linting and sorting imports with Ruff's `isort` tool.

---

src/snowcli/snow_connector.py

Without the quotes it seems it automatically upper-cased the stage name, but with the quotes it doesn't, causing "does not exist" errors.

Fix stage name case since quotes are now added

---

src/snowcli/snow_connector.py

Test case for the fix:
```
params = ['(temp_f number(35,4))','(testparam1 varchar)','(testparam2 varchar(255))','(testparam3 varchar(1), testparam4 varchar)','(testparam5 varchar, testparam6 varchar(1))','()']
for param in params:
print('Test ' + param)
if param == "()":
print('New: ' + param)
else:
print('New: (' + ' '.join(param.split(' ')[1::2]))
print('Old: (' + ' '.join(param.strip("()").split()[1::2]) + ')')
print()
```
Output of test:
```
Test (temp_f number(35,4))
New: (number(35,4))
Old: (number(35,4)
Test (testparam1 varchar)
New: (varchar)
Old: (varchar)
Test (testparam2 varchar(255))
New: (varchar(255))
Old: (varchar(255)
Test (testparam3 varchar(1), testparam4 varchar)
New: (varchar(1), varchar)
Old: (varchar(1), varchar)
Test (testparam5 varchar, testparam6 varchar(1))
New: …
```

Fix for bug #53 handling parameters with optional parameters

---

.pre-commit-config.yaml
src/snowcli/__about__.py
src/snowcli/cli/package.py
src/snowcli/utils.py
tests/test_render.py

- Allow `-y` or `--yes` to install packages without prompt
- Use `subprocess` instead of `os.system()` so I can correctly catch errors when pip exits and return code
- Allow users to specify the path to pip if not found. This is helpful if `pip` doesn't exist because it's `pip3` or something

snow packages improvements

---

src/snowcli/cli/__init__.py
src/snowcli/cli/render.py
src/snowcli/cli/snowpark_shared.py
src/snowcli/cli/sql.py
src/snowcli/config.py
src/snowcli/snow_connector.py
tests/test_render.py
tests/test_sql.py

This PR adds `snow sql` command that allows executing query from string option, file or stdin:
```
➜ snow sql --help                                                       
Usage: snow sql [OPTIONS]                                                                                                                                                                                              
Executes Snowflake query.                                                                                                                                                                                              
Query to execute can be specified using - query option - filename option (all queries from file will be executed) - stdin by piping output, for example `snow render template my.sql | snow sql` …
```

Add simple sql command allowing to execute any query from cli

---

.gitignore
README.md
src/snowcli/__about__.py
src/snowcli/cli/snowpark_shared.py
src/snowcli/cli/streamlit.py
src/snowcli/python_templates/environment.yml.jinja
src/snowcli/python_templates/streamlit_app_launcher.py.jinja
src/snowcli/utils.py

This PR introduces the ability to have Streamlit-in-Snowflake launch from a packaged directory instead of a single script. The packaging process is identical to the existing Snowpark UDF/sproc process, including the ability to download PyPi packages in the absence of an Anaconda option.
Where Anaconda packages exist (either directly specified in requirements.txt or as dependencies of PyPi packages), an environment.yml file will be generated and uploaded to the stage.
I've been cautious to word it as a temporary workaround, with the expectation that eventually it won't be necessary.

Snowpark packaging for Streamlit

---

src/snowcli/__about__.py
src/snowcli/utils.py

This PR fixes a small bug which sometimes occurs when doing a second-round check of Anaconda packages

Fix bug in certain code paths in second-change packaging

---

src/snowcli/cli/snowpark/package.py
src/snowcli/cli/snowpark/procedure_coverage/clear.py
src/snowcli/cli/snowpark/procedure_coverage/report.py
src/snowcli/cli/snowpark_shared.py
src/snowcli/cli/sql.py
src/snowcli/cli/stage.py
src/snowcli/cli/streamlit.py
src/snowcli/cli/warehouse.py
src/snowcli/config.py
src/snowcli/snow_connector.py
src/snowcli/utils.py
tests/__snapshots__/test_snow_connector.ambr
tests/test_snow_connector.py
tests/test_sql.py
tests/test_stage.py

I changed names of functions, variables and classes to stick with PEP-8 naming conventions. This is necessary, as we introduced stricter naming checks in pre-commit stage.

824873 rename functions to stick with pep 8 naming conventions

---

src/snowcli/cli/connection.py
tests/__snapshots__/test_connection.ambr
tests/test_connection.py

Add more parameters to `snow connection add` to support all basic options for connection configuration.

Add more parameters for connection add

---

pyproject.toml

Without this version of the snowflake connector, every separate snow command requires a new browser tab to be created. This version enables the credentials to be cached for a time after they are first created.
See https://github.com/Snowflake-Labs/snowcli/pull/66 for a previous version of this.

Cache connections to allow for multiple snow commands with browser authentication

---

src/snowcli/cli/common/flags.py

This helps because -h is sometimes overridden (e.g. `snow snowpark function create -h` uses -h for handler). It's still usable in some cases (though perhaps should be removed altogether), but this means that if you have an incomplete command, it will say 
```
Try 'snow <commands> --help' for help.
```
Rather than this (which doesn't always work)
```
Try 'snow <commands> --h' for help.
```
...

Show --help as suggestion rather than -h

---

.gitignore
src/snowcli/cli/app.py
src/snowcli/cli/common/flags.py
src/snowcli/cli/snowpark_shared.py
src/snowcli/config.py
src/snowcli/snow_connector.py
src/snowcli/utils.py
tests/test_config.py
tests/test_main.py
tests/test_sql.py

Add default_connection option

---

pyproject.toml
src/snowcli/config.py

Use official release of snowflake connector

---

src/snowcli/cli/constants.py
src/snowcli/cli/snowpark/__init__.py
src/snowcli/cli/snowpark/function/commands.py
src/snowcli/cli/snowpark/procedure/commands.py
src/snowcli/cli/snowpark/procedure/manager.py
src/snowcli/cli/snowpark_shared.py
src/snowcli/snow_connector.py
src/snowcli/sql/call_procedure.sql
src/snowcli/sql/drop_function.sql
src/snowcli/sql/drop_procedure.sql
src/snowcli/sql/execute_function.sql
src/snowcli/sql/list_functions.sql
src/snowcli/sql/list_procedures.sql
tests/snowpark/test_function.py
tests/snowpark/test_procedure.py
tests/streamlit/test_commands.py
tests/test_snow_connector.py
tox.ini

Refactor procedure commands

---

src/snowcli/cli/stage/commands.py
tests/test_stage.py

Fixes #331 by not requiring Typer to enforce that the path that is passed actually resolves to a valid local path, and allow glob-style paths to be passed directly.

Allow glob-style paths for snow stage put

---

src/snowcli/cli/common/flags.py

```
➜ snow snowpark procedure describe --help                  
Usage: snow snowpark procedure describe [OPTIONS]                                                                                                                                                                      
Describes a Snowflake procedure.                                                                                                                                                                                       
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --name              -n      TEXT  Name of the procedure …
```

Split global options into separate sections

---

src/snowcli/cli/nativeapp/commands.py
src/snowcli/cli/nativeapp/init.py
tests/nativeapp/__snapshots__/test_init.ambr
tests/nativeapp/test_commands.py
tests/nativeapp/test_init.py

This PR introduces an extension on the `snow app init` command for native apps, by allowing `--template` and `--git-url` options to be specified in this command. 
As a heads up, some existing code had to be refactored as part of introducing the new options and re-using existing code as much as possible. Accordingly, tests have been added which cover the new and refactored behavior.

[NADE] Add --git-url and --template option to "snow app init"

---

src/snowcli/cli/nativeapp/commands.py
src/snowcli/cli/nativeapp/init.py
tests/nativeapp/test_init.py

This PR adds a validation check to the project name for Native Apps Init command. 
1. This will minimize any conflicts between names used on different platforms, e.g. Windows v Linux/Mac. 
2. Since project name is used to populate default value of application package and application in snowflake.yml, we need to ensure that it is consistent with Snowflake's own identifier requirements, adapted to our use case (first two points in https://docs.snowflake.com/en/sql-reference/identifiers-syntax). This will prevent an experience where a developer creates a directory that may be a valid name on their OS but is not a valid object name in Snowflake, hence creating confusion.

[NADE] Add Project Name Validation + Clarify Help Command

---

src/snowcli/cli/common/sql_execution.py
src/snowcli/cli/nativeapp/artifacts.py
src/snowcli/cli/nativeapp/commands.py
src/snowcli/cli/nativeapp/manager.py
src/snowcli/cli/project/definition.py
src/snowcli/cli/project/schema.py
src/snowcli/cli/project/util.py
src/snowcli/cli/stage/diff.py
tests/nativeapp/test_artifacts.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_package_scripts.py
tests/project/napp_project_1/001-shared.sql
tests/project/napp_project_1/002-shared.sql
tests/project/napp_project_1/snowflake.yml
tests/project/test_config.py

Implements the "create application" and "apply package scripts" parts of snow app run.
Additional changes:
- `MockCursor` now has a correct `rowcount` property
- removes the ability to pass glob patterns in for package scripts, as well as the default value
- `SqlExecutionMixin.use_role` now correctly unsets the role upon exception
- fixed a bug that prevented single files with directory `dest`inations from working the second time around

[NADE] Create application / apply package scripts

---

RELEASE-NOTES.md
src/snowcli/app/cli_app.py
src/snowcli/app/commands_registration/commands_registration_with_callbacks.py
src/snowcli/app/dev/commands_structure.py
src/snowcli/cli/common/flags.py
src/snowcli/cli/snowpark/function/commands.py
src/snowcli/cli/snowpark/jobs/commands.py
tests/test_cli.py

* Alternative approach to #441
* Removed option duplicates by:
* Removing `-p` short option for `--password` option for all commands (backward incompatibility affecting all the commands using a connection) (it was conflicting with various options in a few commands)
* Removing `-a` short option for `--replace-always` in `snow snowpark function update` command (it was conflicting with short version of `--check-anaconda-for-pypi-deps`) 
* Removing `-c` short option for `--compute-pool` in `snow snowpark jobs create` (it was conflicting with short version of global `--connection` option)
* Removing `-c` short option for `--container-name` in `snow snowpark jobs logs` (it was conflicting with short version of global `--connection` option)
* Cherry-picked a test checking that there are no …

[v1.1.1] Removing option duplicates (backward incompatible way)

---

src/snowcli/app/cli_app.py
tests/test_main.py

* Added a handle to app context to have access to it in tests. We can't create a separate new context in tests, because plugin command registration is done only in the context of the running command.

Access to context in tests

---

src/snowcli/api/plugin/command/__init__.py

* Plugins mechanism accidentally added `--install-completion` and `--show-completion` options to all command / command groups registered as plugins. This change fixes it and removes these options, as they should be visible on only top-level `--help`.

Remove completion options from plugin commands

---

src/snowcli/app/cli_app.py

* External plugins are not part of 1.1.1 release so `--disable-external-command-plugins` shouldn't be visible in the help text.

Hide --disable-external-command-plugins option for v1.1.1

---

src/snowcli/cli/nativeapp/manager.py
src/snowcli/cli/project/definition.py
src/snowcli/cli/project/util.py
src/snowcli/cli/streamlit/manager.py
tests/nativeapp/test_manager.py
tests/testing_utils/fixtures.py

- rename `identifier_as_part` to `unquote_identifier`
- use `unquote_identifier` for all LIKE queries + introspecting returned results so any identifier will work properly
- search in returned resultsets for the right row, rather than assuming it's the first one (due to LIKE being unable to restrict to exact case)
- fix tests so that unquoted identifiers are returned in UPPERCASE
- fix a bug in config merging uncovered by using quoted identifiers (`YAML` objects can be scalar)

Proper identifier unquoting

---

CONTRIBUTING.md
pyproject.toml
src/snowcli/cli/common/snow_cli_global_context.py
tests/conftest.py
tests/snowpark/test_function.py
tests/snowpark/test_procedure.py
tests/stage/test_stage.py
tests/streamlit/test_commands.py
tests/test_command_registration.py
tests/test_connection.py
tests/test_main.py
tests/test_snow_connector.py
tests/test_sql.py
tests/testing_utils/fixtures.py
tests_integration/conftest.py
tox.ini

* `tests/nativeapp/test_manager.py` was failing on try of running it as single test module (`pytest tests/nativeapp/test_manager.py`) but everything was ok when running it as part of all tests (just `pytest`)
* The error occurred only in `test_get_snowsight_url` test case.
* The error was indicating that `authenticator` attribute is not present in `ConnectionDetails` in the global context.
* The error was correct because that class did not have `authenticator` and `private_key_path` fields.
* So why it worked for all other tests, why it worked in regular CLI invocations, why `pytest` didn't fail?
* `ConnectionDetails._connection_update` function sets attributes from CLI connection options. It added new attributes (not present as dataclass fields) to `ConnectionDetails` object for …

Fix: Add authenticator and private_key_path fields to ConnectionDetails dataclass

---

RELEASE-NOTES.md
src/snowcli/cli/snowpark/jobs/manager.py
src/snowcli/cli/snowpark/services/manager.py
tests/snowpark/test_jobs.py
tests/snowpark/test_services.py

* Fixes parsing of quotes and multiline strings in snowpark service / job specification
* Fixes #521
* Fixed by changing specification inlining to use `FROM SPECIFICATION $$ ... $$` syntax instead of `FROM SPECIFICATION ' ... '` syntax. `$$ ... $$` syntax is mentioned [here](https://docs.snowflake.com/LIMITEDACCESS/snowpark-containers/working-with-services) in docs.

[SNOW-961823] [SNOW-956924] Fix specification inlining when creating snowpark job or service

---

src/snowcli/cli/nativeapp/manager.py
src/snowcli/exception.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_package_scripts.py

1. There is scope for better error handling when the native apps commands try to execute either a `use warehouse ...` directly, or execute a query that requires use of warehouse, such as creation of an application. This PR is to address that scope.
2. There were some flaky unit tests observed intermittently on python 3.8/3.9/3.10 unit tests with use of `assert` with `ProgrammingError` depending on log level. So instead of testing for the whole error message's string, I have picked out a unique part of it to ensure it is present in the return values.

[NADE] Fix Error Handling for SQL Queries Involving Warehouse

---

src/snowcli/cli/nativeapp/manager.py
tests/nativeapp/test_manager.py

Applications installed in stage dev mode will soon use the string `UNVERSIONED` to report their "version" as opposed to the previous `dev_stage` symbol. We need to support both until the parameter has been fully rolled-out and retired.

Support both UNVERSIONED and dev_stage apps

---

src/snowcli/cli/streamlit/manager.py
tests/streamlit/test_commands.py
tests/test_data/projects/streamlit_full_definition/snowflake.yml

* [ x I've confirmed that my changes are up-to-date with the target branch.
Make single files be PUT to `root_stage/` instead of `root_stage/.`, which is invalid
Fixes #577

Make proper put commands for additional_source_files that aren't in a folder

---

src/snowcli/cli/nativeapp/commands.py
src/snowcli/cli/nativeapp/manager.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_manager_teardown.py
tests_integration/test_nativeapp.py

`snow app teardown` will no longer error out if either the application instance or package does not exist. As such, it can now drop the package in cases where the app instance has already been dropped. It will also exit successfully when neither the instance nor package exist, reflecting that the desired end-state has been reached (albeit without doing anything).

Idempotent + flexible app teardown

---

RELEASE-NOTES.md
src/snowcli/cli/common/cli_global_context.py
src/snowcli/cli/sql/commands.py
src/snowcli/cli/sql/manager.py
tests/test_sql.py
tests/testing_utils/result_assertions.py
tests_integration/test_sql.py

-i has to be provided to use stdin as query input

Use -i for stdin in snow sql

---

tests_integration/test_nativeapp.py

This PR introduces the `--force` flag as part of `snow app teardown` executed in the integration tests for native apps.

[NADE] Integration Tests' Cleanup

---

pyproject.toml

Moved `ruff` linting rules to `[tool.ruff.lint]` according to [docs](https://docs.astral.sh/ruff/configuration/#__tabbed_3_1)

mraba/ruff-linting-in-pyproject: move select to tool.ruff.lint section

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
src/snowflake/cli/plugins/nativeapp/run_processor.py
src/snowflake/cli/plugins/nativeapp/version/commands.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_run_processor.py

This PR makes two changes:
1. Enables directory param for the stage created where we upload files. This way our customers can explore the contents of the stage when they run `snow app` commands, and they do not need an extra step of enabling it.
2. Enables debug mode for versioned installs/upgrades, to keep it consistent across all development mode instances, not just loose files.

[NADE] Enable directory on stage + debug mode for versioned upgrades

---

src/snowflake/cli/plugins/streamlit/manager.py
tests/streamlit/test_commands.py
tests/testing_utils/fixtures.py
tests_integration/test_streamlit.py

Currently, if you do `snow streamlit deploy --experimental` it works fine, but if you do it a second time, it fails, because the ALTER STREAMLIT <name> CHECKOUT has already been done once. This is analogous to the normal `snow streamlit deploy`, which creates a STAGE the first time you do it, and then simply skips it in the future without raising an error.
There is an open [ticket](https://snowflakecomputing.atlassian.net/browse/STREAMLIT-5019) to make this behavior different, but it may be a while.

Skip 'checkout' step if checkout has already been added

---

RELEASE-NOTES.md
src/snowflake/cli/api/exceptions.py
src/snowflake/cli/api/project/util.py
src/snowflake/cli/plugins/object/common.py
src/snowflake/cli/plugins/spcs/common.py
src/snowflake/cli/plugins/spcs/compute_pool/commands.py
src/snowflake/cli/plugins/spcs/compute_pool/manager.py
src/snowflake/cli/plugins/spcs/services/commands.py
src/snowflake/cli/plugins/spcs/services/manager.py
tests/object/test_common.py
tests/spcs/test_common.py
tests/spcs/test_compute_pool.py
tests/spcs/test_services.py
tests_integration/spcs/test_cp.py
tests_integration/test_cp.py

Changes description
- Added additional CLI options to snow containers service create and snow containers pool create to match SQL interface.
- Updated unit tests for ServiceManager.create() and ComputePoolManager.create() and CLI interface of snow containers service create and snow containers pool create.
- Added generic CLI options for Comment and Tag options under object/common.py. These can be used for all other CLI commands that take Tag or Comment (e.g. other create commands, alter tag, alter comment, etc.).
- Minor unrelated typo fixes.
- **Duplicate of [PR#674](https://github.com/Snowflake-Labs/snowcli/pull/674) but from a main repository branch instead of a fork**
New Service Options:
New Compute Pool Options:
Example Output:
**Strangely, there seems to be an error/warning …

SNOW-1011737, SNOW-1011750: Add options to create commands for compute pool and service

---

src/snowflake/cli/api/constants.py
src/snowflake/cli/plugins/object/commands.py
src/snowflake/cli/plugins/object/manager.py
tests/object/__snapshots__/test_object.ambr
tests/object/test_object.py
tests_integration/test_object.py

Added image-repository to the supported objects for `snow object`. Note that DESCRIBE IMAGE REPOSITORY currently doesn't exist in SQL, thus `snow object describe` explicitly excludes image-repository for alignment.
Sample Output:

SNOW-1011764: Adding image-repository to supported objects.

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/compute_pool/commands.py
tests/spcs/test_compute_pool.py
tests_integration/spcs/test_cp.py

Renaming `spcs pool` command group to `spcs compute-pool` based on following proposal: [SPCS SnowCLI Support](https://docs.google.com/document/d/1GePLNDltNSbu1utuwUx0m7AZEA14fH8HaPAlUIKUXd0/edit#heading=h.wfnqxxuj4vft). Note that this is a partial revert of a previous change that removed `compute-pool` and `cp` in favor of `pool`.
**Usage Examples**:

SNOW-1039276: Rename `pool` to `compute-pool`

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/image_repository/commands.py
tests/spcs/test_image_repository.py
tests_integration/spcs/test_image_repository.py

(Requested by Native Apps)
Previously, the output of list images was formatted as DATABASE/SCHEMA/REPOSITORY/IMAGE. However, the (fully qualified) image name that users would actually use in account or in service specifications is **/** DATABASE/SCHEMA/REPOSITORY/IMAGE. Changed output of list images to add this slash.
**Example Usage**:

SNOW-1037643: Adding slash before output of list-images

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/compute_pool/commands.py
tests_integration/spcs/test_cp.py

Renamed `spcs pool stop` to `spcs pool stop-all`.**(Behavior Change)**. 
**Is it possible to include this change in 2.0RC? If not, I could deprecate `spcs pool stop` instead of removing it and make it a hidden alias for `spcs pool stop-all` to release after 2.0**.

SNOW-1039187: Renaming `spcs pool stop` to `stop-all`.

---

RELEASE-NOTES.md
src/snowflake/cli/api/project/util.py
src/snowflake/cli/api/sql_execution.py
src/snowflake/cli/plugins/spcs/image_repository/commands.py
src/snowflake/cli/plugins/spcs/image_repository/manager.py
tests/project/test_util.py
tests/spcs/test_image_repository.py
tests_integration/spcs/test_image_repository.py

Added a new convenience command of `snow spcs image-repository url` that returns the full URL given a repository name. Note that image repositories do not allow for quoted identifiers, so I have added checks that repository name inputs must be unquoted identifiers.
**Example Usage**

SNOW-1011766: Added 'snow spcs image-repository url <repo_name>' command

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/common.py
src/snowflake/cli/plugins/spcs/compute_pool/manager.py
src/snowflake/cli/plugins/spcs/image_repository/commands.py
src/snowflake/cli/plugins/spcs/image_repository/manager.py
src/snowflake/cli/plugins/spcs/services/manager.py
tests/spcs/test_common.py
tests/spcs/test_compute_pool.py
tests/spcs/test_image_repository.py
tests/spcs/test_services.py
tests_integration/spcs/test_image_repository.py

Added a command for `spcs image-repository create <repo_name>`. Added some new error messages for `spcs image-repository create` and `spcs compute-pool create` to identify when an object already exists.
**Usage:**
**New Error Messages:**

SNOW-1011761: Adding `image-repository create` command

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/__init__.py
src/snowflake/cli/plugins/spcs/image_registry/commands.py
src/snowflake/cli/plugins/spcs/image_registry/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/__snapshots__/test_registry.ambr
tests/spcs/test_registry.py
tests_e2e/__snapshots__/test_installation.ambr
tests_integration/spcs/test_registry.py

Added `snow spcs image-registry login` command that automatically fetches your account token and registry URL and tries to login with `docker login`.
**Usage**:
**Errors**:

SNOW-1011767: Adding 'spcs image-registry login' command

---

tests/spcs/test_compute_pool.py
tests_integration/spcs/docker/bootstrap_containers_setup.sh
tests_integration/spcs/spec/spec.yml
tests_integration/spcs/test_image_repository.py
tests_integration/spcs/test_services.py
tests_integration/testing_utils/snowpark_services_utils.py

Currently integration tests for SPCS services simply execute 'hello world' then terminate. This makes it difficult to test lifecycle methods such as `suspend` and `resume`. Furthermore, services are meant to be persistent, not single-execution (that's what jobs are for). In fact, our integration tests currently check that our service reaches a DONE state, which is not technically a supported state for services ([reference](https://docs.snowflake.com/en/sql-reference/functions/system_get_service_status?utm_source=snowscope&utm_medium=serp&utm_term=service+status)).
I propose that for our integration tests we deploy a service that echos whatever is sent to it. This is the service created in the [SPCS tutorial.](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/tutoria …

SNOW-1011779: Changing SPCS services integration test to use persistent service instead of job.

---

src/snowflake/cli/templates/default_streamlit/environment.yml

Even though SiS will automatically install streamlit when the app is deployed, if users are using this environment locally, it won't include essential packages like streamlit and snowpark. This seems like a sensible, minimal set of dependencies to me.

Add streamlit and snowpark as default streamlit environment.yml packages

---

src/snowflake/cli/api/config.py
src/snowflake/cli/api/exceptions.py
src/snowflake/cli/api/secure_utils.py
tests/test_config.py
tests/test_main.py
tests/test_sql.py
tests/testing_utils/files_and_dirs.py

Raising error when default configs (config.toml or connections.toml) have too wide permissions. Error will not be raised if some other config is passed even if defaults have too wide permissions.

Raise error when default configs have too wide permissions

---

src/snowflake/cli/api/console/console.py

Styles used for formatting CliConsole text use system colours.

SNOW-1054145-improve-cli-console-output-readability: use system colors for printed messaged

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/common.py
src/snowflake/cli/plugins/spcs/compute_pool/commands.py
src/snowflake/cli/plugins/spcs/compute_pool/manager.py
src/snowflake/cli/plugins/spcs/services/commands.py
src/snowflake/cli/plugins/spcs/services/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/test_compute_pool.py
tests/spcs/test_services.py
tests_integration/spcs/test_services.py
tests_integration/spcs/testing_utils/spcs_services_utils.py

Added commands for spcs compute-pool set --<property1> <value1> ... and spcs compute-pool unset <name> --<property1>  .... These commands allow you to set values or reset to default values for properties of an existing compute pool, equivalent to ALTER COMPUTE POOL <name> SET/UNSET .... Added unit and integration tests for these commands.

SNOW-1011780: `spcs service set/unset <properties...>` commands

---

src/snowflake/cli/api/exceptions.py
src/snowflake/cli/api/sql_execution.py
src/snowflake/cli/plugins/spcs/image_repository/manager.py
tests/spcs/test_image_repository.py
tests/test_sql.py
tests_integration/spcs/testing_utils/compute_pool_utils.py

[BUGFIX]
For schema level objects (image_repository, service) the connection database and schema must be specified otherwise unqualified names may be ambiguous about what object they refer to*. `get_repository_url` did not do this because it uses the show_specific_object function which does not check that connection database and schema are valid. This means that show_specific_object could potentially find multiple rows for the same repository name.
I have added an option to show_specific_object to check that database and schema are set when we are looking for schema level objects and updated corresponding unit tests. I have also done some cleanup on check_database_and_schema.
\* Otherwise there could be two objects with the same name **o** in different schemas. Operating on object **o** …

SNOW-1057620: Enforce that get-repository-url is called with a connection database and schema

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/compute_pool/commands.py
src/snowflake/cli/plugins/spcs/compute_pool/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/test_compute_pool.py
tests_integration/spcs/testing_utils/compute_pool_utils.py

Added a new command `spcs compute-pool status` to retrieve the current status of a compute pool along with a relevant message, if any. This is helpful for debugging and observability. Updated unit and integration tests to include this new command.
**Usage:**

SNOW-1055803: Adding compute-pool status command

---

RELEASE-NOTES.md
src/snowflake/cli/api/project/util.py
src/snowflake/cli/plugins/spcs/compute_pool/commands.py
src/snowflake/cli/plugins/spcs/image_repository/commands.py
src/snowflake/cli/plugins/spcs/services/commands.py
src/snowflake/cli/plugins/spcs/services/manager.py
tests/project/test_util.py
tests/spcs/test_services.py

Changed implementation of service commands from using _execute_schema_query to _execute_query. If no database/schema is specified in the connection, the user will see an SQL execution error stating to use a database/schema or qualified name. This is consistent with the behavior of commands like `snow object describe` and `snow object drop`.
Also added validation that service, image repository, and compute pool names must be unquoted identifiers.
**Usage**:
**Precedent from object commands**:

SNOW-1057322: Adding support for qualified names for services.

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/spcs/image_registry/manager.py
tests/spcs/test_registry.py

Previously, there was a bug that errors that occured during `docker login` when using `image-registry login` would appear above the ClickException output. This PR fixes that by properly capturing the error output and putting it into the ClickException message.
**Old**
**New**

Redirected stderr to PIPE in docker_registry_login so error output is properly captured

---

RELEASE-NOTES.md
src/snowflake/cli/api/sql_execution.py
src/snowflake/cli/api/utils/naming_utils.py
src/snowflake/cli/plugins/object/common.py
src/snowflake/cli/plugins/spcs/image_repository/commands.py
src/snowflake/cli/plugins/spcs/image_repository/manager.py
tests/api/utils/test_naming_utils.py
tests/spcs/test_image_repository.py
tests/spcs/test_jobs.py
tests/test_sql.py

Modified implementation of show_specific_object to allow qualified object names and added support for qualified image repository names by removing validation that image repository names are unqualified. Also added an explicit check that show_specific_object only returns a single row and throws an error otherwise.
**Usage**:
**Errors when database, schema, repository don't exist**:

SNOW-1043081: Adding support for qualified names for image repositories.

---

.github/CODEOWNERS

As title says. With the move from Snowflake-Labs to snowflakedb Github org, we can use the teams id in CODEOWNERS instead of specifying every NADE member's names.

[NADE] Update CODEOWNERS to use NADE team id.

---

src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/plugins/object/commands.py

Use like_option factory from API instead of redefinig `LikeOption` in object commands

unify LikeOption with api

---

src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/api/commands/project_initialisation.py
src/snowflake/cli/api/project/schemas/streamlit/streamlit.py
src/snowflake/cli/plugins/streamlit/commands.py
tests/__snapshots__/test_help_messages.ambr
tests/test_cli.py
tests/test_command_registration.py
tests_e2e/__snapshots__/test_installation.ambr

Changed `Streamlit` to `Streamlit app`

Fix Streamlit in docs

---

.pre-commit-config.yaml
.snyk/dependency-sync.py
.snyk/req-auto-generated.txt
pyproject.toml

Copy dependencies to requirements.txt in pre commit

---

src/snowflake/cli/plugins/nativeapp/artifacts.py
src/snowflake/cli/plugins/nativeapp/init.py

The `manifest.yml` file in the Snowflake Native App world can use non-quoted scalar values within square brackets, as yaml allows for this. As an example:
```
references:
- egress_eai:
label: "Egress Eai"
description: "EAI for Egress from NA+SPCS"
privileges: [USAGE]
```
In Yaml, a value in square brackets is interpreted as a flow sequence, i.e a list. As a result, StrictYaml expects for any values inside to be enclosed in quotes. It throws an error in the case above along the lines of "JSONesque flow mapping". 
On the other hand, pyyaml enforces no such restriction and its behavior aligns with the yaml specification. Since pyyaml is also being used elsewhere in the code, we can drop strictyaml here in favor of pyyaml.

[NADE][Bugfix] Use Pyyaml instead of StrictYAML

---

RELEASE-NOTES.md
src/snowflake/cli/api/config.py
src/snowflake/cli/app/snow_connector.py
src/snowflake/cli/plugins/connection/commands.py
tests/test_config.py
tests/test_connection.py
tests/test_data/projects/snowpark_procedures/app.py
tests/test_data/projects/snowpark_procedures_coverage/app.py
tests_integration/test_data/projects/snowpark/app/app.py
tests_integration/test_data/projects/snowpark_coverage/app/module/procedures.py
tests_integration/test_data/projects/snowpark_fully_qualified_name/app/app.py

* `snow connection list` - Stopped printing of details of connections which do not exist in config.toml but their name starts with other connection's name
* For example: connection `int` in config.toml and `SNOWFLAKE_CONNECTION_INT2_PASSWORD` env variable - we were printing the env variable value as part of `int` connection description, we won't do it anymore
* `snow connection list` - Stopped printing of unknown connection details (other than available via `connection add` command)
* For example: connection `int` in config.toml  has `foo=bar` setting and there is `SNOWFLAKE_CONNECTION_INT_ABC` env variable - we were printing both values, we won't do it anymore

[SNOW-1246922] Fix printing of env variables in connection list

---

RELEASE-NOTES.md
src/snowflake/cli/__about__.py
src/snowflake/cli/api/config.py
src/snowflake/cli/app/snow_connector.py
src/snowflake/cli/plugins/connection/commands.py
src/snowflake/cli/plugins/nativeapp/artifacts.py
src/snowflake/cli/plugins/nativeapp/init.py
tests/test_config.py
tests/test_connection.py
tests/test_data/projects/snowpark_procedures/app.py
tests/test_data/projects/snowpark_procedures_coverage/app.py
tests_integration/test_data/projects/snowpark/app/app.py
tests_integration/test_data/projects/snowpark_coverage/app/module/procedures.py
tests_integration/test_data/projects/snowpark_fully_qualified_name/app/app.py

Release v2.1.1 cp

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/snowpark/commands.py
src/snowflake/cli/plugins/snowpark/package/manager.py
src/snowflake/cli/plugins/snowpark/package_utils.py
src/snowflake/cli/plugins/snowpark/snowpark_package_paths.py
src/snowflake/cli/plugins/snowpark/snowpark_shared.py
tests/snowpark/test_snowpark_shared.py
tests/test_utils.py
tests_integration/conftest.py
tests_integration/test_snowpark.py
tests_integration/testing_utils/snowpark_utils.py

* Fixed https://github.com/snowflakedb/snowflake-cli/issues/906 - the of the issue is described in my first comments
* Added `SnowparkPackagePaths` dataclass.

[SNOW-1243569] Fixed snowpark build paths for builds with --project option

---

RELEASE-NOTES.md
performance_history_analysis.py
src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/api/commands/project_initialisation.py
src/snowflake/cli/api/console/abc.py
src/snowflake/cli/api/console/console.py
src/snowflake/cli/api/project/errors.py
src/snowflake/cli/plugins/nativeapp/exceptions.py
src/snowflake/cli/plugins/nativeapp/policy.py
src/snowflake/cli/plugins/nativeapp/teardown_processor.py
src/snowflake/cli/plugins/object/stage/diff.py
src/snowflake/cli/plugins/sql/commands.py
src/snowflake/cli/plugins/streamlit/manager.py
test_external_plugins/override_build_in_command/src/snowflakecli/test_plugins/override_build_in_command/commands.py
tests/object/stage/test_diff.py
tests/test_logs.py
tests/test_main.py
tests_integration/test_package.py
tests_integration/testing_utils/snowpark_utils.py

Various typo corrections. Most of these were in docstrings, but some were in message responses. 
It may be worthwhile to add this as a pre-commit hook excluding cli output test assertions where new lines can break spelling and for any non-english, but Snowflake, related terms.

chore: run codespell

---

src/snowflake/cli/api/sql_execution.py
src/snowflake/cli/plugins/connection/commands.py
tests/test_connection.py
tests/test_sql.py

Often users have only `USAGE` privilage on objects which does not allow to describe objects.

Utilise USE instead of DESC in connection test

---

RELEASE-NOTES.md
src/snowflake/cli/api/sql_execution.py
tests_integration/test_connection.py

Before:
```
➜ snow connection test -c int
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 002043 (02000): 01b3dc70-0509-12ff-0001-c1be00cebb6e: SQL compilation error:                                                                                                                                 │
│ Object does not exist, or operation cannot be performed.                                                                                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```

Make connection tests errors more meaningful

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
src/snowflake/cli/plugins/stage/commands.py
src/snowflake/cli/plugins/stage/diff.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_manager.py
tests/stage/test_diff.py
tests_integration/test_nativeapp.py

The current stage diff code assumes that Unix path separators are used on the local execution environment. This is not the case on Windows, leading to incorrect stage path separators being used. This change introduces an explicit `StagePath` type to make sure that stage paths are handled correctly throughout the diff & deploy logic. I also ended up fixing a hidden stage diff command that has always been broken.
Updated all existing tests to pass with the new logic, and removed the workaround for the Windows bug from previous commits. Also manually verified the behaviour of `snow app deploy` with various arguments as well as  `snow app run` on both Mac and Windows. I manually checked the contents of the remote app package stages to make sure the files were published correctly.

[SNOW-1345064] Fix stage path handling on Windows

---

src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
src/snowflake/cli/plugins/nativeapp/manager.py

Add a feature check in `build_bundle` to allow for codegen.

[NADE] Add feature check to allow codegen

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/snowpark/commands.py
src/snowflake/cli/plugins/snowpark/common.py
tests_integration/test_snowpark_external_access.py

Fixes the missing check for changes in `external access integrations` when deploying snowpark objects with `--replace`.
Also, this solves a little bug with building and udf sproc identifier, when argument is  set to empty string.

Snow 1348392 update replace checks

---

.gitignore
tests_integration/snowflake_connector.py

* I've added or updated integration tests to verify correctness of my new code.
When we use the `snowflake_session` fixture in our integration tests, the config values are read from env variables prefixed with `SNOWFLAKE_CONNECTIONS_INTEGRATION_`.
This PR adds `WAREHOUSE` and `ROLE` to the list.
I also added `.env` to `.gitignore` as it's a common convention to put there local/test configuration that you don't want to check in.
I noticed the problem when I tried to run the integration tests locally. I verified the values are correctly picked up after the change:
```
eval $(cat .env) python -m pytest -m integration …
```

Integration tests: use warehouse and role env vars

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/artifacts.py
src/snowflake/cli/plugins/nativeapp/manager.py
src/snowflake/cli/plugins/nativeapp/utils.py
tests/nativeapp/test_artifacts.py
tests_integration/nativeapp/test_bundle.py
tests_integration/nativeapp/test_deploy.py

Introduced BundleMap as an abstraction that encapsulates src -> dest mapping in native app projects. This will enable other parts of the logic (e.g. artifact processors) to query the mapping in a much cleaner way. There are some changes in behaviour introduced as part of this change, most notably enforcing that all src & dest mappings are relative paths.
* New logic is fully unit tested, including as many corner cases in the contract as I could think of
* Verified the previous logic manually before capturing the corner cases
* Verified the implementation by running `snow app bundle` manually

Introduce BundleMap to encapsulate artifact path mappings

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/constants.py
src/snowflake/cli/plugins/nativeapp/run_processor.py
tests/nativeapp/test_run_processor.py
tests_integration/nativeapp/test_version.py

`NativeAppRunProcessor.get_existing_version_info` rewritten to return the most-recent patch row when trying to get information about a specific version.
A new integration test was added to ensure that 3 patches can be added to a version through the CLI.

Fix creation of the 3rd+ patch on an app pkg version

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/common_flags.py
src/snowflake/cli/plugins/nativeapp/version/commands.py
tests/__snapshots__/test_help_messages.ambr

* I've added or updated integration tests to verify correctness of my new code.
Fixing `InteractiveOption` to default to `is_tty_interactive()` instead of `False`.
Also added the `--no-interactive` flag to be able to turn prompting off in an interactive shell.
Running `snow app teardown` in different combinations in a TTY shell:
|Command|Behavior|
|---|---|
|`snow app teardown`|Prompt|
|`snow app teardown --interactive`|Prompt|
|`snow app teardown --no-interactive`|No prompt|
Before the change:
|Command|Behavior|
|---|---|
|`snow app teardown`|No prompt|
|`snow app teardown --interactive`|Prompt|

Fix default interactive flag

---

.gitignore
src/snowflake/cli/api/utils/models.py
tests/test_data/projects/sql_templating/snowflake.local.yml
tests/test_data/projects/sql_templating/snowflake.yml
tests/test_sql.py

Fix env merging of snowflake.yml and snowflake.local.yml
Before the change, if I have env section in both snowflake.yml and snowflake.local.yml, env of snowflake.local.yml will clobber all of the env section in snowflake.yml.
Expected behavior is to clobber only the env variables defined in snowflake.local.yml.
This PR fixes this.

Fix env merging of snowflake.yml and snowflake.local.yml

---

src/snowflake/cli/plugins/nativeapp/codegen/snowpark/callback_source.py.jinja
src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
tests/nativeapp/codegen/snowpark/__snapshots__/test_python_processor.ambr
tests/nativeapp/codegen/snowpark/test_python_processor.py

Sometimes the Snowpark library adds `snowflake-snowpark-python` as a package dependency, and sometimes it does not (e.g. for a UDF). A UDF does require this package, so modified the generation logic to include it regardless.
- Added unit tests
- Manually verified that this fixes the issue encountered in the sample app

Handle missing snowflake-snowpark-python package dependency

---

src/snowflake/cli/api/console/console.py
tests/api/console/test_cli_console_output.py

The current CliConsole isn't cleaned up on exceptions being thrown in the `yield`ed code. This causes the phase-tracking state to remain after the phase has ended.

Clean up phase state on exception

---

src/snowflake/cli/api/project/schemas/native_app/native_app.py
src/snowflake/cli/api/project/schemas/native_app/path_mapping.py
src/snowflake/cli/plugins/nativeapp/artifacts.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/nativeapp/test_artifacts.py
tests/project/__snapshots__/test_config.ambr
tests/project/test_config.py

Following the move to Pydantic to parse project definition files, the `ArtifactMapping` class became redundant, since `PathMapping` serves the same purpose. Additionally, new fields added to the `PathMapping` class were not present on the `ArtifactMapping` class, creating a divergence. This change eliminates the redundancy, and simplifies the `BundleMap` contract as a result.

Removed ArtifactMapping data class in favour of PathMapping

---

src/snowflake/cli/plugins/nativeapp/commands.py
tests/__snapshots__/test_help_messages.ambr
tests_integration/nativeapp/test_deploy.py
tests_integration/testing_utils/assertions/test_result_assertions.py

The `snow app deploy` command accidentally disabled the use of `--no-recursive` because it includes a shorthand notation (`-r`) for the `--recursive` flag, which disabled the default flag handling behaviour in Typer. This change adds back the `--no-recursive` flag.
In addition to automated tests, verified that `--no-recursive` and `--recursive/-r` have the expected behaviour by executing various `deploy` commands on a sample app with local changes. Verified the error messages and stage status after each one.

[SNOW-1456015] Add support for `snow app deploy --no-recursive`

---

src/snowflake/cli/plugins/nativeapp/codegen/snowpark/extension_function_utils.py
tests/nativeapp/codegen/snowpark/__snapshots__/test_extension_function_utils.ambr
tests/nativeapp/codegen/snowpark/test_extension_function_utils.py

UDTF/UDAF require annotated classes as handlers. These handlers also need to be deannotated during the bundle phase, otherwise the Python code will not work in a Snowpark cloud environment. This change generalizes the deannotation logic to handle both function and class definitions.
- Updated unit tests to capture the new behaviour
- Manually verified the updated snapshots to make sure the behaviour was as intended
- Manually verified the change with a representative sample app
- Integ tests for Snowpark annotation processing are WIP and will be covered in a subsequent PR.

[SNOW-1465370] Support deannotating class definitions

---

src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
tests/nativeapp/codegen/snowpark/__snapshots__/test_python_processor.ambr

The Snowpark library sometimes appends its current version to the reported package dependencies. This is too strict for native apps, since they are expected to outlast Snowpark library upgrades. This change normalizes the Snowpark library package and removes that version if it's present. In the case where a user specified that version, we'd strip it as well, but arguably that is correct behaviour for this specific package due to strict backwards compatibility requirements.

[SNOW-1465372] Strip version numbers from the Snowpark lib during codegen

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
src/snowflake/cli/plugins/nativeapp/run_processor.py
src/snowflake/cli/plugins/nativeapp/version/commands.py
src/snowflake/cli/plugins/nativeapp/version/version_processor.py
tests/conftest.py
tests/nativeapp/fixtures.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_run_processor.py
tests/nativeapp/test_version_create_processor.py

This is a pure refactoring that is intended to prepare for a future code change. The general idea is that whenever we perform a bundle operation, we should propagate the BundleMap produced to the deployment logic so that it can be queried. This will be useful when trying to reason about changes files (during the diff operation) later on. Currently the bundle map is only required when specific paths are deployed. With this change, it's always a requirement argument.
- Updated the existing tests for the API change. However, since the bundle map itself is not used yet outside of the current logic that requires it, no new tests need to be added just yet.
- …

Propagate bundle map to all uses of the deployment logic

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/snowpark/common.py
tests/snowpark/test_function.py
tests/snowpark/test_procedure.py
tests_integration/test_snowpark.py
tests_integration/testing_utils/snowpark_utils.py

Added `copy grants` when deploying a function/procedure, to make sure that none of the privileges will be lost during replace

Copy grants while deploying snowpark functions and procedures

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/artifacts.py
tests/nativeapp/test_artifacts.py
tests_integration/nativeapp/test_bundle.py

Artifact rules could allow artifacts to be clobbered in certain cases. This change introduces two fixes that, combined, prevent these invalid rules from being accepted. First, additional checks are introduced to verify overlap between rules. Second, in order to make sure valid cases are processed correctly, the logic has been modified to keep track of individual insertion order for (src, dest) pairs. This way, we can guarantee that the deploy root will contain the correct files after the bundle step.
- Added unit tests to cover the new behaviour
- Manually invoked the CLI using the cases fixed here to verify the deploy root directory. Some of the behaviour that becomes allowed as part of this change will …

Prevent accidentally clobbering artifacts in native app projects

---

RELEASE-NOTES.md
src/snowflake/cli/api/identifiers.py
src/snowflake/cli/api/project/util.py
src/snowflake/cli/plugins/connection/util.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/api/test_fqn.py
tests/test_utils.py

Added an `identifier_for_url` utility which, combined with `make_snowsight_url`, allows us to build URLs based on quoted identifiers that use esoteric characters (like spaces). I have tested that these URLs are successfully resolved by Snowsight when the application is looked up:
```
% snow app init --name 'My ()Friendly() App' my_friendly_app
% cd my_friendly_app
% snow app run
[...]
https://app.snowflake.com/<redacted>/<redacted>/#/apps/application/My%20()Friendly()%20App_cgorrie
% snow app open
% snow app teardown
```

URLencode paths for snowsight URLs

---

src/snowflake/cli/plugins/nativeapp/codegen/snowpark/callback_source.py.jinja

This is a short-term fix for a blocking bug during setup script generation on Windows. Since the paths are not correctly escape, any '\' character is treated as an escape sequence, and the generation step fails. This fix will unblock 2.5.0 with minimal risk. We'll work on a better fix for the next patch release, or the next major release, whichever comes first.
Manually tested this fix on Windows. Verified that MacOS still works.

Temporarily fix handing of python file paths on Windows during Snowpark decorator processing

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/artifacts.py
src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
src/snowflake/cli/plugins/nativeapp/utils.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_artifacts.py
tests_integration/nativeapp/test_deploy.py

`snow app deploy`, when invoked with directories, current a matching artifact deployment rule for each parameter. This is not very intuitive. For example, when a user specifies:
```
- src: app/*
- dest: ./
```
in their `snowflake.yml`, `snow app deploy -r app` results in an error. This change makes the command deploy all files that have been changed within the specified directory instead.

[SNOW-1371918] Make snow app deploy behave more intuitively

---

RELEASE-NOTES.md
src/snowflake/cli/api/project/schemas/streamlit/streamlit.py
src/snowflake/cli/plugins/streamlit/commands.py
src/snowflake/cli/plugins/streamlit/manager.py
tests/project/__snapshots__/test_config.ambr
tests/streamlit/test_commands.py
tests/test_data/projects/example_streamlit/snowflake.yml
tests_integration/test_data/projects/streamlit/snowflake.yml
tests_integration/test_streamlit.py

Add support for `title` name in Streamlit definition.

Add title option for Streamlit definition

---

src/snowflake/cli/plugins/nativeapp/teardown_processor.py

The [no-whitespace diff](https://github.com/snowflakedb/snowflake-cli/pull/1214/files?w=1) can be useful to simplify reviewing this PR
* N/A I've described my changes in the section below.
Small code cleanup in `NativeAppTeardownProcessor.drop_application` and related functions to make future PR diffs look cleaner:
- Fixed incorrect type annotation
- Removed redundant `if interactive:` check that was already within an `elif interactive:` block
- Simplified prompt response check using `lower()`
- Simplified logic around prompting the user for drop confirmation when the …

[SNOW-1486485] Small cleanup to `drop_application`

---

src/snowflake/cli/api/utils/definition_rendering.py
src/snowflake/cli/api/utils/models.py
tests/api/utils/test_definition_rendering.py

Fix bugs related to env section of project definition file:
- Verified that env section is a yaml mapping.
- Verified that each env variable only contains scalar.
- Fixed a Windows bug related to case sensitivity, affecting sql commands only: Because we are copying os.environ to a dict, all Windows env variables become uppercase, forcing windows users to always use uppercase to reference their env variables, even if they defined them as lowercase on windows (Windows env variables are case insensitive).
To reproduce on Windows Powershell:
```
$env:test='test_value'
"select '&{ ctx.env.test }'" # this will result in an error.
```

Fix bugs with templating env section, and case sensitivity on Windows

---

src/snowflake/cli/api/cli_global_context.py
src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/app/telemetry.py
src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/version/commands.py
src/snowflake/cli/plugins/snowpark/commands.py
src/snowflake/cli/plugins/streamlit/commands.py
test_external_plugins/multilingual_hello_command_group/src/snowflakecli/test_plugins/multilingual_hello/commands.py
tests/app/test_telemetry.py

Added `definition_version` information in telemetry dict. This required to change `cli_context.project_definition` to be a full project definition instead of streamlit/snowpark/native_app section.

Add project definition version to telemetry

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/teardown_processor.py
tests/nativeapp/test_teardown_processor.py
tests_integration/nativeapp/test_teardown.py

If we find that the app isn't "owned" by the CLI (i.e. the object's comment isn't what we expect it to be), and the user says that they don't want to drop that app, abort the teardown since dropping the package afterwards would leave the app orphaned and non-functional.
No need to handle `--force` any differently since passing `--force` forces dropping the app anyways. With the current CLI flags, it's no longer possible to create orphan apps.
Denying the drop:
Forcing the drop:

[SNOW-1362197] Abort teardown if we don't drop application

---

src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py

On windows, there is currently a bug where appending relative file paths to a sql file that will be uploaded to a Snowflake stage is done incorrectly. 
E.g. if a file `__generated.sql` exists in a path `some\path\__generated\__generated.sql`, then the correct string to append to the sql file should be `EXECUTE IMMEDIATE FROM '/__generated/__generated.sql';`, but the bug currently causes this: `EXECUTE IMMEDIATE FROM '/__generated\__generated.sql';`. This PR is to correct the bug.

[NADE][Bugfix] Convert to stagepaths before writing to SQL files

---

.github/pull_request_template.md

We have had a few misses and near misses on Windows lately. I think it's a good idea to call out Windows testing explicitly in PRs. Submitters should of course continue to use judgement, as always. Windows-specific may not apply to all PRs, but it's a good reminder to think about the blast radius of a change on different operating systems.

Make windows an explicit check in PR templates

---

RELEASE-NOTES.md
src/snowflake/cli/api/sql_execution.py
src/snowflake/cli/app/printing.py
src/snowflake/cli/plugins/sql/manager.py
tests/object/__snapshots__/test_object.ambr
tests/output/test_format_silent_enforcement.py
tests/output/test_printing.py
tests/stage/__snapshots__/test_stage.ambr
tests/test_sql.py
tests_e2e/test_error_handling.py
tests_integration/test_sql.py

#1145 reported that query text is not printed until query is executed. I changed this by using `VerboseCursor` in `snow sql` command. This changes output of other commands (removes printing queries). I think this a good changes because we don't need to print queries for commands like `snow stage copy`.

Introduce VerboseCursor for printing queries before execution

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/manager.py
tests/nativeapp/test_manager.py

Since `snow app validate` throws away the scratch stage every time, the diff will always show that all files are being uploaded, which isn't necessary to show to the user in this case.
Before:
After:
Validation on `snow app bundle` (and `snow app run`) still shows the diff, since it uses the app's main stage:
Not adding tests since
1. It's a simple change
2. The mocking required to get unit tests working also mocks out the call to `sync_deploy_root_with_stage`, which is where `print_diff_to_console` is called
3. In integration tests, `capsys` can't capture `cc.message`. I'm not sure why but now's not the time to investigate

SNOW-1509249 Hide diff output when running `snow app validate`

---

RELEASE-NOTES.md
src/snowflake/cli/api/cli_global_context.py
src/snowflake/cli/api/commands/decorators.py
src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/api/commands/snow_typer.py
src/snowflake/cli/api/commands/typer_pre_execute.py
src/snowflake/cli/api/project/definition.py
src/snowflake/cli/api/project/definition_manager.py
src/snowflake/cli/api/project/schemas/project_definition.py
src/snowflake/cli/api/utils/definition_rendering.py
src/snowflake/cli/api/utils/models.py
src/snowflake/cli/api/utils/rendering.py
src/snowflake/cli/plugins/nativeapp/init.py
src/snowflake/cli/plugins/sql/commands.py
tests/__snapshots__/test_help_messages.ambr
tests/__snapshots__/test_sql.ambr
tests/api/utils/test_definition_rendering.py
tests/api/utils/test_rendering.py
tests/project/test_definition_manager.py
tests_integration/nativeapp/test_project_templating.py
tests_integration/test_sql_templating.py

Add support for CLI argument --env to allow users to overwrite env variables for templating.
User can provide multiple --env variables (e.g. --env x=1 --env y=a)
User can set empty variable (--env x=) or (--env x='')
Order of template resolution priority:
1) --env vars from cli
2) os env variables
3) env variables defined in project definition file.
This does not alter environment variables.

Add support for --env overrides from command line for templating

---

RELEASE-NOTES.md
src/snowflake/cli/api/project/errors.py
src/snowflake/cli/api/project/schemas/project_definition.py
src/snowflake/cli/api/project/schemas/updatable_model.py
src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
tests/nativeapp/test_post_deploy.py
tests/project/test_config.py

…er up to avoid Pydantic Union issue
1) Improved output of Pydantic validation:
BEFORE:
```
An unexpected exception occurred. Use --debug option to see the traceback. Exception message:
During evaluation of NativeApp in project definition following errors were encountered:
Your project definition is missing following fields: ('name',)
Your project definition is missing following fields: ('artifacts',)
Extra inputs are not permitted. You provided field '('extra',)' with value 'extrafieldvalue' that is not supported in given version.
```
AFTER:
```
╭─ Error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ During evaluation of ProjectDefinition in project definition following errors were encountered: …
```

Improve message for Pydantic model errors and move exception translation up to fix Pydantic Union issue.

---

RELEASE-NOTES.md
src/snowflake/cli/api/utils/definition_rendering.py
tests/api/utils/test_definition_rendering.py

Add warning when templating is used in v1
- we try to parse the template variables, if we find any, we warn.
- if Jinja throws an error, it means templating Syntax was attempted, but was not fully correct. We will also warn in that case.

Add warning when templating is used in v1

---

src/snowflake/cli/plugins/nativeapp/run_processor.py
tests/nativeapp/test_run_processor.py

Previously, `_create_dev_app` and `upgrade_app` duplicated a lot of each others' code. This refactor merges the two codepaths and introduces the `SameAccountInstallMethod` class to encapsulate some of the per-installation-type logic.

De-dupe app create / upgrade path in NativeAppRunProcessor

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/exceptions.py
src/snowflake/cli/plugins/nativeapp/run_processor.py
tests/nativeapp/test_run_processor.py
tests_integration/nativeapp/test_init_run.py

Previously, attempts to `snow app run` when the application object already exists but was installed from a version (e.g via `--version` or `--from-release-directive`) would fail with an error. Now, we hook into the existing `drop_application_before_upgrade` logic and allow cross-upgrades as we already could in the other direction (unversioned to versioned).

Allow cross-upgrade to unversioned mode in "snow app run"

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/exceptions.py
src/snowflake/cli/plugins/nativeapp/teardown_processor.py
tests/nativeapp/test_teardown_processor.py
tests_integration/nativeapp/test_init_run.py
tests_integration/nativeapp/test_teardown.py

`snow app teardown --force` now skips the version check. This allows users to get out of a dead end where they want to drop an application package where they've set the default release directive.

app teardown --force skips version check

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/nativeapp/version/version_processor.py
tests/nativeapp/test_version_create_processor.py
tests_integration/nativeapp/__snapshots__/test_version.ambr
tests_integration/nativeapp/test_version.py

Prompts the user when running `snow app version create` against a package that was not created by the CLI. The standard `--interactive/--no-interactive` and `--force` flags apply as usual.

Allow adding a version to a package without CLI magic comment

---

RELEASE-NOTES.md
src/snowflake/cli/api/rest_api.py
src/snowflake/cli/plugins/object/manager.py
tests/api/test_rest_api.py
tests_integration/test_object.py

More detailed error detection while determining CREATE endpoints url

Snow 1533042 create error handling fix

---

tests/nativeapp/codegen/test_sandbox.py
tests/nativeapp/test_artifacts.py
tests/nativeapp/test_init.py
tests/test_zipper.py

Updating more unit tests to work on Windows. These ones were concerned with differences between venvs on Unix vs Windows. Some tests also just passed when enabled, and others use symlinks so they remain disabled at the test level on Windows.

[SNOW-1528866] Re-enable some unit tests on Windows (2/N)

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py
tests/nativeapp/test_v2_to_v1.py
tests_integration/nativeapp/test_open.py
tests_integration/test_data/projects/napp_init_v1/app/README.md
tests_integration/test_data/projects/napp_init_v1/app/manifest.yml
tests_integration/test_data/projects/napp_init_v1/app/setup_script.sql
tests_integration/test_data/projects/napp_init_v1/snowflake.yml
tests_integration/test_data/projects/napp_init_v2/app/README.md
tests_integration/test_data/projects/napp_init_v2/app/manifest.yml
tests_integration/test_data/projects/napp_init_v2/app/setup_script.sql
tests_integration/test_data/projects/napp_init_v2/snowflake.yml

1. Created the `@nativeapp_definition_v2_to_v1` command decorator that attempts to convert project definition v2 to v1.
2. Added this decorator to the `snow app open` command.
The conversion logic is minimalistic: only what's needed for the `open` command. The following PRs will add support for the remaining commands.
Cloned a new NA project, rewrote `snowflake.yml` with v2 syntax, and verified `snow app open` opens the same URL:
v1:
```
$ snow app init pdfv2-open && cd pdfv2-open
$ snow app run
$ cat snowflake.yml
$ snow app open
```
```yml
definition_version: 1
native_app:
name: pdfv2_open
source_stage: app_src.stage
artifacts:
- src: app/* …
```

Support project definition v2 in "snow app open"

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/stage/diff.py
tests/stage/test_diff.py

Some stage storage backends (e.g. Azure) do not calculate md5sums automatically for multi-part file uploads. As such, these storage backends will return `NULL` for the md5 column. This PR ensures we do not error out and instead treat these files as modified.

Handle null md5s when given by storage backend

---

RELEASE-NOTES.md
src/snowflake/cli/plugins/connection/util.py
src/snowflake/cli/plugins/streamlit/manager.py
tests/test_utils.py

Use `SYSTEM$ALLOWLIST()` to determine the regioned host if the user's connection parameters have given us a regionless one. This allows us to return the correct context path part for the Snowsight URLs we generate.

Support regionless host URLs

---

src/snowflake/cli/api/output/types.py
src/snowflake/cli/app/printing.py
tests/output/test_printing.py

As part of implementing `snow app events -f`, we want to be able to stream messages indefinitely. This PR allows commands return a `StreamResult`, which wraps a generator of `CommandResult` objects. When we print a `StreamResult`, we iterate over all of its values and pass them individually through the same printing process.
An example use-case (some code omitted):
```python
@app.command("events", requires_connection=True)
def app_events(**options):
"""Fetches events for this app from the event table configured in Snowflake."""
manager = NativeAppManager(...)
def g():
for event in manager.get_events():
yield ObjectResult(event)
return StreamResult(g())
```
This generator-based implementation will allow us to make this command poll for events periodically, yielding new result objects for …

Allow commands to return multiple results as a stream

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/nativeapp/test_manager.py
tests_integration/nativeapp/test_events.py

Fetches events from the account event table (See #1337). This does not implement filtering, timeboxing, or limiting output (these will come in a followup).
Regular output prints the messages as a log stream, including any ASCII control codes:
JSON output prints each message as individual JSON values:
This can then be piped to `jq` or equivalent:

SNOW-1544013 Fetch events for app

---

src/snowflake/cli/api/cli_global_context.py
tests/testing_utils/fixtures.py

Before each test we reload few modules but we missed one module. We had 2 different CONFIG_MANAGER objects, when we were sending the telemetry, we were using "old" CONFIG_MANAGER with default config.toml.

Added connectors log_configuration module to reload

---

src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/app/dev/docs/templates/usage.rst.jinja2
tests/__snapshots__/test_docs_generation_output.ambr
tests/test_docs_generation_output.py

* modify template to add default values to generated flags and arguments
* change `--diag-log-path` implementation, so it's default value (tempdir path) is not visible on the output
* add unit test

Add default values to generated docs

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_manager.py

Adds `--since` and `--until` flags to restrict the time range for events. The query is updated to compare the `timestamp` column against the current time minus an `interval` specified by the user: https://docs.snowflake.com/en/sql-reference/data-types-datetime#interval-constants

SNOW-1544013 Add interval filtering to `snow app events`

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_manager.py
tests_integration/nativeapp/test_events.py

Adds `--first` and `--last` parameters to `snow app events`. The two parameters are mutually exclusive to avoid generating a query that would return discontinuous results.
This required updating the query to sort in descending order to limit to the last N events, then re-sort in ascending order for printing and to limit to the first M events.

SNOW-1544013 Add `--first` and `--last` to `snow app events`

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_manager.py
tests_integration/nativeapp/test_events.py

Adds additional filters to allow devs to choose the type and source of the events they want to see. `--type` is used to choose between logs, spans, and span events, and `--scope` is used to filter on the event scope (e.g. the logger class/name in the case of logs).

Add `--type` and `--scope` filters

---

src/snowflake/cli/plugins/nativeapp/artifacts.py
src/snowflake/cli/plugins/nativeapp/bundle_context.py
src/snowflake/cli/plugins/nativeapp/codegen/artifact_processor.py
src/snowflake/cli/plugins/nativeapp/codegen/compiler.py
src/snowflake/cli/plugins/nativeapp/codegen/setup/native_app_setup_processor.py
src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
src/snowflake/cli/plugins/nativeapp/manager.py
src/snowflake/cli/plugins/nativeapp/project_model.py
tests/nativeapp/codegen/snowpark/test_python_processor.py
tests/nativeapp/codegen/test_compiler.py
tests/nativeapp/test_artifacts.py
tests/nativeapp/test_project_model.py

* I've added or updated integration tests to verify correctness of my new code.
Instead of passing `NativeAppCompiler` the entire project definition object (via `NativeAppProjectModel`), we're passing it now the specific parameters it needs, grouped together as `BundleContext`.
The main reason for this is the upcoming support for project definition v2, which has significantly different structure (it's not enough to pass the entire definition object, we also need to know which entity is being bundled, its dependencies, etc.).

Decouple project definition object from artifact processors

---

src/snowflake/cli/plugins/nativeapp/commands.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_manager.py
tests_integration/nativeapp/test_events.py

Adds `--follow` flag to `snow app events` to enable live-tail of events. The command will poll the `get_events` function every 10 seconds (by default, can be changed with `--follow-interval`), printing new rows on each iteration.
The way we detect new events is to make a second query filtering on rows where the `timestamp >=` the timestamp of the last row from the old results. The bound needs to be inclusive since there could be new events with the same timestamp in the new results (i.e. the `timestamp` column isn't necessarily monotonic). Since the bound is inclusive, the first few events from the new results would be the same events as the last few events of the old results, which means we need to only print the net-new rows from the …

Add `--follow` to `snow app events`

---

tests/testing_utils/fixtures.py
tests_integration/config/world_readable.toml
tests_integration/conftest.py
tests_integration/test_config.py

Prevents the warnings about file permissions in tests:
```
/home/runner/.local/share/hatch/env/virtual/snowflake-cli-labs/M-xJJ0Mq/integration/lib/python3.10/site-packages/snowflake/connector/config_manager.py:351: UserWarning: Bad owner or permissions on /home/runner/work/snowflake-cli/snowflake-cli/tests_integration/config/plugin_tests/override_plugin_config.toml.
* To change owner, run `chown $USER "/home/runner/work/snowflake-cli/snowflake-cli/tests_integration/config/plugin_tests/override_plugin_config.toml"`.
* To restrict permissions, run …
```

Set test config file mode to 600 to prevent warnings

---

src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/api/project/schemas/updatable_model.py

Fixes warnings by updating uses of deprecated code:
- Fixes a warning from `click` that `autocompletion` is deprecated:
> DeprecationWarning: 'autocompletion' is renamed to 'shell_complete'. The old name is deprecated and will be removed in Click 8.1. See the docs about 'Parameter' for information about new behavior.
_typer_param_setup_autocompletion_compat(self, autocompletion=autocompletion)
The type signature of `shell_complete` is a little different but we're not using any of it anyways:
- Fixes a warning from `pydantic` about a deprecated pattern:
> …

SNOW-1571918 Update deprecated usages to recommended ones

---

.github/workflows/test_trusted.yaml
pyproject.toml
scripts/run_tests_with_retry.py

Integration tests have gotten flaky recently, mostly due to 504 timeouts from Snowflake. Since this isn't limited to a specific test, we can't flag it as `@flaky`, `@retry`, etc. This PR introduces a cross-platform script that will automatically re-run pytest with `--last-failed` so that any tests that fail get one more try. If they pass on the retry, they were most likely flaky; if they fail again, they were most likely not.
In a future PR, I'd like to start …

Retry integration test failures automatically

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_manager.py

Adds `--consumer-app-hash` to the `snow app events` command to distinguish between multiple app installations in the same account.

SNOW-1623352 Add option to pass app installation hash

---

src/snowflake/cli/_plugins/nativeapp/project_model.py
src/snowflake/cli/api/project/definition.py
tests/nativeapp/test_project_model.py
tests_integration/nativeapp/test_deploy.py
tests_integration/nativeapp/test_init_run.py

Prerequisite for #1437. After discussing in-person, we decided to not overwrite the `USER` environment variable in tests and instead add a new `SNOWFLAKE_CLI_TEST_RESOURCE_SUFFIX` env var that will be appended to app package and app identifiers. In #1437, we'll use this variable to generate unique names for these resources so they don't clash during concurrent tests.

Append SNOWFLAKE_CLI_TEST_RESOURCE_SUFFIX value to app and package name

---

src/snowflake/cli/_plugins/nativeapp/project_model.py
src/snowflake/cli/api/project/schemas/entities/application_entity_model.py
src/snowflake/cli/api/project/schemas/entities/application_package_entity_model.py
src/snowflake/cli/api/project/schemas/native_app/application.py
src/snowflake/cli/api/project/schemas/native_app/package.py
src/snowflake/cli/api/project/schemas/updatable_model.py
src/snowflake/cli/api/project/util.py
src/snowflake/cli/api/utils/definition_rendering.py
tests/api/utils/test_definition_rendering.py
tests/nativeapp/test_project_model.py
tests/test_data/projects/integration_external_v2/package/001-shared.sql
tests/test_data/projects/integration_external_v2/package/002-shared.sql
tests/test_data/projects/integration_templated_v2/package/001-shared.sql
tests/test_data/projects/integration_templated_v2/package/002-shared.sql
tests/test_data/projects/integration_v2/package/001-shared.sql
tests/test_data/projects/integration_v2/package/002-shared.sql
tests_integration/conftest.py
tests_integration/nativeapp/test_bundle.py
tests_integration/nativeapp/test_debug_mode.py
tests_integration/nativeapp/test_deploy.py
tests_integration/nativeapp/test_events.py
tests_integration/nativeapp/test_init_run.py
tests_integration/nativeapp/test_large_upload.py
tests_integration/nativeapp/test_open.py
tests_integration/nativeapp/test_post_deploy.py
tests_integration/nativeapp/test_project_templating.py
tests_integration/nativeapp/test_teardown.py
tests_integration/nativeapp/test_validate.py
tests_integration/nativeapp/test_version.py

Adds the current test name as a suffix on created apps and packages so we can tell which resources are created by which test. The method chosen to inject the name removes the need to pass `env=TEST_ENV` when calling `runner.invoke` and also fixes a bug that was introduced in #1396 due to the use of `--dist-worksteal` and the `TEST_ENV` being a module global (it was possible for a test to drop a resource used by another test concurrently because all tests in a …

SNOW-1623250 Add current test name to test resource env var in tests

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/run_processor.py
tests/nativeapp/test_run_processor.py

When warnings are returned by CREATE APPLICATION or UPGRADE APPLICATION, show them using `cc.warning` as well as an extra line break to draw visual attention to the warnings.

Print warnings on CREATE or UPGRADE

---

tests_integration/nativeapp/conftest.py
tests_integration/nativeapp/test_bundle.py
tests_integration/nativeapp/test_debug_mode.py
tests_integration/nativeapp/test_deploy.py
tests_integration/nativeapp/test_events.py
tests_integration/nativeapp/test_init_run.py
tests_integration/nativeapp/test_large_upload.py
tests_integration/nativeapp/test_open.py
tests_integration/nativeapp/test_post_deploy.py
tests_integration/nativeapp/test_project_templating.py
tests_integration/nativeapp/test_teardown.py
tests_integration/nativeapp/test_validate.py
tests_integration/nativeapp/test_version.py

Changes `with project_directory()` to `with nativeapp_project_directory()`, which automatically runs `snow app teardown` before exiting the project. This allows us to remove the `try`/`finally` in most tests. For tests that were using `with pushd(test_project)`, this has been changed to `with nativeapp_teardown()`, which is what `with nativeapp_project_directory()` uses under the hood.

SNOW-1636849 Auto-teardown Native App in integration tests

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/version/version_processor.py
tests/nativeapp/test_version_create_processor.py
tests/nativeapp/test_version_drop_processor.py

When running `snow app version create` and `snow app version drop`, wrap the version in `to_identifier()` so users don't have to specify the quotes around version names that aren't valid identifiers. If the name is already quoted, `to_identifier()` doesn't do anything.

SNOW-1621834 Cast version to identifier when creating/dropping app versions

---

src/snowflake/cli/api/project/errors.py
src/snowflake/cli/plugins/nativeapp/manager.py
tests/nativeapp/test_post_deploy_for_app.py
tests/nativeapp/test_post_deploy_for_package.py

Fix 1: backslash path in Windows for sql scripts
Before, you can only specify native app sql script to run with forward slashes.
Backward slashes were causing issues with Jinja2. By using as_posix(), we ensure that Jinja2 can parse the paths
Fix 2: fix pydantic reporting which was not working when there is an array in the path:
Example: native_app.application.post_deploy[0].sql_script

Support backslash for windows path

---

src/snowflake/cli/api/project/errors.py

When error location in Pydantic contains indices, it crashes with an error that can't be decyphired easily.
It crashes trying to join a mix of string and integers ".".join(e["loc"]).
This fixes it to report integers nicely: e.g. key1[1].key2 
WIll add unit test as a follow up (to unblock the release)

Fix integer indices in error reporting

---

src/snowflake/cli/_plugins/nativeapp/codegen/compiler.py
src/snowflake/cli/_plugins/nativeapp/codegen/setup/native_app_setup_processor.py
src/snowflake/cli/_plugins/nativeapp/codegen/setup/setup_driver.py.source
src/snowflake/cli/_plugins/nativeapp/codegen/snowpark/python_processor.py
tests/nativeapp/codegen/snowpark/test_python_processor.py

Updating the setup processor driver to match ToT in the snowflake.app package
Since the snowflake.app package is still private, this was tested manually using an env var override. Integ and E2E tests will be added when the feature is closer to PrPr.

Update setup processor according to new result schema

---

src/snowflake/cli/_plugins/streamlit/manager.py
tests/streamlit/test_commands.py
tests/test_data/projects/streamlit_empty_pages/environment.yml
tests/test_data/projects/streamlit_empty_pages/snowflake.yml

Added check in Streamlit to skip put on stage when directory is empty.

Skip empty pages directory when deploying streamlit

---

src/snowflake/cli/api/entities/application_package_entity.py
src/snowflake/cli/api/entities/utils.py
src/snowflake/cli/api/rendering/jinja.py
tests/nativeapp/test_post_deploy_for_app.py
tests/nativeapp/test_post_deploy_for_package.py

By supporting old and new templating syntax, we warn if both old syntax is used, and we error out if both old and new syntax is used at the same time in the same file.
The error messaging for these does not say which file is coming from.
In this PR I do some small refactor while adding the name of the file in the messaging.
I have already added this messaging to templating arbitrary files - this expands it to post_deploy scripts.

Improve error messages on SQL execution

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/git/manager.py
src/snowflake/cli/_plugins/stage/manager.py
tests_integration/__snapshots__/test_git.ambr
tests_integration/test_data/projects/stage_execute/ScriptInCamelCase.sql
tests_integration/test_git.py
tests_integration/test_object.py

...
Fix git execute was failing when the directory contained a character in upper case. 
Example:
```
(snowflake-cli-labs) (base) jvasquezrojas@V9P2792XJ5 snowflake-cli % snow git list-files "@jvasquez_repository/branches/dev/CICD/DB1/example.sql" -c integration                                            
+------------------------------------------------------------------------------------------------------------------------------------------------+
| name                                                  | size | md5  | sha1                                     | last_modified                 |
|-------------------------------------------------------+------+------+----------------------------------------- …
```

Fix git execute with upper letter in directory

---

src/snowflake/cli/_plugins/snowpark/commands.py
src/snowflake/cli/_plugins/streamlit/commands.py
src/snowflake/cli/_plugins/workspace/commands.py
src/snowflake/cli/api/project/definition_conversion.py
tests/project/test_project_definition_v2.py
tests/test_data/projects/migration_multiple_entities/app/README.md
tests/test_data/projects/migration_multiple_entities/app/manifest.yml
tests/test_data/projects/migration_multiple_entities/app/setup.sql
tests/test_data/projects/migration_multiple_entities/snowflake.yml
tests/workspace/__snapshots__/test_manager.ambr
tests/workspace/test_manager.py

* N/A I've described my changes in the release notes (covered by existing note).
Enables `snow ws migrate` to migrate a v1 or v1.1 Native App project file to v2. Doesn't support migrating package scripts since they use a different template syntax, we'll tackle those in a followup.

SNOW-1643030 Add Native App support to `snow ws migrate` command

---

src/snowflake/cli/_plugins/nativeapp/manager.py
src/snowflake/cli/api/entities/application_package_entity.py

Extracts the body of `ApplicationPackageEntity.action_bundle()` to a separate method and changes `NativeAppManager.build_bundle()` to use it too.

SNOW-1653357 Refactor build_bundle to use method in ApplicationPackageEntity

---

src/snowflake/cli/api/entities/utils.py
src/snowflake/cli/api/project/definition_conversion.py
tests/test_data/projects/migration_package_scripts/app/README.md
tests/test_data/projects/migration_package_scripts/app/manifest.yml
tests/test_data/projects/migration_package_scripts/app/setup.sql
tests/test_data/projects/migration_package_scripts/package_scripts/001.sql
tests/test_data/projects/migration_package_scripts/package_scripts/002.sql
tests/test_data/projects/migration_package_scripts/snowflake.yml
tests/workspace/test_manager.py

Use the [no-whitespace diff](https://github.com/snowflakedb/snowflake-cli/pull/1538/files?w=1) for an easier diff-viewing experience.
PDFv2 doesn't support package scripts, so we need to convert them to post-deploy hooks. Since package scripts use a different Jinja template syntax (`{{ }}` instead of `<% %>`), we need to convert the actual files as well.

SNOW-1643030 Convert package scripts to post-deploy hooks

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_v2_to_v1.py
tests_integration/nativeapp/conftest.py
tests_integration/nativeapp/test_init_run.py
tests_integration/test_data/projects/napp_init_v2_multiple_entities/app/README.md
tests_integration/test_data/projects/napp_init_v2_multiple_entities/app/manifest.yml
tests_integration/test_data/projects/napp_init_v2_multiple_entities/app/setup_script.sql
tests_integration/test_data/projects/napp_init_v2_multiple_entities/snowflake.yml

Use the [no-whitespace diff](https://github.com/snowflakedb/snowflake-cli/pull/1546/files?w=1) for a more pleasant diff-viewing experience
Adds `--package-entity-id` and `--app-entity-id` options to all commands that use `@nativeapp_definition_v2_to_v1` to allow us to handle v2 definitions that have multiple apps or packages in the old v1 commands.
The new logic will also attempt to determine which app or package to convert if it's non-ambiguous (i.e. there's only one entity of that type) and will infer the package to convert from the application entity's `target` field.

SNOW-1653909 Add options for choosing which entities to convert back to v1

---

src/snowflake/cli/_plugins/nativeapp/run_processor.py
src/snowflake/cli/_plugins/workspace/commands.py
src/snowflake/cli/_plugins/workspace/plugin_spec.py
src/snowflake/cli/api/entities/application_package_entity.py
src/snowflake/cli/api/entities/common.py
tests/workspace/test_application_package_entity.py
tests_integration/nativeapp/__snapshots__/test_version.ambr
tests_integration/nativeapp/test_version.py

Adds `snow ws version list` command to be invoked on an app package entity. Behaves the same as `snow app version list`.

Add `snow ws version list` command

---

src/snowflake/cli/_plugins/nativeapp/application_entity.py
tests_integration/nativeapp/test_post_deploy.py

Fix app role None with ws commands
- previously, it was resetting to None in getattr() command because getattr only defaults when the attribute doesn't exist, not when the attribute is None.

Fix app role None with ws commands

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py
src/snowflake/cli/_plugins/nativeapp/version/commands.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_v2_to_v1.py
tests/test_data/projects/integration_templated_v2/snowflake.yml
tests/test_data/projects/integration_v2/snowflake.yml
tests_integration/nativeapp/conftest.py
tests_integration/nativeapp/test_init_run.py
tests_integration/nativeapp/test_teardown.py

Use the [no-whitespace diff](https://github.com/snowflakedb/snowflake-cli/pull/1557/files?w=1) for a more pleasant diff-viewing experience
Followup to #1546 to fix a bug where it would complain if we had a PDv2 with multiple app entities for commands that didn't care about the app at all.
Also updates `snow app teardown` to me PDFv2-aware so we can teardown all the apps created from one package.

SNOW-1653909 If we can't find an app entity to convert, only fail if it's required, update `snow app teardown` to tear down multiple apps

---

src/snowflake/cli/_plugins/nativeapp/artifacts.py
src/snowflake/cli/_plugins/nativeapp/version/version_processor.py
tests/nativeapp/test_artifacts.py
tests_integration/nativeapp/test_version.py

Fixed a bug where versions read from a manifest file in `snow app create` could lead to a crash due to being parsed as numbers. Fixes SNOW-1653838.

Fix numerical version when reading from manifest file

---

src/snowflake/cli/_plugins/streamlit/streamlit_entity_model.py
tests/streamlit/__snapshots__/test_commands.ambr
tests/streamlit/test_commands.py
tests_integration/test_streamlit.py

Adds back 2.8 support for glob in streamlit. The support was limited to PUT behavior.  The 3.0 added pre-check for srtifacts which caused validation errors.

Bring back glob support in streamlit

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/application_entity.py
src/snowflake/cli/_plugins/nativeapp/application_package_entity.py
src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/manager.py
src/snowflake/cli/_plugins/nativeapp/policy.py
src/snowflake/cli/_plugins/nativeapp/run_processor.py
src/snowflake/cli/_plugins/workspace/commands.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_manager.py
tests/workspace/test_application_package_entity.py
tests_integration/nativeapp/test_deploy.py

...
Adds a prompt for when running `app deploy` or `ws deploy` (for a package entity) that was not created by the CLI.  
This behavior already exists for version commands.

Catch error on deploy for package with special comment

---

src/snowflake/cli/_plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py
tests/nativeapp/test_v2_to_v1.py

Fixes a bug where a command that doesn't use the app entity would show
```
More than one application entity exists in the project definition file, specify --app-entity-id to choose which one to operate on.
```
when there was more than one app entity in `snowflake.yml`. The new logic just ignores all the app entities since the command doesn't use it anyways.

Don't error on a PDFv2 with multiple entities if it's not required

---

src/snowflake/cli/_plugins/nativeapp/application_entity.py
src/snowflake/cli/_plugins/nativeapp/application_package_entity.py
src/snowflake/cli/_plugins/nativeapp/manager.py
src/snowflake/cli/_plugins/nativeapp/run_processor.py
src/snowflake/cli/_plugins/nativeapp/version/commands.py
src/snowflake/cli/_plugins/nativeapp/version/version_processor.py
src/snowflake/cli/_plugins/workspace/commands.py
src/snowflake/cli/api/entities/common.py
tests/nativeapp/test_run_processor.py
tests/nativeapp/test_version_create.py
tests/nativeapp/utils.py

Moves implementation of `snow app version create` to `ApplicationPackageEntity.version_drop` and wires it into `snow ws version create` too.

SNOW-1643309 Move version create to app package entity

---

tests_integration/testing_utils/assertions/test_result_assertions.py

Regexes should use raw strings since `\s` isn't a valid Python escape sequence.

Fix DeprecationWarning in tests

---

src/snowflake/cli/_plugins/helpers/commands.py
tests/helpers/__snapshots__/test_v1_to_v2.ambr

Fixes unwanted linebreak for long templated identifiers:

Don't break long lines when converting v1 to v2

---

tests/nativeapp/test_package_scripts.py

Switch some mocks of `NativeAppManager._execute_X` to mock `SqlExecutor.execute_X` instead. The rest are being removed in https://github.com/snowflakedb/snowflake-cli/pull/1616/files.

Remove NativeAppManager SQL mocks

---

src/snowflake/cli/_plugins/nativeapp/entities/application.py
src/snowflake/cli/_plugins/nativeapp/manager.py
src/snowflake/cli/_plugins/nativeapp/run_processor.py

Since `SqlExecutor` is now instantiated on-demand in the relevant entity methods, we no longer need to make `NativeAppManager` inherit from it. The only external change required was to move `get_snowsight_host` into `ApplicationEntity`.

Make NativeAppManager no longer inherit from SqlExecutionMixin

---

src/snowflake/cli/_plugins/helpers/commands.py
tests/helpers/__snapshots__/test_v1_to_v2.ambr

Stop alphabetizing dict keys in `snow helpers v1-to-v2`, to keep the converted PDFs to an opinionated order.

Don't sort keys when converting PDFv1 to v2

---

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/manager.py
tests/nativeapp/test_manager.py
tests/nativeapp/utils.py

Now that `ApplicationPackageEntity` has a static `deploy()` method, we can just call that instead of having to pass a callback from the `NativeAppManager` to deploy the app files to the scratch stage when doing setup script validation. There's a bit of a an explosion in required params, but it's temporary and it'll be cleaned up when the v1 commands are made to operate on v2 entities directly.

SNOW-1653357 Remove deploy_to_scratch_stage_fn() and call deploy() directly

---

src/snowflake/cli/_plugins/workspace/action_context.py
src/snowflake/cli/_plugins/workspace/manager.py
tests/workspace/test_application_package_entity.py

We have some commands, like `snow app bundle`/`snow ws bundle` that don't even need a connection, so let's defer connecting to Snowflake until it's actually needed by the particular action being run.
For now, all `snow ws` commands are still marked as requiring a connection, that will be fixed separately.

Defer fetching role and warehouse until they're needed

---

src/snowflake/cli/_plugins/helpers/commands.py
src/snowflake/cli/api/project/definition_manager.py
tests/helpers/test_v1_to_v2.py
tests/project/test_definition_manager.py
tests/test_data/projects/migration_local_yml/snowflake.local.yml
tests/test_data/projects/migration_local_yml/snowflake.yml

Fixes bug with `snow helpers v1-to-v2` if a `snowflake.local.yml` is present. Currently, the local file isn't renamed, so a v1 local can be overlaid onto a v2 main definition file after migration, which breaks subsequent commands. Since local overrides are no longer a desired feature in PDFv2, we don't convert them unless `--migrate-local-overrides` is used.

Disable snowflake.local.yml migration by default, add flag to enable it

---

src/snowflake/cli/api/project/definition_conversion.py
tests/helpers/test_v1_to_v2.py

Fixes the manifest not being found if it isn't explicitly mentioned as an artifact or as part of a glob when running `snow helpers v1-to-v2`.

Find deeply-nested manifest.yml when converting v1 to v2

---

src/snowflake/cli/_plugins/workspace/commands.py
tests/workspace/test_ws_dump.py

Quick `snow ws dump` internal command to show what a snowflake.yml file will render to after defaults, templates, and mixins.
v1:
```yml
definition_version: 1
native_app:
name: test
source_stage: app_src.stage
artifacts:
- src: app/*
dest: ./
```
```yml
definition_version: '1'
native_app:
name: test
artifacts:
- src: app/*
dest: ./
processors: []
bundle_root: output/bundle/
deploy_root: output/deploy/
generated_root: __generated/
source_stage: app_src.stage
scratch_stage: app_src.stage_snowflake_cli_scratch
package: null
application: null
snowpark: null
streamlit: null
```
v1.1:
```yml
definition_version: 1.1
native_app:
name: test
source_stage: app_src.stage
artifacts:
- src: app/*
dest: ./
```
```yml
definition_version: '1.1'
native_app:
name: test
artifacts:
- src: app/*
dest: ./ …
```

Add simple ws dump command to show final PDF model

---

scripts/packaging/build_binaries.sh
scripts/packaging/build_darwin_package.sh
scripts/packaging/macos/SnowflakeCLI.bash
scripts/packaging/macos/SnowflakeCLI.plist
scripts/packaging/macos/postinstall

[SNOW-1694005](https://snowflakecomputing.atlassian.net/browse/SNOW-1694005) 
Combined building binaries and pkg with pyinstaller.
Solved problem with signing multpile linked Python binaries
[SNOW-1694005]: https://snowflakecomputing.atlassian.net/browse/SNOW-1694005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNOW-1694005: MacOS binary signing

---

src/snowflake/cli/_plugins/nativeapp/v2_conversions/compat.py

No material changes, just extracting the entity finding logic into `_find_app_and_package_entities` and the Typer options into `APP_AND_PACKAGE_OPTIONS` slim the diff in #1635.

SNOW-1706990 Extract fields in compat module

---

src/snowflake/cli/api/cli_global_context.py
src/snowflake/cli/api/project/definition_conversion.py
tests/project/test_project_definition_v2.py

Extracted from #1667 to get separate CLI team codeowner review.
Allows converting a v1 definition to v2 only in-memory, without saving the resultant v2 definition to `snowflake.yml`. This will be used in a future decorator added in #1667 to allow v1 commands to operate natively on v2 entities by implicitly converting the definition.
Since the definition conversion process currently updates package script files in-place, we need a way to isolate those changes to a temp directory instead of touching the user's project directory. This is achieved by creating a tempdir to hold these conversions and by replacing the package script filenames in the project definition with absolute paths to those temp files, taking advantage of the (documented) fact that `Path(...) / "/tmp/foo"` ignores the …

Allow converting PDFv1 to PDFv2 in-memory only

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/v2_conversions/compat.py
tests_integration/nativeapp/test_bundle.py

We eventually want to remove `NativeAppManager` and `NativeAppProjectModel` since they're only thin wrappers around the v2 entities right now. Since the `snow app` commands can only operate on a single package or app at a time, we need to adapt the definition that the user gives us if it doesn't conform. This PR adds `@single_app_and_package()` decorator to be used on `snow app` commands to perform this conversion.
If the user gives us a v1 definition, it is implicitly converted to a v2 definition with `app` and `pkg` entities using the same conversion as `snow helpers v1-to-v2`. If the user gives us a v2 definition, it is searched for a single package entity and up to one app entity using the same logic as the current `@nativeapp_definition_v2_to_v1()` decorator, including disambiguating …

SNOW-1706990 Add decorator to extract a single app and package from a PDFv2

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/artifacts.py
src/snowflake/cli/_plugins/nativeapp/codegen/compiler.py
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/api/project/definition_conversion.py
tests/nativeapp/codegen/test_compiler.py
tests/nativeapp/test_artifacts.py
tests/workspace/test_application_package_entity.py

Subtle cwd-dependent bugs can creep in if we work with relative paths too much. Let's enforce that all paths used to initialize `BundleMap` and `NativeAppCompiler` should be absolute so there's no doubt about where files will be read from or written to. Paths to individual files within these roots are still allowed to be relative.

Enforce that paths used for BundleMap and NativeAppCompiler are always absolute

---

pyproject.toml
src/snowflake/cli/_plugins/snowpark/common.py
src/snowflake/cli/_plugins/snowpark/package/anaconda_packages.py
tests/snowpark/test_common.py
tests_integration/conftest.py
tests_integration/nativeapp/test_bundle.py
tests_integration/nativeapp/test_large_upload.py
tests_integration/test_snowpark.py

Adjusts the test to work consistently on CI and QA environments. Type conversion for snowpark was reversed: user input -> snowflake type.

Fix Snowpark type casting

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/v2_conversions/compat.py
tests_integration/nativeapp/test_feature_metrics.py

Makes `snow app deploy` operate natively on v2 entities, like `snow ws deploy`. Updates `@single_app_and_package` to keep the correct `ctx.env`.

SNOW-1706990 Convert `snow app deploy` to v2-native

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/entities/application.py
src/snowflake/cli/_plugins/nativeapp/manager.py
tests_integration/nativeapp/test_init_run.py

Converts `snow app run` to operate natively on v2 entities, like `snow ws deploy` on an app entity.

SNOW-1706990 Convert `snow app run` to v2-native

---

src/snowflake/cli/_plugins/nativeapp/artifacts.py
tests/nativeapp/test_artifacts.py

Fixed a bug identified by @sfc-gh-astus where the wrong message can be issued when a snowflake.yml file contains conflicting artifact rules.

Fixed error message in artifact logic

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/snowpark/commands.py
src/snowflake/cli/_plugins/snowpark/package/commands.py
src/snowflake/cli/_plugins/snowpark/package_utils.py
tests/snowpark/test_build.py
tests/snowpark/test_package.py
tests/test_utils.py
tests_integration/test_package.py
tests_integration/test_snowpark.py

Add pip error details to logs.
Small refactor of `download_unavailable_packages` (raise exception earlier, as all usages were immediately raising in case `succeded==False`)

Snow 1703629 log pip error message

---

RELEASE-NOTES.md

mraba/changes-from-v3.0.2: update release notes

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/v2_conversions/compat.py
src/snowflake/cli/_plugins/nativeapp/version/commands.py
tests_integration/nativeapp/conftest.py

Use the [no-whitespace diff](https://github.com/snowflakedb/snowflake-cli/pull/1709/files?w=1) for a more pleasant diff-viewing experience
Converts `snow app teardown` to remove its use of `NativeAppTeardownProcessor` by converting the v1 definition to v2. Renamed `@single_app_and_package` to `@force_project_definition_v2` and made `single_app_and_package` a flag which can be disabled to allow passing through a v2 definition that has multiple app/package entities in it.

SNOW-1706990 Make `snow app teardown` only operate on v2 entities

---

src/snowflake/cli/_app/telemetry.py
tests/app/test_telemetry.py

Add information if CLI was run in any of known CI environments.

Add CI usage to telemetry

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/git/commands.py
src/snowflake/cli/_plugins/stage/manager.py
src/snowflake/cli/api/identifiers.py
tests/api/test_fqn.py
tests/git/test_git_commands.py
tests/stage/test_stage.py
tests_integration/__snapshots__/test_git.ambr
tests_integration/test_git.py

Fix `snow git execute` for Python files:
1. Copy the files first to temporary stage to workaround missing Snow git feature
2. Strip leading and trailing quotes from input variables so the values are consistent between SQL and Python
3. Add support for temporary stage in `StageManager`

Fix snow git execute for Python files

---

src/snowflake/cli/_plugins/nativeapp/version/version_processor.py
tests/nativeapp/test_version_create.py

Updates version create tests to use `ApplicationPackageEntity` and removes `NativeAppVersionCreateProcessor`

SNOW-1706990 Remove NativeAppVersionCreateProcessor

---

src/snowflake/cli/_plugins/git/commands.py
src/snowflake/cli/_plugins/git/manager.py
src/snowflake/cli/_plugins/stage/commands.py
src/snowflake/cli/_plugins/stage/diff.py
src/snowflake/cli/_plugins/stage/manager.py
src/snowflake/cli/api/entities/utils.py
src/snowflake/cli/api/identifiers.py
src/snowflake/cli/api/stage_path.py
tests/git/__snapshots__/test_git_commands.ambr
tests/git/test_git_commands.py
tests/nativeapp/test_manager.py
tests/stage/test_diff.py
tests/stage/test_stage.py
tests/stage/test_stage_path.py
tests/streamlit/test_commands.py

1. Renames existing `StagePath` to `StagePathType` to avoid ambiguity
2. Introduce `StagePath` class representing a file on stage. This class offers `Path` like operations including `joinpath` or `parent` operations.
The next step of refactor will be removing of `StagePathParts` concepts and then moving query generation to `StagePath`.

Introduce StagePath for working with files on stages

---

src/snowflake/cli/_plugins/git/commands.py
tests/__snapshots__/test_help_messages.ambr

Adjust note in `snow git execute` help to point out that both sql and py files are supported.

Add python to git execute help

---

src/snowflake/cli/_plugins/nativeapp/v2_conversions/compat.py
src/snowflake/cli/api/cli_global_context.py
src/snowflake/cli/api/project/definition_conversion.py
tests/project/test_project_definition_v2.py
tests_integration/nativeapp/test_project_templating.py
tests_integration/test_data/projects/napp_templates_processors_v1/app/setup_script.sql
tests_integration/test_data/projects/napp_templates_processors_v2/app/setup_script.sql

When converting PDFv1 to PDFv2, we need to convert package scripts to post-deploy hooks, so we have to convert the `{{ package_name }}` template into the normal template syntax.
When converting using `snow helpers v1-to-v2`, we convert `{{ package_name }}` to `<% ctx.entities.pkg.identifier %>` since we know that the next time the CLI is run, the template context will be v2-based and that `ctx.entities.pkg.identifier` will be a valid reference.
When converting in-memory however, the template context is v1-based and since the conversion has to be transparent to the user (they could have other files with templates still using v1 references in it), we can't override the template context to v2, so `ctx.entities.pkg.identifier` is an invalid reference. 
Fortunately for in-memory conversions, …

Defer package script conversion until PDFv2 is loaded into Pydantic

---

src/snowflake/cli/_plugins/nativeapp/commands.py
tests_integration/nativeapp/test_diff.py

Fixes `snow app diff` crash by making it handle both kinds of identifiers (string and object)

Fix `snow app diff` with string identifier

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/commands.py

Removed the `snow app init` command, since it was disabled and hidden in 3.0.

Delete the hidden `snow app init` command

---

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
tests/nativeapp/fixtures.py
tests/nativeapp/test_application_package_entity.py
tests_common/conftest.py

The static and class methods on entities was intended as a stopgap to allow them to be called from `NativeAppManager` without an instance of the entity. Now that `NativeAppManager` is gone (#1749), we can get rid of the static and call the action on an instance instead. This also has the advantage of unit-testing the action methods, which were previously only run in integration tests.
This PR also adds some fixtures to create dummy entity instances, which will be useful in future unit tests (instead of needing to load a whole definition file).

SNOW-1706990 Remove static method for action_version_list

---

tests/nativeapp/test_manager.py

Adds custom IDs to the parametrization of `test_get_events` to make the test names cleaner and more meaningful.
Before (scroll right):
```bash
<Dir snowflake-cli>
<Package tests>
<Package nativeapp>
<Module test_manager.py>
<Function test_get_events[0-limit 0-10-limit 10-testorg-testacc-428cdba48b74dfbbb333d5ea2cc51a78ecc56ce2-resource_attributes:"snow.application.package.name" = 'APP_PKG' and resource_attributes:"snow.application.consumer.organization" = 'TESTORG' and resource_attributes:"snow.application.consumer.name" = 'TESTACC' and resource_attributes:"snow.database.hash" = '428cdba48b74dfbbb333d5ea2cc51a78ecc56ce2'-types0--scopes0--until2-and timestamp <= '2024-01-01 00:00:00'-1 hour-and timestamp >= sysdate() - interval '1 hour']>
<Function test_get_events[20-limit 20-0-limit …
```

Prettify test_get_events IDs

---

src/snowflake/cli/api/config.py
tests/test_config.py

Display warnings when permissions for config files are too wide.

SNOW-1754872: display warning on windows for too wide permissions

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/stage/manager.py
tests/stage/test_stage.py
tests_integration/__snapshots__/test_git.ambr
tests_integration/__snapshots__/test_stage.ambr
tests_integration/test_data/projects/stage_execute_without_requirements/script_template.py
tests_integration/test_git.py
tests_integration/test_stage.py

* Fix: Removed requirement of presence of `requirements.txt` file for Python code execution via `snow git execute` or `snow stage execute`. Now Python code without external requirements can be correctly executed without necessity to create an empty `requirements.txt` file.
* Explicit passing of snowpark session during registration and invocation of temporary stored procedures to avoid "Too many active sessions" errors in tests.
* Added integration tests and adjusted unit tests.

[SNOW-1758029] Removed necessity of requirements.txt for git execute

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_version_create.py
tests/nativeapp/utils.py

Updates `ApplicationPackageEntity` to make deploy and validation classmethods into instance methods, greatly simplifying the parameters being passed around.

SNOW-1758715 Convert app package deploy and validate to instance methods

---

src/snowflake/cli/_plugins/nativeapp/entities/application.py
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
tests/nativeapp/test_application_package_entity.py
tests/nativeapp/test_post_deploy_for_app.py
tests/nativeapp/test_post_deploy_for_package.py

Converts `execute_post_deploy_hooks` for both entities to instance methods. Removes `test_invalid_hook_type` since it's now impossible to pass an invalid hook since Pydantic will fail to validate the model object (and will also fail if trying to set `model.meta.post_deploy` to an invalid hook afterwards).

SNOW-1758715 Convert execute_post_deploy_hooks to instance method

---

test_external_plugins/broken_plugin/pyproject.toml
test_external_plugins/failing_plugin/pyproject.toml
test_external_plugins/multilingual_hello_command_group/pyproject.toml
test_external_plugins/override_build_in_command/pyproject.toml
test_external_plugins/snowpark_hello_single_command/pyproject.toml
tests_common/pycharm_debug.py
tests_e2e/__snapshots__/test_installation.ambr
tests_e2e/conftest.py

* Fixed `snow --help` e2e test.
* Bug reason: CLI was firstly installed in correct dev version but plugins which still required `snowflake-cli-labs` instead of `snowflake-cli` were able to find only officially released CLI versions and were overriding dev CLI with official CLI.
* Added `pycharm_debug.py` manual util to simplify debugging of tests (especially integration and e2e tests).
* Added `tests_common` as pytest plugin to e2e tests to make possible to run e2e tests locally.

Fixes and improvements in E2E tests

---

RELEASE-NOTES.md
src/snowflake/cli/api/config.py
tests/test_config.py
tests/testing_utils/fixtures.py

* Changed scope of unit tests' `test_snowcli_config` fixture from `session` to `function` to avoid side effects between tests.
* Added an unit test confirming the bug
* Bugfix in `config.py`. We were saving whole content of "conf file cache" to `config.toml`. Now we're saving connections to `connections.toml` if that file exists.
* Conditions:
* No connections in `config.toml`
* Only one connection in `connections.toml` (“dev” connection)
* Invoked command: `snow connection set-default "dev"`
* Incorrect behaviour:
* Default connection was changed correctly but “dev” connection details were copied from `connections.toml` to `config.toml`. User may don’t want to keep connection secrets in config.toml so IMO it looks like security issue.
* Reason:
* We were saving whole content of "conf …

[SNOW-1739737] BUGFIX: Setting a default connection copies the connection from connections.toml to config.toml

---

src/snowflake/cli/_plugins/nativeapp/entities/application.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_sf_sql_facade.py
tests/nativeapp/utils.py

Moves `application_objects_to_str()` out from the `ApplicationEntity` class to be a module-level function and `get_account_event_table()` to the SQL facade since they're not part of the public API of the entity

SNOW-1758715 Move small helper methods out of ApplicationEntity class

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/api/exceptions.py
tests_integration/nativeapp/test_events.py

The `--consumer-org` and `--consumer-account` flags must be used together, the error message was saying that they can't be used together.

Fix wrong error messaging in snow app events

---

src/snowflake/cli/_plugins/nativeapp/entities/application.py
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_run_processor.py

Adds properties to the native app entities to make usage of model fields a bit simpler and safer (especially the derived ones like paths).
For example, to get the package name, we can call `self.name` instead of `self._entity_model.fqn.name`.

Create shortcut properties for entity model fields

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/sql/commands.py
src/snowflake/cli/_plugins/sql/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/__snapshots__/test_sql.ambr
tests/test_sql.py

Fix for #1740 
Adds `--retain-comments` option to `snow sql` command

Add `--retain-comments` option to `snow sql`

---

tests_integration/spcs/test_services.py

This test has been timing out for the past few days, let's xfail it until we can debug why or the issue goes away

Mark test_job_services as xfail because it's timing out and blocking us

---

src/snowflake/cli/_plugins/nativeapp/entities/application.py
tests/nativeapp/test_run_processor.py

Just a small cleanup to remove callbacks that are no longer required since we can just call the instance methods. Also standardizes `is_interactive` to `interactive` since that one is more common in the rest of the codebase.

Remove callbacks in ApplicationEntity.action_deploy

---

src/snowflake/cli/_plugins/nativeapp/artifacts.py
src/snowflake/cli/_plugins/nativeapp/codegen/templates/templates_processor.py
src/snowflake/cli/api/project/definition_conversion.py
tests_integration/helpers/test_v1_to_v2.py

When running `snow helpers v1-to-v2`, the structure of the project definition changes, and so does the structure of the template context. If artifacts are using the `templates` processor, the files could have references to v1 fields, like `ctx.native_app.stage`, for example. These references would then be invalid after the v2 conversion, since the template context now only has data about v2 entities. We therefore need to convert these template references to the equivalent v2 references using information from the conversion process. We don't convert `ctx.env.` or `fn.` references since those don't change from v1 to v2.

SNOW-1772200 Convert templates in artifacts when converting PDF from v1 to v2

---

src/snowflake/cli/api/metrics.py
tests/api/metrics/test_metrics_spans.py

- implement depth and total limits for spans so that the column housing the telemetry doesn't blow up
- added `count_spans_in_subtree`, `span_depth`, `trimmed` fields to reporting dict to make investigation easier if we do reach the limits
- chose to do metadata augmentation on the span tree as we're making it to make the postprocessing easier (e.g. no need to build an adjacency matrix and bfs at the end, we can use simple python builtins, which makes the implementation cleaner/more declarative, and easier to read and maintain imo

implement depth & total span limits with tests

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/artifacts.py
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/sf_facade_exceptions.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
src/snowflake/cli/_plugins/nativeapp/version/commands.py
src/snowflake/cli/_plugins/workspace/commands.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_artifacts.py
tests/nativeapp/test_version_create.py
tests/nativeapp/test_version_drop.py
tests_integration/nativeapp/__snapshots__/test_version.ambr

Added `--label` option to `snow app version create`. version label in `manifest.yml` will be ignored if this option is provided. 
Other changes:
- `--patch` can be provided to the cli even if there is no version name specified in the cli. `manifest.yml will be checked for the version name. if there is a conflicting patch in the manifest, the user will have to confirm to use the cli-provided patch.   
- If a version name is provided through the cli, all version info from manifest (version name, patch, and label) are ignored.

Add --label to version create

---

src/snowflake/cli/_plugins/spcs/common.py
src/snowflake/cli/_plugins/spcs/services/commands.py
src/snowflake/cli/_plugins/spcs/services/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/test_services.py
tests_integration/spcs/test_services.py
tests_integration/spcs/testing_utils/spcs_services_utils.py

The updated snow spcs service logs command now supports additional parameters for enhanced log retrieval and monitoring:
--since: Start log retrieval from a specified UTC timestamp.
--include-timestamps: Add timestamps to log entries for log streaming.
--follow (-f): Stream logs in real-time.
--follow-interval: Customize polling intervals during log streaming.
Design Doc:
https://docs.google.com/document/d/1hvGC97jfvhfcg6gyPnFUl5j2-Xc1MKWy6C7ftc5JZ1c/edit?tab=t.0#heading=h.an8exbgprj8y

SNOW-1789074: SPCS Log streaming - SNOWCLI

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
src/snowflake/cli/api/entities/utils.py
tests/nativeapp/test_manager.py
tests/nativeapp/test_sf_sql_facade.py
tests/nativeapp/utils.py
tests_integration/nativeapp/test_version.py

If a user only has the following permissions:
- `MONITOR` on the package
- `USAGE` on the stage’s schema
- `READ` on the stage
- `MANAGE VERSIONS` on the package
They should still be able to create a new version. 
To remove the requirement to have privilege to create a stage, we now check if the stage exists instead of doing `create stage if not exists`. To remove the requirement to have privilege to check for release directives, we now show a different warning if we couldn't check whether a version is already included in a release directive.

SNOW-1763420 Allow creating version with only MANAGE VERSIONS privilege

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/api/project/definition_conversion.py
tests/helpers/__snapshots__/test_v1_to_v2.ambr
tests/helpers/test_v1_to_v2.py
tests/project/test_project_definition_v2.py

* make manifest field optional in pdfV2 definition of application package
* don't generate manifest field in v1-to-v2 conversions
Change to snowflake-cli-templates to exclude the field when cli version >= 3.2.0
https://github.com/snowflakedb/snowflake-cli-templates/pull/15

Make manifest optional in application package pdfV2

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/spcs/services/commands.py
src/snowflake/cli/_plugins/spcs/services/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/test_services.py

**Enhanced `snow spcs service logs` Command with New Parameters**
This pull request introduces improvements to the `snow spcs service logs` command by adding new parameters, allowing for more flexible and efficient log retrieval and monitoring:
- **New Parameter: `--previous-logs (-p)`**  
- Allows users to retrieve logs from the last terminated container instance, improving accessibility to historical logs and enhancing debugging visibility.
```shell
snow spcs service logs log_pre --container-name log-restart --instance-id 0 -p
```
- This command retrieves logs from the previously terminated container if it exists. Error handling has been added to notify users if no previous container instance is available or if incompatible flags are used.

Snow 1789099: SnowCLI integrates with spcs previous logs

---

src/snowflake/cli/api/config.py
tests/test_config.py
tests/testing_utils/fixtures.py

Fix for fix from #1791 , which was failing in case we had all connections in `connections.toml` and `config.toml` was empty.

Fix for connections.toml with empty config.toml

---

tests_integration/nativeapp/test_version.py

Removed metric_level field from response

Removed metric_level field from response

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/connection/commands.py

Default value `[]` was visible in prompts for `snow connection add`.

Fix for default visible in connection add

---

RELEASE-NOTES.md
pyproject.toml
scripts/packaging/Dockerfile

* SNOW-1790301: downgrade python to 3.10
Cherry pick of #1900

Snow 1790301 linux build fix (#1900)

---

RELEASE-NOTES.md
src/snowflake/cli/__about__.py
tests_e2e/__snapshots__/test_installation.ambr

* SNOW-1790301: downgrade python to 3.10
Version bump and release notes update

v3.2.1: version bump and release notes update

---

.gitignore
src/snowflake/cli/_plugins/nativeapp/artifacts.py
tests/nativeapp/test_artifacts.py

Having a mis-formatted version field in the manifest.yml throws the wrong error: 
`Error: Manifest.yml file does not contain a value for the version field.`
This PR fixes this to throw the appropriate error.

Fix error message for mis-formatted version field in manifest.yml

---

tests_integration/nativeapp/__snapshots__/test_version.ambr
tests_integration/nativeapp/test_version.py

* (N/A) I've added or updated automated unit tests to verify correctness of my new code.
* (N/A) I've described my changes in the release notes.
There is a version integ test that is brittle in the face of new columns. This change makes it resilient to columns being added, without weakening the current assertions.

Make version test resilient to new fields

---

pyproject.toml
snyk/requirements.txt
tests_e2e/conftest.py

Snowpark 1.26.0 breaks native app's snowpark integration. It looks like a new piece of logic was introduced that incorrectly assumes that Snowpark has a valid session, which is not the case when we execute Snowpark in the CLI sandbox. NADE will need to work with the Snowpark team on the fix or workaround, until then we shouldn't use the buggy library.

Downgrade snowpark lib until a fix is identified

---

tests/nativeapp/test_artifacts.py
tests/snowpark/test_function.py
tests/streamlit/test_artifacts.py
tests/streamlit/test_commands.py
tests/testing_utils/fixtures.py
tests_integration/conftest.py

The feature branch is currently broken. This PR fixes the merge gates so that work can continue on the branch.
This is mostly work from @sfc-gh-astus, I just ensured that the quality gates pass (and removed the tweaks to pre-commit as they're not necessary and shouldn't be merged to main)

Fix rebase issues in feature/unification-artifacts

---

src/snowflake/cli/_plugins/nativeapp/codegen/templates/templates_processor.py
tests/nativeapp/codegen/templating/test_templates_processor.py
tests/nativeapp/utils.py

Template processor should not fail if it can't read a file.

Soften error to warning in template processor when fails to read file

---

src/snowflake/cli/_plugins/nativeapp/codegen/compiler.py
src/snowflake/cli/_plugins/nativeapp/codegen/setup/native_app_setup_processor.py
src/snowflake/cli/_plugins/nativeapp/codegen/snowpark/python_processor.py
src/snowflake/cli/_plugins/nativeapp/codegen/templates/templates_processor.py
src/snowflake/cli/api/project/definition_conversion.py
tests/nativeapp/codegen/test_compiler.py
tests_integration/helpers/test_v1_to_v2.py

* (N/A) I've added or updated integration tests to verify correctness of my new code.
* (N/A) I've described my changes in the release notes.
This change is part 1 of a series of refactorings aiming to enable the templates processor in domains other than native apps. This change specifically aims to move domain logic out of the compiler and into individual processors. This will facilitate moving the common portion of the processors to a shared location (under the `artifacts` module in the CLI's API). Attempting to do so now would leave a significant number of references to native apps in common code, which I would prefer to avoid.

Move domain logic to individual processors

---

RELEASE-NOTES.md
src/snowflake/cli/api/project/util.py
tests/project/test_util.py
tests/test_utils.py
tests_integration/nativeapp/test_version.py

Adding patches to versions with non-SQL safe characters (like v1.0) was failing:
`snow app version create v1.0` succeeds (creates a version)
`snow app version create v1.0` fails - doesn't recognize that version was already created and attempts recreation
`snow app version create v1.0 --patch 3` fails - doesn't recognize the version, so can't add patch.

Fix not able to add patch to quoted versions

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
src/snowflake/cli/_plugins/nativeapp/version/commands.py
tests/nativeapp/test_sf_sql_facade.py
tests/nativeapp/test_version_create.py
tests/nativeapp/test_version_drop.py
tests/nativeapp/utils.py
tests_integration/nativeapp/__snapshots__/test_version.ambr
tests_integration/nativeapp/test_version.py

- Add support for release channels in snow app version create
- Create/Drop now uses Register/Deregister instead of Add/Drop when creating/dropping versions.
- `snow app version create` now returns version and patch in json format.
- fix to label being set to ""(blank) when not provided by CLI (instead of None)

Add support for release channels in snow app version create

---

src/snowflake/cli/api/rest_api.py
tests_integration/test_object.py

Temporarily disable schema existence check for object create due to server-side issue
https://snowflakecomputing.atlassian.net/browse/SNOW-1855040

Temporarily disable schema existence check for object create

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/entities/application.py
src/snowflake/cli/_plugins/nativeapp/release_directive/commands.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_event_sharing.py
tests/nativeapp/test_run_processor.py
tests/nativeapp/test_sf_sql_facade.py
tests_integration/nativeapp/test_init_run.py

Add support for snow app run from release channel:
* you can run `snow app run --from-release-directive --channel=my_channel` to run from release directive of channel `my_channel`.
* `--from-release-directive` is required to be specified with `--channel`
* for app upgrades, we check if channel is the same - if not, we provide the option to drop and recreate the app instance.

Add support for snow app run from release channel

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/streamlit/manager.py
src/snowflake/cli/api/project/schemas/v1/streamlit/streamlit.py
tests/api/utils/test_definition_rendering.py
tests/streamlit/test_streamlit_manager.py

Moved default Streamlit warehouse from model
Added depreciation message

Moved default streamlit warehouse from model

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/release_channel/__init__.py
src/snowflake/cli/_plugins/nativeapp/release_channel/commands.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/__snapshots__/test_application_package_entity.ambr
tests/nativeapp/test_application_package_entity.py
tests/nativeapp/test_sf_sql_facade.py

Add support for `snow app release-channel list [CHANNEL]` command.
Integ tests will be added once UIParam is in production

Add release channels list support

---

pyproject.toml
snyk/requirements.txt

* Pinning `click` version to 8.1.7 because our integration tests currently fail on 8.1.8. Typer uses `click>=8.0.6` requirement. We'll continue debugging of issues with 8.1.8 and remove the pin later.

[SNOW-1874231] Pinning click to 8.1.7 as temporary workaround to unblock tests failing by recent changes in click

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/version/commands.py
src/snowflake/cli/_plugins/workspace/commands.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_version_create.py
tests_integration/nativeapp/test_version.py

Add --from-stage option to version create
When `--from-stage` is provided, `snow app version create --from-stage` will create a version from the content of the stage directly without resyncing the local files to the stage.

Add --from-stage option to version create

---

src/snowflake/cli/_plugins/nativeapp/commands.py
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_application_package_entity.py
tests/nativeapp/test_sf_sql_facade.py
tests/nativeapp/test_version_create.py

Allow --create-version in `snow app publish` command.
If user wants us to create the version and patch that they provided, they need to pass `--create-version` flag. This will delegate to the version create command to handle the version creation and then continue with the regular publish workflow.
The same logic of falling back to the manifest will also apply in that case, which makes version and patch optional.

Add support for --create-version in snow app publish

---

src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
tests/nativeapp/__snapshots__/test_application_package_entity.ambr
tests/nativeapp/test_application_package_entity.py
tests/nativeapp/test_run_processor.py
tests/nativeapp/test_sf_sql_facade.py
tests/nativeapp/utils.py

- Fix messaging for errors for release channels/directives features.
- same_identifier() replaced with unquote_identifier() check. The reason is that identifiers in SnowCLI are different than what is stored in the backend. The backend never uses quotes in its output. It uses capitalization to indicate that.
For example:
- `abc` locally is the same as `ABC` on the server.
- `"abc"` locally is the same as `abc` on the server but different from `ABC` on the server.
- `a.bc` locally is the same as `a.bc` on the server, because it contains special characters and SnowCLI automatically quotes it.
Instead of `same_identifier(local, remote_identifier)`, the check should change to:
`unquote_identifier(local) == remote_identifier`

Bug fixes and improvements to release directives and channels commands

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/spcs/compute_pool/commands.py
src/snowflake/cli/_plugins/spcs/compute_pool/compute_pool_entity.py
src/snowflake/cli/_plugins/spcs/compute_pool/compute_pool_entity_model.py
src/snowflake/cli/_plugins/spcs/compute_pool/manager.py
src/snowflake/cli/api/project/schemas/entities/entities.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/test_compute_pool.py
tests/test_data/projects/spcs_compute_pool/snowflake.yml
tests/test_data/projects/spcs_multiple_compute_pools/snowflake.yml
tests_integration/spcs/test_compute_pool.py
tests_integration/spcs/testing_utils/compute_pool_utils.py
tests_integration/test_data/projects/spcs_compute_pool/snowflake.yml

Added new command `snow spcs compute-pool deploy` using snowflake.yml.
Added `--replace` flag for `snow spcs compute-pool create` command.

Added snow spcs compute-pool deploy command

---

pyproject.toml
snyk/requirements.txt
src/snowflake/cli/_app/cli_app.py
src/snowflake/cli/_app/commands_registration/commands_registration_with_callbacks.py
tests/__snapshots__/test_help_messages.ambr
tests/test_main.py
tests_e2e/__snapshots__/test_installation.ambr

* Click 8.1.8 fixed eagerness of help option but as the result its callback is now evaluated before our eager options. This is problematic for CLI because command registration is based on evaluation of eager options and default help option cannot now present commands registered by our plugins mechanism. To fix it, I added custom help option working almost the same as the default one. The only difference is that it's displayed as the first option, not the last option like the default one.
* Thanks to this change I was able to remove the pin to click 8.1.7 and I did it.

[SNOW-1874231] Fixes for click 8.1.8 (custom help option)

---

src/snowflake/cli/_app/__main__.py
src/snowflake/cli/_app/cli_app.py
src/snowflake/cli/_app/commands_registration/commands_registration_with_callbacks.py
tests/test_connection.py
tests/test_docs_generation_output.py
tests/test_main.py
tests/testing_utils/fixtures.py
tests_integration/conftest.py
tests_integration/test_external_plugins.py

* Introduced `CliAppFactory`, which wraps all callback definitions. Thanks to that, callbacks and commands are not registered globally but only within an instance of `CliAppFactory`. The factory exposes `create_or_get_app` method.
* Removed global `AppContextHolder` in favour of `get_click_context` method exposed by `CliAppFactory`. Click context was and still is needed in tests traversing command tree (like docs generation tests).
* Simplified `commands_registration_with_callbacks.py`.
* The main change is removed `before` callback wrapper. It was used to invoke commands registration as soon as possible but IMO it's not needed to do it as soon as possible and we can invoke registration from `commands_registration_callback` after processing all eager CLI options (what we did anyway but …

[SNOW-1747456] Remove side effects from command registration

---

src/snowflake/cli/_plugins/streamlit/manager.py
src/snowflake/cli/_plugins/streamlit/streamlit_entity_model.py
src/snowflake/cli/api/project/schemas/entities/common.py
tests/streamlit/test_streamlit_manager.py
tests_integration/test_data/projects/streamlit_v2/snowflake.yml

Add grants support to Streamlit entity

---

src/snowflake/cli/api/sql_execution.py
tests_integration/test_data/projects/napp_application_post_deploy_v1/scripts/app_post_deploy2.sql
tests_integration/test_data/projects/napp_application_post_deploy_v1/scripts/package_post_deploy2.sql
tests_integration/test_data/projects/napp_application_post_deploy_v2/scripts/app_post_deploy2.sql
tests_integration/test_data/projects/napp_application_post_deploy_v2/scripts/package_post_deploy2.sql

Fix failure to SQL scripts when there is a comment at the end of the file.
- Before the fix, any SQL script with comment at the end of the file will result in "Empty SQL Statement" error.
- After the fix, error should disappear
Updated integration tests to cover this usecase.
Error comes from Snowflake backend and is caused by a library, so the only way to cover this usecase is through integration tests (not unit tests)

Fix failure to SQL scripts when there is a comment at the end of the file

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
src/snowflake/cli/_plugins/nativeapp/release_channel/commands.py
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
src/snowflake/cli/api/entities/common.py
tests/__snapshots__/test_help_messages.ambr
tests/nativeapp/test_application_package_entity.py
tests/nativeapp/test_sf_sql_facade.py
tests/nativeapp/utils.py
tests_integration/nativeapp/test_release_channels.py

Add `snow app release-channel set-accounts` command.
We already have `snow app release-channel add-accounts` and `remove-accounts` commands. This one provides another option to set accounts by replacing the whole list of accounts instead of adding or removing.

Add commands to set-accounts for release channels (add-accounts/remove-accounts already exist)

---

RELEASE-NOTES.md
src/snowflake/cli/_app/printing.py
tests/test_printing.py

Fixes SQL command output formating. Before:
```
➜ snow sql -q 'select current_date();' --format=JSON
[
{
"CURRENT_DATE()": %      
```
and after
```
➜ snow sql -q 'select current_date();' --format=JSON        
[
{
"CURRENT_DATE()": "2025-02-17"
}
]
```

Fix date handling in sql cmd when using json

---

pyproject.toml
src/snowflake/cli/_app/commands_registration/builtin_plugins.py
src/snowflake/cli/_plugins/project/commands.py
src/snowflake/cli/_plugins/project/feature_flags.py
src/snowflake/cli/_plugins/project/manager.py
src/snowflake/cli/_plugins/project/plugin_spec.py
src/snowflake/cli/_plugins/project/project_entity_model.py
src/snowflake/cli/_plugins/stage/manager.py
src/snowflake/cli/_plugins/streamlit/commands.py
src/snowflake/cli/_plugins/streamlit/manager.py
src/snowflake/cli/api/artifacts/upload.py
src/snowflake/cli/api/commands/utils.py
src/snowflake/cli/api/project/schemas/entities/entities.py
src/snowflake/cli/api/project/schemas/entities/project_entity_model.py
tests/__snapshots__/test_help_messages.ambr
tests/dcm_project/test_dcm_project.py
tests/dcm_project/test_dcm_project_manager.py
tests/streamlit/__snapshots__/test_commands.ambr
tests/streamlit/test_streamlit_manager.py
tests/test_data/projects/dcm_project/snowflake.yml
tests/test_performance.py
tests_integration/conftest.py
tests_integration/test_data/projects/dcm_project/file_a.sql
tests_integration/test_data/projects/dcm_project/manifest.yml
tests_integration/test_data/projects/dcm_project/snowflake.yml
tests_integration/test_dcm_project.py

Add `snow project` commands hidden behind a feature flag.

Add project commands

---

RELEASE-NOTES.md
pyproject.toml
snyk/requirements.txt
src/snowflake/cli/_app/commands_registration/builtin_plugins.py
src/snowflake/cli/_app/snow_connector.py
src/snowflake/cli/_plugins/auth/__init__.py
src/snowflake/cli/_plugins/auth/keypair/commands.py
src/snowflake/cli/_plugins/auth/keypair/manager.py
src/snowflake/cli/_plugins/auth/keypair/plugin_spec.py
src/snowflake/cli/_plugins/object/manager.py
src/snowflake/cli/api/commands/flags.py
src/snowflake/cli/api/secret.py
src/snowflake/cli/api/secure_path.py
tests/__snapshots__/test_help_messages.ambr
tests/auth/__snapshots__/test_auth.ambr
tests/auth/test_auth.py
tests/test_connection.py
tests/test_snow_connector.py
tests_e2e/__snapshots__/test_installation.ambr
tests_integration/snowflake_connector.py

* Added new `snow auth keypair` commands:
* `setup` - generate key pair, set public key for the user in Snowflake and create/update the connection.
* `rotate` - rotate keys for connection.
* `list` - list the public keys for the user.
* `remove` - remove the public key for the user.

Added snow auth keypair setup/rotate/list/remove commands

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/stage/manager.py
tests/stage/test_stage.py

https://snowflakecomputing.atlassian.net/browse/SNOW-1966187
Fixes a bug where recursive copying to stage for unbalanced directory trees was not working as expected due to potential deletion of directories before they were processed.

feat: [SNOW-1966187] fix recursive copy for unbalanced trees

---

RELEASE-NOTES.md
src/snowflake/cli/_app/snow_connector.py
src/snowflake/cli/_app/telemetry.py
src/snowflake/cli/_plugins/auth/keypair/commands.py
src/snowflake/cli/_plugins/auth/keypair/manager.py
src/snowflake/cli/_plugins/connection/commands.py
src/snowflake/cli/api/secure_path.py
tests/__snapshots__/test_help_messages.ambr
tests/auth/__snapshots__/test_auth.ambr
tests/auth/test_auth.py
tests/test_connection.py
tests/test_secret_type.py
tests/testing_utils/fixtures.py

Added `snow auth keypair status` command to verify the key pair configuration and test the connection.
The `snow connection add` command has been enhanced to include key pair authentication when a password is provided.
Added support for ~ in SecurePath

Added auth keypair status command and extended connection add

---

scripts/packaging/build_isolated_binary_with_hatch.py
src/snowflake/cli/__about__.py
src/snowflake/cli/_app/telemetry.py

Fix binaries introducing themselves as pypi installation in telemetry.
**Changes:**
* Introduce variable `IS_INSTALLED_FROM_BINARY` variable to `__about__.py`, which is overridden by binary building script. The script will fail if the variable is not defined.
**Tests:**
* Branch `pczajka-test-telemtry` contains "debug" commit that adds debug info to "connection list" command.
* Check pypi version:
```
> pip install git+https://github.com/snowflakedb/snowflake-cli.git@pczajka-test-telemtry
> snow connection list
Checking installation source:
pypi
```
* Check binary version:
```
> python scripts/packaging/build_isolated_binary_with_hatch.py
> ./dist/binary/snow-3.6.0rc0 connection list
Checking installation source:
binary
```

Snow 1999047 fix binaries visible as pypi in telemetry

---

pyproject.toml
tests_integration/test_git.py

Change repository used in most integration tests to a tiny one (https://github.com/snowflakedb/homebrew-snowflake-cli/), as the size of this repository (used until now) causes issues for SnowGit team (copy operation alerts started firing). This repository remains cloned only for execute tests.

Change git repository used in integration tests

---

src/snowflake/cli/_plugins/project/project_entity_model.py
src/snowflake/cli/api/cli_global_context.py
tests/dcm_project/test_project_entity_model.py
tests/test_data/projects/dcm_project/snowflake.yml
tests_integration/test_data/projects/dcm_project/snowflake.yml

main file should not be configurable. Neither it's name nor location in project directory. It must be always called manifest.yml and it must be in project root.
Additionally added checks in cli to confirm that the file exists.
Review together with https://github.com/snowflakedb/snowflake-cli-templates/pull/22
When trying to init a project from the updated template it works as expected, and uploads manifest.yml without having to specify it in snowflake.yml:
```
$ snow project create
Creating project 'with_manifest'
Uploading artifacts
Creating stage my_project_stage if not exists.
Performing a diff between the Snowflake stage: my_project_stage and your local deploy_root: /Users/jwilkowski/snowflake/snowflake-cli/data_proj/output/bundle.
Local changes to be deployed:
added: …
```

feat: [SNOW-2026174] make project's manifest.yml required

---

src/snowflake/cli/_plugins/project/commands.py
tests/__snapshots__/test_help_messages.ambr
tests_integration/test_data/projects/dcm_project/snowflake.yml
tests_integration/test_dcm_project.py

There's a confusion between `entity_id` and `identifier` in the project commands. This PR fixes list-versions command (which doesn't use pdf) and makes the difference between identifiers more explicit in integration tests

fix: [SNOW-2032682] fix project entity_id vs identifier

---

src/snowflake/cli/_plugins/project/commands.py
src/snowflake/cli/api/commands/flags.py
tests/__snapshots__/test_help_messages.ambr
tests/dcm_project/test_commands.py
tests_integration/test_dcm_project.py

https://snowflakecomputing.atlassian.net/browse/SNOW-2057523
For avoidance of doubt: when a file gets deleted from a project, subsequent project execution will "unapply" changes from that deleted file

feat: [SNOW-2057523] make project add-version prune stage by default

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/sql/commands.py
src/snowflake/cli/_plugins/sql/manager.py
src/snowflake/cli/_plugins/sql/snowsql_commands.py
src/snowflake/cli/_plugins/sql/statement_reader.py
tests/sql/__snapshots__/test_repl.ambr
tests/sql/__snapshots__/test_sql.ambr
tests/sql/test_snowsql_commands.py
tests/sql/test_statement_reader.py
tests_integration/sql/__snapshots__/test_snowsql_commands.ambr
tests_integration/sql/test_snowsql_commands.py

Add support for `!queries`, `!result` and `!abort` commands for SnowSQL. They're meant to be used in `--output=TABLE` format and might malfunction when mixed with other commands in `--json` output format.

Add support for queries, result and abort commands

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/snowpark/package/anaconda_packages.py
tests/snowpark/test_anaconda.py
tests/snowpark/test_package.py
tests_integration/test_snowpark.py

Created workaround for missing `!=` operator for package import in Snowpark

SNOW-2054743 Fix for error with `!=` in requirements

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
src/snowflake/cli/api/sql_execution.py
tests/api/test_sql_execution.py
tests/nativeapp/test_run_processor.py
tests/nativeapp/test_sf_sql_facade.py

Fix escaping identifiers for "use" commands in SqlExecutor and nativeapp's SnowflakeSQLFacade
Set connection role to one requiring escaping (for example `test-role`) and follow [this tutorial](https://quickstarts.snowflake.com/guide/native-app-chairlift/index.html?index=..%2F..index#0) - `snow app run` command should succeed

Snow 2089072 fix escaping identifiers for "use" commands

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/snowpark/common.py
src/snowflake/cli/_plugins/snowpark/snowpark_entity.py
src/snowflake/cli/_plugins/snowpark/snowpark_entity_model.py
tests/snowpark/__snapshots__/test_models.ambr
tests/snowpark/__snapshots__/test_snowpark_entity.ambr
tests/snowpark/test_models.py
tests/snowpark/test_snowpark_entity.py
tests_integration/test_data/projects/snowpark_artifact_repository/app.py
tests_integration/test_data/projects/snowpark_artifact_repository/requirements.txt
tests_integration/test_data/projects/snowpark_artifact_repository/snowflake.yml
tests_integration/test_snowpark.py

Adding `artifact_repository` and `artifact_repository_packages` fields to the Snowpark Entity Model to support direct usage of non-anaconda packages

Add artifact repository fields to Snowpark Entity Model

---

pyproject.toml
src/snowflake/cli/_plugins/spcs/image_repository/commands.py
src/snowflake/cli/_plugins/spcs/image_repository/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/test_image_repository.py
tests_integration/spcs/test_image_repository.py

Today, CLI command from spcs image repo list-images is not updated with SQL version and does not support filtering using like ''. 
This change adds support for filtering images based on a like pattern 
`show images like '%openflow%' in image repository snowflake.images.snowflake_images;`

FLOW-2736: Enable filtering show images output using like

---

pyproject.toml
snyk/requirements.txt

After `click 8.2.0` release typer raises error while displaying help messages. This PR freezes click dependency to latest compatible version (`8.1.8`)

fix error showing for --help messages

---

RELEASE-NOTES.md
pyproject.toml
snyk/requirements.txt
src/snowflake/cli/__about__.py

* update `snowflake-connector-python` to 3.15
* https://github.com/snowflakedb/snowflake-cli/pull/2238
* https://github.com/snowflakedb/snowflake-cli/pull/2272

Cherry picks to 3.7.2

---

RELEASE-NOTES.md
src/snowflake/cli/_plugins/spcs/image_registry/commands.py
src/snowflake/cli/_plugins/spcs/image_registry/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/test_registry.py

This PR enhances the `snow spcs image-registry url` command by adding a `--private-link` flag. When used, the command will return the private link URL (or an empty response if not available) instead of the public URL.
This is cherry-pick of https://github.com/snowflakedb/snowflake-cli/pull/2275

SNOW-2097298: Add --private-link flag to the snow spcs image-registry url command

---

src/snowflake/cli/_plugins/cortex/commands.py
src/snowflake/cli/_plugins/cortex/constants.py
src/snowflake/cli/_plugins/cortex/manager.py
tests/__snapshots__/test_docs_generation_output.ambr
tests/cortex/test_cortex_commands.py

This PR is a resubmission of a previous one that encountered issues with the CI merge gates and was unable to proceed.
Original PR: https://github.com/snowflakedb/snowflake-cli/pull/2152
This new PR contains the same code changes as the original.
The Snowflake CLI has a snowflake cortex complete command which calls into Cortex complete, but uses the SQL backend. This means that latency will be more variable for users using this tool.
This PR:
Changes the default model to llama3.1-70b.
Adds a --backend flag to switch between SQL and REST backends and implements support for calling into both.
Enables REST backend by default.
...

SNOW-1994541: Change cortex complete to use snowflake.core APIs

---

src/snowflake/cli/_plugins/spcs/image_registry/commands.py
src/snowflake/cli/_plugins/spcs/image_registry/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/spcs/__snapshots__/test_registry.ambr
tests/spcs/test_registry.py

This PR enhances the `snow spcs image-registry login` command by adding a `--private-link` flag. When used, the command will log in using the private link URL instead of the public URL.

SNOW-2089589: add --private-link flag to the snow spcs image-registry login command

---

tests_integration/nativeapp/test_init_run.py

Fix failing integ tests due to release channels enabled by default
`snow app publish` should handle both cases (enabled/disabled)

Fix failing integ tests due to release channels enabled by default

---

tests_integration/tests_using_container_services/spcs/test_registry.py
tests_integration/tests_using_container_services/spcs/test_services.py
tests_integration/tests_using_container_services/spcs/testing_utils/spcs_services_utils.py

* The permissions check is ran on the server
* The server introduced "secondary roles" since the tests was added, so firing this check would require big changes in integration account setup
*  "no permissions" case is covered by unit tests

Snow 2148566 fix flaky spcs tests

---

scripts/packaging/delete_mac_certs.sh
scripts/packaging/load_mac_certs.sh

The changes are not touching any code so the above checks are not applicable. The change is only to enable dynamic loading of the mac certs so these are more secure and not always enabled on the node, but only for the signing.

SNOW-2118790: Adding new scripts for dynamic mac certification loading within Jenkins building Job

---

scripts/packaging/delete_mac_certs.sh
scripts/packaging/load_mac_certs.sh

Added keychain refresh after importing new certs from FUSE secrets and used delete-identity instead of delete-certificate for not enabling loose private keys within node when not used. I am adding only changes to scripts used by Jenkins Jobs so the logic of this service is not touched hence the above checks does not apply.

SNOW-2118790: security fixes

---

scripts/packaging/load_mac_certs.sh

Changing the md5sum to md5 as older machines using x86 does not support md5sum. This change does not change logic of the service, but only release scripts used by jenkins so above checks does not apply.

SNOW-2118790: Moved from md5sum to md5 as it is not supported

---

RELEASE-NOTES.md
src/snowflake/cli/api/stage_path.py
tests/stage/test_stage_path.py

SNOW-2210870 Proper `is_dir` and `is_file` implementations - use `is_file` and `is_dir` from `Path`

SNOW-2210870 Proper `is_dir` and `is_file` implementations

---

src/snowflake/cli/_plugins/dcm/commands.py
src/snowflake/cli/_plugins/dcm/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/dcm/test_commands.py
tests/dcm/test_manager.py
tests_integration/test_dcm_project.py

This PR addresses the following:
* Removing `snow dcm add-version`
* * `--prune` and `--alias` logic moved to `dcm plan` and `dcm deploy`
* Removing `--no-version` flag on `dcm create` and removed creating initial version whatsoever

SNOW-2229492 and SNOW-2229493 - cleanup versions in DCM

---

src/snowflake/cli/_plugins/dcm/commands.py
src/snowflake/cli/_plugins/dcm/manager.py
tests/__snapshots__/test_help_messages.ambr
tests/dcm/test_commands.py
tests/dcm/test_manager.py
tests_integration/test_dcm_project.py

This PR adds `--output-path` to `snow dcm plan`. It allows to write rendered SQLs in given location

SNOW-2231968 Add `--output-path` to `snow dcm plan`

---

README.md

Since uv now far supercedes what pipx does, and has ~ an order of magnitude more usage (https://pypistats.org/packages/uv vs https://pypistats.org/packages/pipx), this switches out pipx instructions for uv (or uvx)

Update README.md to show uv instead of pipx

---

src/snowflake/cli/_plugins/connection/commands.py
tests/__snapshots__/test_help_messages.ambr
tests/test_connection.py

* [] I've described my changes in the release notes.
Changed connection name to be argument of snow connection remove command. An option felt inconsistent with other commands and also if that argument was not provided, CLI broke

feat: [SNOW-988145] provide connection name as arg

---

src/snowflake/cli/_app/cli_app.py

The `test_broken_plugin` and `test_failing_plugin` tests were reported flaky. The expected log messages contained only information about directory creation that indicates that plugins were not discovered. This could happen due to both `commands_registration` and `configuration_file` being marked as `eager` and some race condition there. Also, given `commands_registration` should be the last one, it shouldn't be eager in the first place.
Closes #2479 and #2468

SNOW-2191699 SNOW-2181193 commands_registration shouldn't be eager

---

scripts/packaging/win/build_installer.bat

This change replaces hardcoded key name in the script that builds the Windows installer with variable reference that has been added to the Jenkins job in the other PR.
Test run: https://es-ci-legacy-mainvalidation-001.jenkinsdev1.us-west-2.aws-dev.app.snowflake.com/job/SnowflakeCLI-Win-x86-64-Installer/245/console
The key name value from the parameter has been used correctly:

SNOW-1555911: Replace hardcoded keypair alias with variable for signing windows installer

---

src/snowflake/cli/_app/commands_registration/command_plugins_loader.py

There's possibility of a race condition in loading plugins, order is unknown and override plugin can be added before build-in one. This change adds sorting of plugins by name to have fixed order and ensures that internal plugin is loaded before external one, even with the same name. 
Fixes #2604

SNOW-2337682 Ensure built-in plugins are loaded first.

---

src/snowflake/cli/_plugins/logs/manager.py
tests/logs/__snapshots__/test_logs.ambr
tests/logs/test_logs.py

SNOW-2347456 Properly escape `_` and `%` in `snow logs --partial`

---

tests_integration/test_object.py

Comparing result of `snow object list warehouses` with `show warehouses` is prone to timing issues - another warehouses can be added/removed between the calls - and this test was flaky.
This PR makes it stable.
Closes: #2570

SNOW-2305287 make non-flaky version of testing show warehouses
